### ISSUE TITLE
OpenBSD: ./configure[13306]: /: cannot execute - Is a directory

### ISSUE THREAD

**Issue by juanfra684** [gambit/gambit#124]
configure shows various errors on OpenBSD

```
checking whether ln -s works... yes
checking for ranlib... (cached) ranlib
checking for ar... (cached) ar
./configure[13306]: /: cannot execute - Is a directory
./configure[13306]: /: cannot execute - Is a directory
./configure[13306]: g": not found
sed: 1: ""s": invalid command code "
./configure[13334]: /: cannot execute - Is a directory
./configure[13334]: g": not found
./configure[13334]: /: cannot execute - Is a directory
sed: 1: ""s": invalid command code "
./configure[13334]: /: cannot execute - Is a directory
./configure[13334]: /: cannot execute - Is a directory
./configure[13334]: g": not found
sed: 1: ""s": invalid command code "
./configure[13334]: /: cannot execute - Is a directory
./configure[13334]: /: cannot execute - Is a directory
./configure[13334]: g": not found
sed: 1: ""s": invalid command code "
./configure[13334]: /: cannot execute - Is a directory
./configure[13334]: /: cannot execute - Is a directory
./configure[13334]: g": not found
sed: 1: ""s": invalid command code "
checking whether make sets $(MAKE)... (cached) yes
configure: creating ./config.status
config.status: creating makefile
config.status: creating include/makefile
```

**Comment by adam-7** [comment]
@juanfra684  , what Gambit version?

**Comment by feeley** [comment]
Can you show the complete configure output including the configure command?  The content of config.log will be instructive too.

**Comment by adam-7** [comment]
People tried configure there before never any issue. I suggest if there's no updates within 3 months, close this issue. Looking forward to any clarification @juanfra684 .

**Comment by juanfra684** [comment]
4.7.6. I've tested again with 4.8.3 and here is the configure output:

```
Using /usr/write-ports/pobj/gambit-4.8.3/config.site (generated)
configure: WARNING: unrecognized options: --disable-silent-rules, --disable-gtk-doc
configure: loading site script /usr/write-ports/pobj/gambit-4.8.3/config.site
checking build system type... x86_64-unknown-openbsd5.9
checking host system type... x86_64-unknown-openbsd5.9
checking target system type... x86_64-unknown-openbsd5.9
checking for gcc... cc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... (cached) o
checking whether we are using the GNU C compiler... (cached) yes
checking whether cc accepts -g... (cached) yes
checking for cc option to accept ISO C89... none needed
checking how to run the C preprocessor... cc -E
checking for grep that handles long lines and -e... (cached) /usr/bin/grep
checking for egrep... (cached) /usr/bin/egrep
checking for ANSI C header files... (cached) yes
checking for sys/types.h... (cached) yes
checking for sys/stat.h... (cached) yes
checking for stdlib.h... (cached) yes
checking for string.h... (cached) yes
checking for memory.h... (cached) yes
checking for strings.h... (cached) yes
checking for inttypes.h... (cached) yes
checking for stdint.h... (cached) yes
checking for unistd.h... (cached) yes
checking size of void*... 8
checking size of long... 8
checking for bool... no
checking whether cc defines __GNUC__... yes
checking whether cc defines __clang__...
checking whether cc defines __llvm__...
checking whether cc defines _MSC_VER...
checking whether cc defines _WIN32...
checking for errno.h... (cached) yes
checking for float.h... (cached) yes
checking for signal.h... (cached) yes
checking for stdio.h... (cached) yes
checking for stdlib.h... (cached) yes
checking for string.h... (cached) yes
checking for time.h... (cached) yes
checking for unistd.h... (cached) yes
checking for pwd.h... (cached) yes
checking for dlfcn.h... (cached) yes
checking dl.h usability... no
checking dl.h presence... no
checking for dl.h... no
checking sys/dxe.h usability... no
checking sys/dxe.h presence... no
checking for sys/dxe.h... no
checking mach-o/dyld.h usability... no
checking mach-o/dyld.h presence... no
checking for mach-o/dyld.h... no
checking for sys/types.h... (cached) yes
checking for sys/time.h... (cached) yes
checking for sys/times.h... (cached) yes
checking sys/timeb.h usability... no
checking sys/timeb.h presence... no
checking for sys/timeb.h... no
checking sys/timers.h usability... no
checking sys/timers.h presence... no
checking for sys/timers.h... no
checking for sys/resource.h... (cached) yes
checking for sys/wait.h... (cached) yes
checking for sys/mman.h... (cached) yes
checking for syslog.h... (cached) yes
checking for netdb.h... (cached) yes
checking for grp.h... (cached) yes
checking fpu_control.h usability... no
checking fpu_control.h presence... no
checking for fpu_control.h... no
checking os2.h usability... no
checking os2.h presence... no
checking for os2.h... no
checking dos.h usability... no
checking dos.h presence... no
checking for dos.h... no
checking direct.h usability... no
checking direct.h presence... no
checking for direct.h... no
checking wdefwin.h usability... no
checking wdefwin.h presence... no
checking for wdefwin.h... no
checking tfork.h usability... no
checking tfork.h presence... no
checking for tfork.h... no
checking curses.h usability... yes
checking curses.h presence... yes
checking for curses.h... yes
checking ncurses.h usability... yes
checking ncurses.h presence... yes
checking for ncurses.h... yes
checking for netinet/in.h... (cached) yes
checking for arpa/inet.h... (cached) yes
checking for termios.h... (cached) yes
checking for pty.h... (cached) no
checking stropts.h usability... no
checking stropts.h presence... no
checking for stropts.h... no
checking libutil.h usability... no
checking libutil.h presence... no
checking for libutil.h... no
checking for util.h... (cached) yes
checking sys/fpu.h usability... no
checking sys/fpu.h presence... no
checking for sys/fpu.h... no
checking fenv.h usability... yes
checking fenv.h presence... yes
checking for fenv.h... yes
checking for fcntl.h... (cached) yes
checking for sys/ioctl.h... (cached) yes
checking for sys/socket.h... (cached) yes
checking for strings.h... (cached) yes
checking for memory.h... (cached) yes
checking for sys/sysctl.h... (cached) yes
checking ws2tcpip.h usability... no
checking ws2tcpip.h presence... no
checking for ws2tcpip.h... no
checking TargetConditionals.h usability... no
checking TargetConditionals.h presence... no
checking for TargetConditionals.h... no
checking for poll.h... (cached) yes
checking for environ... yes
checking for _NSGetEnviron... checking crt_externs.h usability... no
checking crt_externs.h presence... no
checking for crt_externs.h... no
no
checking for remove... (cached) yes
checking for rename... (cached) yes
checking for sys/stat.h... (cached) yes
checking for mkdir... (cached) yes
checking for dirent.h... (cached) yes
checking for opendir... (cached) yes
checking for stat.h... (cached) no
checking for sys/stat.h... (cached) yes
checking for stat... (cached) yes
checking for stat64... no
checking for struct stat64... no
checking for socklen_t... yes
checking for library containing asin... -lm
checking for library containing dlopen... none required
checking for library containing shl_load... no
checking for library containing socket... none required
checking for library containing gethostbyname... none required
checking for library containing hstrerror... none required
checking for library containing openpty... -lutil
checking for library containing WSAStartup... no
checking for library containing timeBeginPeriod... no
checking for pipe... (cached) yes
checking for socketpair... (cached) yes
checking for chdir... (cached) yes
checking for execvp... (cached) yes
checking for getgrnam... (cached) yes
checking for getpid... (cached) yes
checking for getppid... (cached) yes
checking for getpwnam... (cached) yes
checking for ioctl... (cached) yes
checking for link... (cached) yes
checking for mkfifo... (cached) yes
checking for rmdir... (cached) yes
checking for socket... (cached) yes
checking for utimes... (cached) yes
checking for strerror... (cached) yes
checking for symlink... (cached) yes
checking for sysconf... (cached) yes
checking for sysctl... (cached) yes
checking for syslog... (cached) yes
checking for unlink... (cached) yes
checking for waitpid... (cached) yes
checking for mmap... (cached) yes
checking for fcntl... (cached) yes
checking for tcgetsetattr... yes
checking for sigaction... (cached) yes
checking for sigemptyset/sigaddset... yes
checking for sigprocmask... (cached) yes
checking for signal... (cached) yes
checking for clock_gettime... (cached) yes
checking for getclock... no
checking for gettimeofday... (cached) yes
checking for ftime... no
checking for time... (cached) yes
checking for nanosleep... (cached) yes
checking for sleep... (cached) yes
checking for getrusage... (cached) yes
checking for times... (cached) yes
checking for clock... (cached) yes
checking for DosQuerySysInfo... no
checking for setitimer... (cached) yes
checking for dos_setvect... no
checking for DosStartTimer... no
checking for VInstall... no
checking for shl_load... no
checking for DosLoadModule... no
checking for dxe_load... no
checking for GetDiskFragment... no
checking for dlopen... yes
checking for NSLinkModule... no
checking for gethostname... (cached) yes
checking for inet_pton... (cached) yes
checking for getaddrinfo... (cached) yes
checking for gethostbyname... (cached) yes
checking for gethostbyaddr... (cached) yes
checking for getservbyname... (cached) yes
checking for getservbyport... (cached) yes
checking for getprotobyname... (cached) yes
checking for getprotobynumber... (cached) yes
checking for getnetbyname... (cached) yes
checking for select... (cached) yes
checking for poll... (cached) yes
checking for ppoll... yes
checking for openpty... yes
checking for getpt... (cached) no
checking for ptsname... (cached) yes
checking for ctermid... (cached) yes
checking for isastream... no
checking for hstrerror... (cached) yes
checking for get_fpc_csr... no
checking how cc's preprocessor evaluates (__GNUC__*1000+__GNUC_MINOR__)>=4002&&(__GNUC__*1000+__GNUC_MINOR__)<=4003... yes
checking how cc's preprocessor evaluates __llvm__ && !__clang__ && (__GNUC__*1000+__GNUC_MINOR__)<4005...
checking whether cc accepts -no-cpp-precomp...  -no-cpp-precomp
checking whether cc accepts -fschedule-insns2...  -fschedule-insns2
checking whether cc accepts -fno-trapping-math...  -fno-trapping-math
checking whether cc accepts -fno-move-loop-invariants...  -fno-move-loop-invariants
checking whether cc accepts -fno-keep-inline-dllexport...
checking whether cc accepts -mieee...
checking whether cc accepts -mieee-with-inexact...
checking whether cc accepts -mieee-fp...  -mieee-fp
checking whether cc accepts -Wall...  -Wall
checking whether cc accepts -W...  -W
checking whether cc accepts -Wno-unused...  -Wno-unused
checking whether cc accepts -Wno-write-strings...  -Wno-write-strings
checking whether cc accepts -g...  -g
checking whether cc accepts -p...  -p
checking whether cc accepts -pg...  -pg
checking whether cc accepts -ftest-coverage...  -ftest-coverage
checking whether cc accepts -fprofile-arcs...  -fprofile-arcs
checking whether cc accepts -fbranch-probabilities...  -fbranch-probabilities
checking whether cc accepts -O1...  -O1
checking whether cc accepts -O2...  -O2
checking whether cc accepts -fno-math-errno...  -fno-math-errno
checking whether cc accepts -fno-strict-aliasing...  -fno-strict-aliasing
checking whether cc accepts -fwrapv...  -fwrapv
checking whether cc accepts -fomit-frame-pointer...  -fomit-frame-pointer
checking whether cc accepts -fPIC...  -fPIC
checking whether cc accepts -fpic...  -fpic
checking whether cc accepts -fno-common...  -fno-common
checking whether cc accepts -rdynamic...  -rdynamic
checking whether cc accepts -shared...  -shared
checking for X... (cached) libraries /usr/X11R6/lib, headers /usr/X11R6/include
checking whether -R must be followed by a space... no
checking for gethostbyname... (cached) yes
checking for connect... (cached) yes
checking for remove... (cached) yes
checking for shmat... (cached) yes
checking for IceConnectionNumber in -lICE... (cached) yes
checking whether ln -s works... yes
checking for ranlib... (cached) ranlib
checking for ar... (cached) ar
./configure[13622]: /: cannot execute - Is a directory
./configure[13622]: /: cannot execute - Is a directory
./configure[13622]: g": not found
sed: 1: ""s": invalid command code "
./configure[13650]: /: cannot execute - Is a directory
./configure[13650]: /: cannot execute - Is a directory
./configure[13650]: g": not found
sed: 1: ""s": invalid command code "
./configure[13650]: /: cannot execute - Is a directory
./configure[13650]: /: cannot execute - Is a directory
./configure[13650]: g": not found
sed: 1: ""s": invalid command code "
./configure[13650]: /: cannot execute - Is a directory
./configure[13650]: /: cannot execute - Is a directory
./configure[13650]: g": not found
sed: 1: ""s": invalid command code "
./configure[13650]: /: cannot execute - Is a directory
./configure[13650]: /: cannot execute - Is a directory
./configure[13650]: g": not found
sed: 1: ""s": invalid command code "
checking whether make sets $(MAKE)... (cached) yes
configure: creating ./config.status
config.status: creating makefile
config.status: creating include/makefile
config.status: creating include/gambit.h
config.status: creating lib/makefile
config.status: creating gsi/makefile
config.status: creating gsc/makefile
config.status: creating bin/makefile
config.status: creating bin/gambcomp-C.unix
config.status: creating bin/gambcomp-C.bat.windows
config.status: creating bin/gambdoc.unix
config.status: creating bin/gambdoc.bat.windows
config.status: creating misc/makefile
config.status: creating doc/makefile
config.status: creating tests/makefile
config.status: creating examples/makefile
config.status: creating examples/distr-comp/makefile
config.status: creating examples/pi/makefile
config.status: creating examples/ring/makefile
config.status: creating examples/web-repl/makefile
config.status: creating examples/web-server/makefile
config.status: creating examples/tcltk/makefile
config.status: creating examples/Xlib-simple/makefile
config.status: creating examples/pthread/makefile
config.status: creating examples/misc/makefile
config.status: creating contrib/makefile
config.status: creating contrib/GambitREPL/makefile
config.status: creating prebuilt/makefile
config.status: creating prebuilt/macosx/makefile
config.status: creating prebuilt/macosx/build-phase2
config.status: creating prebuilt/windows/makefile
config.status: creating prebuilt/windows/build-phase2
config.status: creating include/config.h
configure: WARNING: unrecognized options: --disable-silent-rules, --disable-gtk-doc
configure:
**************************************************************************
***                                                                    ***
*** The option "--enable-single-host" was not specified to the         ***
*** configure script.  The Gambit system will compile correctly but    ***
*** typically the executables will run considerably slower than when   ***
*** "--enable-single-host" is specified.  On the other hand the build  ***
*** with "--enable-single-host" is typically slower and requires lots  ***
*** of RAM memory (>= 1 GB).  If you are willing to wait for the       ***
*** longer build, try the configure option "--enable-single-host".     ***
***                                                                    ***
**************************************************************************

```

Configure options: `./configure --enable-shared --disable-cplusplus --disable-absolute-shared-libs --docdir=/usr/local/share/doc/gambit/ --includedir=/usr/local/include/gambit/ --libdir=/usr/local/lib/gambit/ --enable-c-opt=-O2 -pipe   --prefix=/usr/local --sysconfdir=/etc --mandir=/usr/local/man --infodir=/usr/local/info --localstatedir=/var --disable-silent-rules --disable-gtk-doc`

I've attached the [config.log](https://github.com/feeley/gambit/files/98450/config.txt).

Probably the problem is that the regex is compatible with GNU `sed` but incompatible with OpenBSD `sed`.

This is the workaround which I've been using until 4.7.9 (I've not updated to newer versions):

```diff
@@ -13592,32 +13592,32 @@ if test "$datadir" = "\${datarootdir}"; then
   datadir="\${prefix}/share"
 fi

-GAMBCLIB_DEFS="$GAMBCLIB_DEFS -D___GAMBCDIR=\"\\\"`echo \"$prefix\" | sed -e \"s|/|$PATH_SEP|g\"`\\\"\""
+GAMBCLIB_DEFS="$GAMBCLIB_DEFS -D___GAMBCDIR=\"\\\"$prefix\\\"\""

 if test "$ENABLE_SYMLINKS" != yes; then

   if test "$bindir" != "\${prefix}/bin"; then
-    GAMBCLIB_DEFS="$GAMBCLIB_DEFS -D___GAMBCDIR_BIN=\"\\\"`echo \"$bindir\" | sed -e \"s|/|$PATH_SEP|g\"`\\\"\""
+    GAMBCLIB_DEFS="$GAMBCLIB_DEFS -D___GAMBCDIR_BIN=\"\\\"$bindir\\\"\""
   fi

   if test "$includedir" != "\${prefix}/include"; then
-    GAMBCLIB_DEFS="$GAMBCLIB_DEFS -D___GAMBCDIR_INCLUDE=\"\\\"`echo \"$includedir\" | sed -e \"s|/|$PATH_SEP|g\"`\\\"\""
+    GAMBCLIB_DEFS="$GAMBCLIB_DEFS -D___GAMBCDIR_INCLUDE=\"\\\"$includedir\\\"\""
   fi

   if test "$libdir" != "\${prefix}/lib"; then
-    GAMBCLIB_DEFS="$GAMBCLIB_DEFS -D___GAMBCDIR_LIB=\"\\\"`echo \"$libdir\" | sed -e \"s|/|$PATH_SEP|g\"`\\\"\""
+    GAMBCLIB_DEFS="$GAMBCLIB_DEFS -D___GAMBCDIR_LIB=\"\\\"$libdir\\\"\""
   fi

   if test "$docdir" != "\${prefix}/doc"; then
-    GAMBCLIB_DEFS="$GAMBCLIB_DEFS -D___GAMBCDIR_DOC=\"\\\"`echo \"$docdir\" | sed -e \"s|/|$PATH_SEP|g\"`\\\"\""
+    GAMBCLIB_DEFS="$GAMBCLIB_DEFS -D___GAMBCDIR_DOC=\"\\\"$docdir\\\"\""
   fi

   if test "$infodir" != "\${prefix}/info"; then
-    GAMBCLIB_DEFS="$GAMBCLIB_DEFS -D___GAMBCDIR_INFO=\"\\\"`echo \"$infodir\" | sed -e \"s|/|$PATH_SEP|g\"`\\\"\""
+    GAMBCLIB_DEFS="$GAMBCLIB_DEFS -D___GAMBCDIR_INFO=\"\\\"$infodir\\\"\""
   fi

   if test "$datadir" != "\${prefix}/share"; then
-    GAMBCLIB_DEFS="$GAMBCLIB_DEFS -D___GAMBCDIR_SHARE=\"\\\"`echo \"$datadir\" | sed -e \"s|/|$PATH_SEP|g\"`\\\"\""
+    GAMBCLIB_DEFS="$GAMBCLIB_DEFS -D___GAMBCDIR_SHARE=\"\\\"$datadir\\\"\""
   fi
```

**Comment by adam-7** [comment]
@juanfra684 @feeley  ah you are right, there is indeed some little SED problem. I think it was introduced less than 18 months ago.

Find console output of my attempt below, it looks less severe here but still. The error I see is the crashed sed call right above the list of "config.status: creating [...]" lines on the bottom.

5.8 AMD64: bash -c "git clone https://github.com/feeley/gambit; cd gambit; CXX=eg++ ./configure --enable-single-host --enable-cplusplus" gives:


checking build system type... x86_64-unknown-openbsd5.8
checking host system type... x86_64-unknown-openbsd5.8
checking target system type... x86_64-unknown-openbsd5.8
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking how to run the C preprocessor... gcc -E
checking whether we are using the GNU C++ compiler... yes
checking whether eg++ accepts -g... yes
checking how to run the C++ preprocessor... eg++ -E
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking size of void*... 8
checking size of long... 8
checking for bool... yes
checking whether eg++ defines __GNUC__... yes
checking whether eg++ defines __clang__...
checking whether eg++ defines __llvm__...
checking whether eg++ defines _MSC_VER...
checking whether eg++ defines _WIN32...
checking errno.h usability... yes
checking errno.h presence... yes
checking for errno.h... yes
checking float.h usability... yes
checking float.h presence... yes
checking for float.h... yes
checking signal.h usability... yes
checking signal.h presence... yes
checking for signal.h... yes
checking stdio.h usability... yes
checking stdio.h presence... yes
checking for stdio.h... yes
checking for stdlib.h... (cached) yes
checking for string.h... (cached) yes
checking time.h usability... yes
checking time.h presence... yes
checking for time.h... yes
checking for unistd.h... (cached) yes
checking pwd.h usability... yes
checking pwd.h presence... yes
checking for pwd.h... yes
checking dlfcn.h usability... yes
checking dlfcn.h presence... yes
checking for dlfcn.h... yes
checking dl.h usability... no
checking dl.h presence... no
checking for dl.h... no
checking sys/dxe.h usability... no
checking sys/dxe.h presence... no
checking for sys/dxe.h... no
checking mach-o/dyld.h usability... no
checking mach-o/dyld.h presence... no
checking for mach-o/dyld.h... no
checking for sys/types.h... (cached) yes
checking sys/time.h usability... yes
checking sys/time.h presence... yes
checking for sys/time.h... yes
checking sys/times.h usability... yes
checking sys/times.h presence... yes
checking for sys/times.h... yes
checking sys/timeb.h usability... no
checking sys/timeb.h presence... no
checking for sys/timeb.h... no
checking sys/timers.h usability... no
checking sys/timers.h presence... no
checking for sys/timers.h... no
checking sys/resource.h usability... yes
checking sys/resource.h presence... yes
checking for sys/resource.h... yes
checking sys/wait.h usability... yes
checking sys/wait.h presence... yes
checking for sys/wait.h... yes
checking sys/mman.h usability... yes
checking sys/mman.h presence... yes
checking for sys/mman.h... yes
checking syslog.h usability... yes
checking syslog.h presence... yes
checking for syslog.h... yes
checking netdb.h usability... yes
checking netdb.h presence... yes
checking for netdb.h... yes
checking grp.h usability... yes
checking grp.h presence... yes
checking for grp.h... yes
checking fpu_control.h usability... no
checking fpu_control.h presence... no
checking for fpu_control.h... no
checking os2.h usability... no
checking os2.h presence... no
checking for os2.h... no
checking dos.h usability... no
checking dos.h presence... no
checking for dos.h... no
checking direct.h usability... no
checking direct.h presence... no
checking for direct.h... no
checking wdefwin.h usability... no
checking wdefwin.h presence... no
checking for wdefwin.h... no
checking tfork.h usability... no
checking tfork.h presence... no
checking for tfork.h... no
checking curses.h usability... yes
checking curses.h presence... yes
checking for curses.h... yes
checking ncurses.h usability... yes
checking ncurses.h presence... yes
checking for ncurses.h... yes
checking netinet/in.h usability... yes
checking netinet/in.h presence... yes
checking for netinet/in.h... yes
checking arpa/inet.h usability... yes
checking arpa/inet.h presence... yes
checking for arpa/inet.h... yes
checking termios.h usability... yes
checking termios.h presence... yes
checking for termios.h... yes
checking pty.h usability... no
checking pty.h presence... no
checking for pty.h... no
checking stropts.h usability... no
checking stropts.h presence... no
checking for stropts.h... no
checking libutil.h usability... no
checking libutil.h presence... no
checking for libutil.h... no
checking util.h usability... yes
checking util.h presence... yes
checking for util.h... yes
checking sys/fpu.h usability... no
checking sys/fpu.h presence... no
checking for sys/fpu.h... no
checking fenv.h usability... yes
checking fenv.h presence... yes
checking for fenv.h... yes
checking fcntl.h usability... yes
checking fcntl.h presence... yes
checking for fcntl.h... yes
checking sys/ioctl.h usability... yes
checking sys/ioctl.h presence... yes
checking for sys/ioctl.h... yes
checking sys/socket.h usability... yes
checking sys/socket.h presence... yes
checking for sys/socket.h... yes
checking for strings.h... (cached) yes
checking for memory.h... (cached) yes
checking sys/sysctl.h usability... yes
checking sys/sysctl.h presence... yes
checking for sys/sysctl.h... yes
checking ws2tcpip.h usability... no
checking ws2tcpip.h presence... no
checking for ws2tcpip.h... no
checking TargetConditionals.h usability... no
checking TargetConditionals.h presence... no
checking for TargetConditionals.h... no
checking poll.h usability... yes
checking poll.h presence... yes
checking for poll.h... yes
checking for environ... yes
checking for _NSGetEnviron... checking crt_externs.h usability... no
checking crt_externs.h presence... no
checking for crt_externs.h... no
no
checking for remove... yes
checking for rename... yes
checking for sys/stat.h... (cached) yes
checking for mkdir... yes
checking dirent.h usability... yes
checking dirent.h presence... yes
checking for dirent.h... yes
checking for opendir... yes
checking stat.h usability... no
checking stat.h presence... no
checking for stat.h... no
checking for sys/stat.h... (cached) yes
checking for stat... yes
checking for stat64... no
checking for struct stat64... no
checking for socklen_t... yes
checking for library containing asin... none required
checking for library containing dlopen... none required
checking for library containing shl_load... no
checking for library containing socket... none required
checking for library containing gethostbyname... none required
checking for library containing hstrerror... none required
checking for library containing openpty... -lutil
checking for library containing WSAStartup... no
checking for library containing timeBeginPeriod... no
checking for pipe... yes
checking for socketpair... yes
checking for chdir... yes
checking for execvp... yes
checking for getgrnam... yes
checking for getpid... yes
checking for getppid... yes
checking for getpwnam... yes
checking for ioctl... yes
checking for link... yes
checking for mkfifo... yes
checking for rmdir... yes
checking for socket... yes
checking for utimes... yes
checking for strerror... yes
checking for symlink... yes
checking for sysconf... yes
checking for sysctl... yes
checking for syslog... yes
checking for unlink... yes
checking for waitpid... yes
checking for mmap... yes
checking for fcntl... yes
checking for tcgetsetattr... yes
checking for sigaction... yes
checking for sigemptyset/sigaddset... yes
checking for sigprocmask... yes
checking for signal... yes
checking for clock_gettime... yes
checking for getclock... no
checking for gettimeofday... yes
checking for ftime... no
checking for time... yes
checking for nanosleep... yes
checking for sleep... yes
checking for getrusage... yes
checking for times... yes
checking for clock... yes
checking for DosQuerySysInfo... no
checking for setitimer... yes
checking for dos_setvect... no
checking for DosStartTimer... no
checking for VInstall... no
checking for shl_load... no
checking for DosLoadModule... no
checking for dxe_load... no
checking for GetDiskFragment... no
checking for dlopen... yes
checking for NSLinkModule... no
checking for gethostname... yes
checking for inet_pton... yes
checking for getaddrinfo... yes
checking for gethostbyname... yes
checking for gethostbyaddr... yes
checking for getservbyname... yes
checking for getservbyport... yes
checking for getprotobyname... yes
checking for getprotobynumber... yes
checking for getnetbyname... yes
checking for select... yes
checking for poll... yes
checking for ppoll... yes
checking for openpty... yes
checking for getpt... no
checking for ptsname... yes
checking for ctermid... yes
checking for isastream... no
checking for hstrerror... yes
checking for get_fpc_csr... no
checking how eg++'s preprocessor evaluates (__GNUC__*1000+__GNUC_MINOR__)>=4002&&(__GNUC__*1000+__GNUC_MINOR__)<=4003...
checking how eg++'s preprocessor evaluates __llvm__ && !__clang__ && (__GNUC__*1000+__GNUC_MINOR__)<4005...
checking whether eg++ accepts -no-cpp-precomp...
checking whether eg++ accepts -fschedule-insns2...  -fschedule-insns2
checking whether eg++ accepts -fno-trapping-math...  -fno-trapping-math
checking whether eg++ accepts -fno-move-loop-invariants...  -fno-move-loop-invariants
checking whether eg++ accepts -fno-keep-inline-dllexport...
checking whether eg++ accepts -mieee...
checking whether eg++ accepts -mieee-with-inexact...
checking whether eg++ accepts -mieee-fp...  -mieee-fp
checking whether eg++ accepts -Wall...  -Wall
checking whether eg++ accepts -W...  -W
checking whether eg++ accepts -Wno-unused...  -Wno-unused
checking whether eg++ accepts -Wno-write-strings...  -Wno-write-strings
checking whether eg++ accepts -g...  -g
checking whether eg++ accepts -p...  -p
checking whether eg++ accepts -pg...  -pg
checking whether eg++ accepts -ftest-coverage...  -ftest-coverage
checking whether eg++ accepts -fprofile-arcs...  -fprofile-arcs
checking whether eg++ accepts -fbranch-probabilities...  -fbranch-probabilities
checking whether eg++ accepts -O1...  -O1
checking whether eg++ accepts -O2...  -O2
checking whether eg++ accepts -fno-math-errno...  -fno-math-errno
checking whether eg++ accepts -fno-strict-aliasing...  -fno-strict-aliasing
checking whether eg++ accepts -fwrapv...  -fwrapv
checking whether eg++ accepts -fomit-frame-pointer...  -fomit-frame-pointer
checking whether eg++ accepts -fPIC...  -fPIC
checking whether eg++ accepts -fpic...  -fpic
checking whether eg++ accepts -fno-common...  -fno-common
checking whether eg++ accepts -rdynamic...  -rdynamic
checking whether eg++ accepts -shared...  -shared
checking for X... libraries /usr/X11R6/lib, headers /usr/X11R6/include
checking whether -R must be followed by a space... no
checking for gethostbyname... (cached) yes
checking for connect... yes
checking for remove... (cached) yes
checking for shmat... yes
checking for IceConnectionNumber in -lICE... yes
checking whether ln -s works... yes
checking for ranlib... ranlib
checking for ar... ar
./configure[13622]: /: cannot execute - Is a directory
./configure[13622]: /: cannot execute - Is a directory
./configure[13622]: g": not found
sed: 1: ""s": invalid command code "
checking whether make sets $(MAKE)... yes
configure: creating ./config.status
config.status: creating makefile
config.status: creating include/makefile
config.status: creating include/gambit.h
config.status: creating lib/makefile
config.status: creating gsi/makefile
config.status: creating gsc/makefile
config.status: creating bin/makefile
config.status: creating bin/gambcomp-C.unix
config.status: creating bin/gambcomp-C.bat.windows
config.status: creating bin/gambdoc.unix
config.status: creating bin/gambdoc.bat.windows
config.status: creating misc/makefile
config.status: creating doc/makefile
config.status: creating tests/makefile
config.status: creating examples/makefile
config.status: creating examples/distr-comp/makefile
config.status: creating examples/pi/makefile
config.status: creating examples/ring/makefile
config.status: creating examples/web-repl/makefile
config.status: creating examples/web-server/makefile
config.status: creating examples/tcltk/makefile
config.status: creating examples/Xlib-simple/makefile
config.status: creating examples/pthread/makefile
config.status: creating examples/misc/makefile
config.status: creating contrib/makefile
config.status: creating contrib/GambitREPL/makefile
config.status: creating prebuilt/makefile
config.status: creating prebuilt/macosx/makefile
config.status: creating prebuilt/macosx/build-phase2
config.status: creating prebuilt/windows/makefile
config.status: creating prebuilt/windows/build-phase2
config.status: creating include/config.h

**Comment by adam-7** [comment]
@juanfra684 can you confirm if the bug still exists?

I guess it's about time to close this issue.

**Comment by juanfra684** [comment]
You're right. I don't see the weird output in configure.
