### ISSUE TITLE
Error when decoding UTF-8.

### ISSUE THREAD

**Issue by gravicappa** [gambit/gambit#189]
Hello. Got an error

    Can't convert from C UTF-8-string (read-char '#<input-port #2 (u8vector)>)

when trying to convert UTF-8 encoded text from u8vector to string via this
function:

    (define (string<-utf8 x)
      (call-with-output-string ""
        (lambda (out)
          (call-with-input-u8vector (list char-encoding: 'UTF-8 init: x)
            (lambda (in)
              (let loop ()
                (let ((c (read-char in)))
                  (cond ((not (eof-object? c))
                         (write-char c out)
                         (loop))))))))))

The text itself should be correct:

    (define v (u8vector 49 58 100 44 50 58 49 49 44 56 58 50 48 48 48 48 48 50
                        48 44 50 58 49 48 44 49 48 58 49 52 53 54 55 53 56 57
                        54 52 44 52 49 58 208 161 209 130 208 181 208 187 208
                        187 208 176 208 182 32 208 188 208 181 209 130 208 176
                        208 187 208 187 208 184 209 135 208 181 209 129 208
                        186 208 184 208 185 44 55 58 49 49 49 53 98 98 55 44
                        55 58 49 49 51 98 48 53 98 44 50 58 56 48 44 49 58 50
                        44 49 58 49 44))

    (string<-utf8 v) ;; ERROR
    (string<-utf8 (subu8vector v 1 (u8vector-length v))) ;; OK
    (string<-utf8 (subu8vector v 2 (u8vector-length v))) ;; ERROR

**Comment by feeley** [comment]
Thanks for the bug report.  I have reproduced the problem and will investigate.

**Comment by feeley** [comment]
Fixed by commit fc75d7363281a72a9b864f0d3d17889136a4b743
