### ISSUE TITLE
Documentation 'bug' in 17.6.1 Byte-port settings

### ISSUE THREAD

**Issue by DavidCase** [gambit/gambit#197]
The documentation for section 17.6.1 (Byte-port settings) does not mention that the encodings are not bound and so must be quoted. I just tested  [ char-encoding: ], [ eol-encoding: ] and [path: ] and they are bound globally  but the options like [ ASCII ], [ UTF-8 ], and [ cr ] are not bound and so must be quoted.
All of the examples given in the documentation cover the cases where the options are already "Scheme ready" (#t, #f, an integer, a string, etc.) so the overall impression given is not very clear.

BTW, I love Gambit and I finally got it to run in Emacs! I have been running it for years and years now under emulation in  SheepShaver (back when it had it's own IDE) and it is a real treat to have it back in OS X.

**Comment by feeley** [comment]
Section 17.3 (Port settings) gives explains this and includes the following example:

```(open-input-file (list path: "foo" char-encoding: 'UTF-8))```
