### ISSUE TITLE
Missing warnings for undeclared variables in 4.8.5

### ISSUE THREAD

**Issue by mgorges** [gambit/gambit#203]
Sorry, if I missed something obvious but it seems that the current version of gambit is less helpful when it comes to warnings during compilation. I don't have both versions available on the same machine so one example with linux and one with macos

Old behaviour (4.7.9):

    mgorges@ECEM01:~$ cat missing-warning.sh 
    #/bin/bash
    echo "(define a b)" > a.scm
    ~/.cache/lambdanative/linux/bin/gsc -prelude "(declare (block)(not safe)(standard-bindings)(extended-bindings))" -c -o a.c a.scm
    gcc  -DLINUX   -D___SINGLE_HOST -D___LIBRARY -D___PRIMAL -DSTANDALONE -c -o a.o a.c -I/home/mgorges/.cache/lambdanative/linux/include
    ~/.cache/lambdanative/linux/bin/gsc -link a.c
    
    mgorges@ECEM01:~$ ./missing-warning.sh 
    *** WARNING -- "b" is not defined,
    ***            referenced in: ("a.c")
    mgorges@ECEM01:~$

New behaviour (4.8.5):

    mg@kanonia2 ~/Downloads/aa $cat missing-warning.sh 
    #/bin/bash
    echo "(define a b)" > a.scm
    ~/Documents/Programming/lambdanative-cache/macosx/bin/gsc -prelude "(declare (block)(not safe)(standard-bindings)(extended-bindings))" -c -o a.c a.scm
    gcc  -DLINUX   -D___SINGLE_HOST -D___LIBRARY -D___PRIMAL -DSTANDALONE -c -o a.o a.c -I/Users/mg/Documents/Programming/lambdanative-cache/macosx/include
    ~/Documents/Programming/lambdanative-cache/macosx/bin/gsc -link a.c
    mg@kanonia2 ~/Downloads/aa $./missing-warning.sh
    mg@kanonia2 ~/Downloads/aa $

**Comment by gambiteer** [comment]
I don't know the answer to your question.

But I will note that Gambit relies on passing gcc some options with non-default values for correctness of the assembly code that gcc produces from the C code that gsc generates, and I encourage people to employ the scripts used implicitly by gsc called with various options (-exe, etc.) to compile C code generated by Gambit.

**Comment by feeley** [comment]
The behaviour changed a while back so that gsc is silent by default and you need the -warnings option to get the warnings.

**Comment by mgorges** [comment]
@feeley okay thanks.
