### ISSUE TITLE
Add separate files from misc/bench.tgz to git repo

### ISSUE THREAD

**Issue by gambiteer** [gambit/gambit#208]
Marc:

I want to add a new test chudnovsky.scm to bench.tgz, and I have to modify four *-iter files, two gambit prefix files, and add the new source file itself.

I'd also like to modify pi.scm to recognize the existence of exact-integer-sqrt, available in R[67]RS and easily provided in gambit with a few lines in the prefix file.

This is a pain when everything is just tied up in a binary tarball.  I don't think it would be too much trouble now to have a separate gambit/bench directory with the individual files.

**Comment by feeley** [comment]
Fixed by commit 0a3cf3d18430bfe8a06cfde8063e74790dbab735
