### ISSUE TITLE
--enable-debug leads to signed multiplication overflow abort on arm

### ISSUE THREAD

**Issue by gambiteer** [gambit/gambit#211]
I decided to configure and build Gambit on arm (Raspberry Pi 3) with

cutie-pi:~/programs/gambit/tests> ../gsi/gsi -v
v4.8.5 20160913182345 armv7l-unknown-linux-gnueabihf "./configure '--enable-debug' '--enable-debug-garbage-collect'"

"make check" fails in a number of places, but I don't get a good backtrace, e.g.,

cutie-pi:~/programs/gambit/tests> gdb ../gsc/gsc
GNU gdb (Raspbian 7.7.1+dfsg-5) 7.7.1
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "arm-linux-gnueabihf".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ../gsc/gsc...done.
(gdb) run -:~~bin=../bin,~~lib=../lib,~~include=../include -f -warnings -o mem -exe mem.scm
Starting program: /home/pi/programs/gambit/gsc/gsc -:~~bin=../bin,~~lib=../lib,~~include=../include -f -warnings -o mem -exe mem.scm

Program received signal SIGABRT, Aborted.
0x76dfdf70 in __GI_raise (sig=sig@entry=6)
    at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
56      ../nptl/sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) where
#0  0x76dfdf70 in __GI_raise (sig=sig@entry=6)
    at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#1  0x76dff324 in __GI_abort () at abort.c:89
#2  0x00a65538 in __mulvsi3 ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
(gdb) bt
#0  0x76dfdf70 in __GI_raise (sig=sig@entry=6)
    at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#1  0x76dff324 in __GI_abort () at abort.c:89
#2  0x00a65538 in __mulvsi3 ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
(gdb) 

Any suggestions?

**Comment by feeley** [comment]
Add ```--enable-debug-host-changes``` and after it crashes look at the end of gambit.log to see what was the last function called.

**Comment by gambiteer** [comment]
And ... 11 hours later gambit.log is 1GB in size on a 8GB file system, test3 has been running for 5 hours of CPU time.

I'll wait a few hours more but perhaps we need another strategy.

**Comment by feeley** [comment]
No need to do a "make check"! Just run gsc/gsc as was done originally

**Comment by gambiteer** [comment]
Found it.  On Ubuntu 16.04 with

heine:~/programs/gambit/gambit/tests> ../gsi/gsi -v
v4.8.5 20160913182345 x86_64-unknown-linux-gnu "./configure 'CC=/usr/local/gcc-6.2.0/bin/gcc -m32' '--enable-debug' '--enable-debug-garbage-collection'"

you get

heine:~/programs/gambit/gambit/tests> gdb ../gsi/gsi
GNU gdb (Ubuntu 7.11.1-0ubuntu1~16.04) 7.11.1
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ../gsi/gsi...done.
(gdb) run  -:s,~~bin=../bin,~~lib=../lib,~~include=../include -f -e '(begin (load "r4rstest.scm") (test-cont) (test-sc4) (test-delay) (exit))' >! test3.out
Starting program: /home/lucier/programs/gambit/gambit/gsi/gsi -:s,~~bin=../bin,~~lib=../lib,~~include=../include -f -e '(begin (load "r4rstest.scm") (test-cont) (test-sc4) (test-delay) (exit))' >! test3.out

Program received signal SIGABRT, Aborted.
0xf7fd8be9 in __kernel_vsyscall ()
(gdb) bt
#0  0xf7fd8be9 in __kernel_vsyscall ()
#1  0xf7dc3e89 in raise () from /lib/i386-linux-gnu/libc.so.6
#2  0xf7dc53e7 in abort () from /lib/i386-linux-gnu/libc.so.6
#3  0x0844837c in __mulvsi3 (a=1335505868, b=331804471) at ../../../../gcc-6.2.0/libgcc/libgcc2.c:157
#4  0x081349b2 in ___H__23__23_equal_3f__2d_hash (___ps=0x85b9ca0 <___gstate0>) at _system.c:5260
#5  0x080d1c26 in trampoline (___ps=0x85b9ca0 <___gstate0>) at setup.c:2592
#6  0x080d1e60 in ___call (nargs=0, proc=139557233, stack_marker=140256357) at setup.c:2708
#7  0x080d1f62 in ___run (thunk=139557233) at setup.c:2742
#8  0x080d3888 in ___setup (setup_params=0xffffd0a0) at setup.c:4221
#9  0x080f6b95 in ___main (linker=0x80cf9b3 <____20___gsi__>) at main.c:723
#10 0x080e3e16 in ___main_char (argc=5, argv=0xffffd284, linker=0x80cf9b3 <____20___gsi__>, script_line=0x0) at os_base.c:413
#11 0x080cf9f8 in main (argc=5, argv=0xffffd284) at _gsi_.c:9267

which is this code:

___DEF_SLBL(5,___L5__23__23_equal_3f__2d_hash)
   ___SET_R1(___FIXASHL(___R1,___FIX(1L)))
   ___SET_R1(___FIXADD(___STK(-5),___R1))
   ___SET_R1(___FIXMUL(___R1,___FIX(331804471L)))
   ___SET_R1(___FIXAND(___R1,___FIX(536870911L)))
   ___POLL(6)

which is

  (define (combine a b)
    (##fxand
     (##fx* (##fx+ a (##fxarithmetic-shift-left b 1))
            331804471)
     (macro-max-fixnum32)))

which you probably already suspected ...

**Comment by gambiteer** [comment]
I'm working on a fix.

**Comment by gambiteer** [comment]
Fixed with 9c5e9dabdf3f3d766dfd2c0e98d459e2e40a1207
