### ISSUE TITLE
Gambit REPL freeze during multibyte character output

### ISSUE THREAD

**Issue by nortiero** [gambit/gambit#220]
Steps to reproduce (tested with 4.8.7 on OS X and Linux):

gsi -:t8
enter this: ††††††††††††††††††††††††††††††††††††††††††††††††††††††††
press enter, then cursor up
freeze

The issue is due to a loop in os_tty.c:lineeditor_output_drain; if a wide character needs more output_byte buffer space than currently available, the inner conversion loop will spin forever.

A hopefully correct one liner fix is in #219.
Tested OK with UTF8 output

**Comment by feeley** [comment]
Thanks for the pull request! Fixed by commit 23c658611f6b536507234b24c53d74c6fed2f9d5.
