### ISSUE TITLE
Strange behavior observed with (block) and a closure

### ISSUE THREAD

**Issue by nortiero** [gambit/gambit#229]
Sample code:

```
(declare
 (block))


(define (whatever) (println "whatever"))
;(define (whatever) #f)

(define (iclose p1)
  (define (foo) (whatever) (println "foo: " p1))
  foo)

(let loop ((v 0))
  (let ((tmp (iclose #xdeadbeef)))
    (println "tmp: " tmp)
    (if (< v 20) (loop (+ v 1)))))

```

Output (gambit version 6c56013, ` gsc -exe sample.scm`)
```
tmp: #<procedure #2>
tmp: #<procedure #3>
tmp: #<procedure #4>
tmp: #<procedure #3>
tmp: #<procedure #5>
tmp: #<procedure #3>
tmp: #<procedure #6>
tmp: #<procedure #3>
tmp: #<procedure #7>
tmp: #<procedure #3>
tmp: #<procedure #8>
tmp: #<procedure #3>
tmp: #<procedure #9>
tmp: #<procedure #3>
tmp: #<procedure #10>
tmp: #<procedure #3>
tmp: #<procedure #11>
tmp: #<procedure #3>
tmp: #<procedure #12>
tmp: #<procedure #3>
tmp: #<procedure #13>
```

This only happens if:
- (block) optimization is enabled;
- (iclose p) can be memoized, e.g. p is a constant;
- something a little more complicated happens inside _foo_ (like "_whatever_" invocation)

If any of these conditions are not met, gambit will always emit a new closure, or recycle the previous one, which is perfectly fine for me 👍 

But why only one in two ?

Please close if this issue is of no relevance, or something absolutely obvious that I ignore...

**Comment by feeley** [comment]
Amusing! Not a bug... it is a consequence of the inlining algorithm which does two things with this code. First it unrolls the loop so there are two iterations per cycle around the loop (thus two calls to iclose) and second, it inlines the body of iclose in one of the two calls to iclose, making that lambda constant, i.e. no free variables).  Just add the -expansion option to gsc to see the code after expansion. Try adding the declaration ``` (inlining-limit 500)``` to see how the inliner behaves (in this case iclose is inlined 3 times and all closures are the same).

**Comment by feeley** [comment]
BTW check the ```([not] generative-lambda)``` compiler declaration that can be used to force the generation of distinct closures.
