### ISSUE TITLE
Build error under Arch Linux 64 Bit

### ISSUE THREAD

**Issue by stefanhusmann** [gambit/gambit#231]
I get a build error with the latest commit. See http://dpaste.com/2BMM3B6 for a build log. Commit 4.8.8.r72.gd13c173 could be compiled successfully.

**Comment by feeley** [comment]
From the log it seems you are using "make latest-release" which is deprecated.  The correct way to build Gambit from a github clone is:

```
    git clone https://github.com/gambit/gambit.git
    cd gambit
    ./configure
    make -j4 current-gsc-boot
    ./configure --enable-single-host
    make -j4 from-scratch
    make check
    make -j4 doc
    sudo make install
```

**Comment by stefanhusmann** [comment]
Thanks, that was the problem.
