### ISSUE TITLE
SEGFAULT with FFI pointer derefence

### ISSUE THREAD

**Issue by vyzo** [gambit/gambit#247]
With Gambit-v4.8.5, the following ffi pointer dereference segfaults:
libfoo.scm:
```scheme
(declare
  (block)
  (standard-bindings)
  (extended-bindings)
  (not safe))

(##namespace (""))

(c-declare #<<END-C
#include <stdlib.h>

typedef unsigned int MDB_dbi;
static ___SCMOBJ ffi_free (void *ptr);

END-C
)

(c-define-type MDB_dbi "MDB_dbi")
(c-define-type MDB_dbi*
  (pointer MDB_dbi (MDB_dbi*) "ffi_free"))

(define-macro (define-c-lambda id args ret #!optional (name #f))
  (let ((name (or name (##symbol->string id))))
    `(define ,id
       (c-lambda ,args ,ret ,name))))

(define-c-lambda ffi_make_mdb_dbi_ptr () MDB_dbi*
  "___result = (MDB_dbi*)malloc (sizeof (MDB_dbi));")
(define-c-lambda ffi_mdb_dbi_ptr_value (MDB_dbi*) MDB_dbi
  "___result = *___arg1;")

(c-declare #<<END-C
___SCMOBJ ffi_free (void *ptr)
{
 free (ptr);
 return ___FIX (___NO_ERR);
}
END-C
)
```

The following crashes:
```
$ gsc libfoo.scm
$ gsi
Gambit v4.8.5

> (load "libfoo")
"/home/vyzo/src/bugs/gambit/libfoo.o1"
> (define ptr (ffi_make_mdb_dbi_ptr))
> (ffi_mdb_dbi_ptr_value ptr)
Segmentation fault
```

**Comment by feeley** [comment]
The idiom "___result = ...;" is no longer valid (and in the case of ffi_make_mdb_dbi_ptr it should have been "___result_voidstar = ...;").  Now, you should use "___return(...);" as indicated in the manual (check the commit 33a475dd17e0560881264761516ace42fbf7b170).  Also, (c-define-type MDB_dbi "MDB_dbi") should be (c-define-type MDB_dbi unsigned-int).

**Comment by vyzo** [comment]
Thanks Marc.
Note that defining dbi as a named type is not quite an option, as the type is named by the library I am writing the bindings for (here it was just a verbatim typedef for the testcase)

**Comment by vyzo** [comment]
Btw, is `___result` and `___result_voidstar` simply deprecated or just plain broken and need to be converted to `___return`? 
I have quite a bit of ffi code with `___result*` (it uses `___result_voidstar` as appropriate though, as opposed to the bug in my test case above)
