### ISSUE TITLE
Configuring with clang doesn't find -fno-trapping-math?

### ISSUE THREAD

**Issue by gambiteer** [gambit/gambit#248]
When configured with
```
./configure 'CC=/pkgs/llvm-4.0.0/bin/clang -march=native -D___CAN_IMPORT_CLIB_DYNAMICALLY' '--enable-single-host' '--enable-multiple-versions'
```
The typical compile command is
```
/pkgs/llvm-4.0.0/bin/clang -march=native -D___CAN_IMPORT_CLIB_DYNAMICALLY -Wno-unused -Wno-write-strings -Wdisabled-optimization -O1 -fwrapv -fno-strict-aliasing -fno-math-errno -fomit-frame-pointer -fPIC -fno-common   -I"../include" -c -o "os_time.o" -I. -DHAVE_CONFIG_H -D___GAMBITDIR="\"/usr/local/Gambit/v4.8.8\"" -D___SYS_TYPE_CPU="\"x86_64\"" -D___SYS_TYPE_VENDOR="\"unknown\"" -D___SYS_TYPE_OS="\"linux-gnu\"" -D___CONFIGURE_COMMAND="\"./configure 'CC=/pkgs/llvm-4.0.0/bin/clang -march=native -D___CAN_IMPORT_CLIB_DYNAMICALLY' '--enable-single-host' '--enable-multiple-versions'"\" -D___OBJ_EXTENSION="\".o\"" -D___EXE_EXTENSION="\"\"" -D___BAT_EXTENSION="\"\"" -D___PRIMAL os_time.c -D___LIBRARY
```
Clang claims to support `-fno-trapping-math`, yet it doesn't appear on the command line.  I couldn't find anything in `config.log` to explain this.

In gcc this option would make a noticeable difference in some code, but I don't know how much it affects clang/llvm.

**Comment by svenha** [comment]
The code block in configure for -fno-trapping-math can be moved up from the gcc-specific part to the part for gcc and llvm (look for the comment `Determine if GNU gcc or LLVM gcc is being used.`). In addition you must delete the corresponding lines like `DASH_fno_trapping_math=""` There are more such options that clang supports, e.g.  -fschedule-insns2.

Maybe this issue should be closed.
