### ISSUE TITLE
unit-tests/04-coverage/_num-stress.scm should be named unit-tests/04-coverage/_num.scm

### ISSUE THREAD

**Issue by gambiteer** [gambit/gambit#263]
Marc:
unit-tests/04-coverage/_num-stress.scm

should be named

unit-tests/04-coverage/_num.scm

It should be tested every time the unit tests are run.  It's just a lot of little one-line tests.

**Comment by feeley** [comment]
Go for it!  If it turns out to run for too long we can always make it a "stress" test again.

**Comment by gambiteer** [comment]
It seems I don't yet know how to rename a file in github.

**Comment by feeley** [comment]
```
git mv foo-bar.scm foobar.scm
```

**Comment by gambiteer** [comment]
Fixed.
