### ISSUE TITLE
Self referencing loops in macro expansion

### ISSUE THREAD

**Issue by eval-apply** [gambit/gambit#277]
I just stumbled across a case where the macro expander seems to get stuck in a loop (killed after some minutes), I realise the code given below is problematic but I was surprised that it caused issues with Gambit compiler.  Is there a way to short circuit the self referencing environment lookup?

```scheme
(define-macro (foo bar)
  `(foo ,bar))

(foo 'baz)
```

Fails to terminate correctly when run via `gsc -exe t.scm`.  Gambit version and compile flags: `v4.8.8 20170203122653 x86_64-apple-darwin16.6.0 "./configure '--enable-gcc-opts' '--enable-single-host' 'CC=/usr/local/bin/gcc-7'"`

**Comment by feeley** [comment]
This is not a problem with environment lookup.  You are asking ```(foo 'baz)``` to expand to ```(foo 'baz)``` and the compiler is doing exactly that.  And then ```(foo 'baz)``` will be expanded to ```(foo 'baz)``` ad infinitum.  This is no different than an infinite loop at execution time.  Recursive macros need a termination condition, which you don't have here.

**Comment by eval-apply** [comment]
Oh right of course!  Right you are apologies for the noise.
