### ISSUE TITLE
unwind thunks not invoked when thread exits with exception

### ISSUE THREAD

**Issue by vyzo** [gambit/gambit#295]
In the following scenario, the unwind thunk fails to be invoked:
```
(define (thread-main)
  (dynamic-wind
      void
      (lambda ()
        (with-exception-catcher
         raise
         (lambda () (raise 'foo))))
      (lambda ()
        (display "FINALLY!")
        (newline))))

> (thread-start! (make-thread thread-main))
#<thread #2>
> (thread-join! #2)
*** ERROR IN (console)@12.1 -- Uncaught exception: foo
(thread-join! '#<thread #2>)
1> ,t
>
```

Expected result is to see `FINALLY` displayed in the console, but nothing happens.
Instead the thread just exits with the exception without ever invoking the unwind thunk.

This is a critical bug, as it breaks finalization of background threads.

**Comment by vyzo** [comment]
cc @fare

**Comment by vyzo** [comment]
In fact it is more generalized: if the thread exits with an exception, the unwind thunk doesn't get inboked at all:
```
(define (thread-main)
  (dynamic-wind
      void
      (lambda () (raise 'foo))
      (lambda ()
        (display "FINALLY!")
        (newline))))
> (thread-start! (make-thread thread-main))
#<thread #3>
> (thread-join! #3)
*** ERROR IN (console)@25.1 -- Uncaught exception: foo
(thread-join! '#<thread #3>)
1> ,t
>
```

**Comment by feeley** [comment]
This is expected behaviour.  Exceptions and continuations are not tied together like in other languages.  Raising an exception does nothing to the current continuation (i.e. the exception handler is executed with the same continuation as the "raise").  To actually unwind the stack you must call a continuation higher in the stack, for example like this:

```
(define (thread-main)
  (with-exception-catcher
   (lambda (exc)
     (println "caught exception"))
   (lambda ()
     (dynamic-wind
       void
       (lambda ()
         (raise 'foo))
       (lambda ()
         (println "FINALLY!"))))))

(define t (thread-start! (make-thread thread-main)))

(thread-join! t)
```

**Comment by vyzo** [comment]
So basically all threads need to have an exception catcher to reliably invoke unwind thunks!?

Is there a way to set the default thread exception handler to unwind the stack without plastering an exception catcher in all created threads?

**Comment by feeley** [comment]
The problem is not with the primordial exception handler (which can be set with ```(set! ##primordial-exception-handler-hook ...)```).

The problem is that dynamic-wind needs a destination continuation to know how much to unwind. Here you want the initial continuation passed to the thread's thunk, and the simplest way to get to it is to capture it when the thunk is executed.  This could be done by adding a wrapper around ```make-thread```.

Another option would be to capture the continuation when the exception is raised and walk up the stack to find the initial continuation... rather messy stuff.  Or a special purpose procedure could be written to unwind all of the unwind stack (see ```##continuation-unwind-wind``` in lib/_thread.scm).

Let me repeat my position that exceptions and continuations should not be tied together as it restricts the flexibility of exceptions.  The (traditional) model that all functions that are called must eventually return is not correct when call/cc is available, and in this respect ```dynamic-wind``` is a dubious construct.

**Comment by vyzo** [comment]
Your position is understood, and I agree that we don't want to restrict the system's flexibility.

I am just looking for an efficient way to guarantee unwind thunks for finalizers, as we have
a `with-unwind-protect form in Gerbil that simulates unwind-protect with dynamic-wind:
```
(define (with-unwind-protect K fini)
  (let ((once #f))
    (dynamic-wind
      (lambda ()
        (declare (not interrupts-enabled))
        (when once
          (error "Cannot reenter unwind protected block"))
        (set! once #t))
      K fini)))
```

**Comment by vyzo** [comment]
Obviously it would be really nice if we had a native `unwind-protect` construct!

**Comment by feeley** [comment]
Just like ```dynamic-wind``` the simpler ```unwind-protect``` construct is dubious in a language with first-class continuations. Both of these constructs reinforce the model that functions that are called eventually return.  This is true in most other languages and it would be true of a language built on top of Gambit that hides the existence of first-class continuations. Is Gerbil headed that way?

There is definitely a language design tradeoff here. A language that does things automatically for the programmer (like unwinding the unwind-protect stack when a thread terminates) may provide a model that is "the right thing" to do 99% of the time (and thus simplifies the programming task), but it means that in the remaining 1% of the time the language can't be used for that task.  I prefer a different tradeoff here. In your particular use case, you can use a ```with-exception-catcher``` wrapper to achieve what you want.  So your use case requires a tiny bit of extra work (easily abstracted in a function or macro).  If performance is critical, the best solution is to walk the continuation to find the initial continuation and do a ```continuation-graft``` that raises the exception.

**Comment by vyzo** [comment]
> This is true in most other languages and it would be true of a language built on top of Gambit that hides the existence of first-class continuations. Is Gerbil headed that way?

Not at all! Gerbil intends to hide nothing from Gambit and whole-heartedly embraces efficient threads and continuations :)

We do need however some way to handle resource finalization in server threads (actors). There, it is more applicable to use a stack unwind model for resource management, as the computations are fundamentally i/o loops and abortive exceptions is a natural way to do control flow in that context.

> I prefer a different tradeoff here. In your particular use case, you can use a with-exception-catcher wrapper to achieve what you want. 

I am with you. I do use a spawn wrapper to make-thread/start-thread! which takes arguments among other things, so I just added the default with-exception-catcher wrapper as you suggested. 
Just one line of code indeed solves the issue, and the performance impact is minimal as far as I can tell.

I was just surprised to find out that unwind thunks behave completely independently from continuations in the absence of a root exception handler. I hadn't noticed before, because server threads typically have an exception handler that logs the exception -- and so unwind thunks were executing as expected.

**Comment by vyzo** [comment]
edited a typo!

**Comment by feeley** [comment]
But if you use the ```with-exception-catcher``` wrapper in your spawn operation, doesn't that imply that the unwinding will always be done unconditionally on uncaught exceptions?  You can't have it both ways! It seems to me the programmer should be involved in the decision.  I assume Gambit's ```make-thread``` is still available and would be a workaround, but I don't like "workarounds" (here possibly also losing some important feature that you've put in your spawn construct).

I'll look into the implementation of a ```##thread-body-continuation``` construct that returns the continuation of the thread's body (i.e. the one a ```##continuation-capture``` at the very beginning of a thread would return).

**Comment by vyzo** [comment]
> But if you use the with-exception-catcher wrapper in your spawn operation, doesn't that imply that the unwinding will always be done unconditionally on uncaught exceptions? You can't have it both ways! It seems to me the programmer should be involved in the decision.

Sadly yes, that's the part I don't like. 

>  I assume Gambit's make-thread is still available and would be a workaround, but I don't like "workarounds"

 `make-thread/start-thread!` of course is still available, so a programmer can make the decision to use it. 
But yeah, it's a workaround, I'd like to use the spawn form consistently.

> I'll look into the implementation of a ##thread-body-continuation construct that returns the continuation of the thread's body

thanks!

**Comment by feeley** [comment]
Actually easy to implement...

```
(define (##continuation-oldest cont)
  (let loop ((cont cont))
    (let ((next (##continuation-next cont)))
      (if next
          (loop next)
          cont))))
```

So the primordial exception handler hook should be set to something like

```
(set! ##primordial-exception-handler-hook
      (lambda (exc handler)
        (##continuation-capture
         (lambda (cont)
           (##continuation-graft
            (##continuation-oldest cont)
            handler
            exc)))))
```

In a way, this lazily captures the oldest continuation, so you only pay the price of the continuation capture if there is an uncaught exception.

**Comment by vyzo** [comment]
Excellent, that's pretty much what I need.

**Comment by feeley** [comment]
I'll add this to the Gambit library under the name ```##continuation-last``` which seems more logical (it is the last continuation frame accessible with repeated ```##continuation-next``` on the continuation).

**Comment by feeley** [comment]
Done!

**Comment by vyzo** [comment]
thank you marc!
