### ISSUE TITLE
Version 3, for Freedos

### ISSUE THREAD

**Issue by GHExplorer** [gambit/gambit#307]
Hi,

Am I posting in the right place?

I found a flash drive with FreeDos installed, and am having some fun with older applications.  Is Version 3 of Gambit available?  This website

https://owainkenwayucl.github.io/2017/08/06/UsefulToolsFreeDOS.html

Says that 3.x was compatible with Freedos.

**Comment by gambiteer** [comment]
This page:

http://gambitscheme.org/wiki/index.php/Distributions

has version 3.0

**Comment by GHExplorer** [comment]
That's the one, thanks.

**Comment by gambiteer** [comment]
closing
