### ISSUE TITLE
Double tilde (~~) not working as expected

### ISSUE THREAD

**Issue by mjsir911** [gambit/gambit#329]
Pulling from the [documentation](http://www.iro.umontreal.ca/~gambit/doc/gambit.html#index-_007e_007e):
```
> (path-expand "~~lib/foo")
"/usr/local/Gambit/lib/foo"
```

On my machine, `~~` is not expanded
```scheme
> (current-directory)
"/tmp/tmp.183VvTXcqP/"
> (path-expand "~~lib/foo")
"/tmp/tmp.183VvTXcqP/~~lib/foo"

> (path-expand "~~")
"/usr/"
> (path-expand "foo" "~~")
"~~/foo"
```

```bash
$ gsi -v
v4.2.8
```

**Comment by feeley** [comment]
Could you try with a more recent version of Gambit?  v4.2.8 is 10 years old!

**Comment by mjsir911** [comment]
Some of the points presented in the initial issue are simply due to age. I took a look at the documentation for my version, and the only real problem that still holds up is
```scheme
> (path-expand "foo" "~~")
"~~/foo"
```
Feel free to close this issue, the real problem here is that the version installed through my repository manager (dpkg) is *ten years old*

**Comment by abdelq** [comment]
@mjsir911 FYI, 4.8.8 just recently landed on sid.

**Comment by mjsir911** [comment]
Actually thanks, that solves my problem entirely.
