### ISSUE TITLE
Race condition running tests 7 and 10 in parallel

### ISSUE THREAD

**Issue by abdelq** [gambit/gambit#330]
Tests failed on a Hewlett Packard Precision Architecture (HP/PA) server due to a race condition between
parallel runs of tests 7 and 10. Technically, it could happen in other architectures as well:

    ------------ TEST 7 (memory management and C-interface)
    rm -f mem.c mem_.c mem.o mem_.o mem
    LD_LIBRARY_PATH=../lib:../gsi:../gsc: ../gsc/gsc -:~~bin=../bin,~~lib=../lib,~~include=../include -f -warnings -o mem -exe mem.scm
    56.590734000000005 secs elapsed cpu time
    heartbeat frequency = 217.70348481431606 Hz
    [...]
    ------------ TEST 10 (consistency of lib/gambit#.scm)
    rm -rf mem.o mem.o*
    LD_LIBRARY_PATH=../lib:../gsi:../gsc: ../gsc/gsc -:~~bin=../bin,~~lib=../lib,~~include=../include -f -i test10.scm
    gcc: error: mem.o: No such file or directory
    makefile:148: recipe for target 'test7' failed
    make[2]: *** [test7] Error 70
    [...]

[Full log](https://buildd.debian.org/status/fetch.php?pkg=gambc&arch=hppa&ver=4.8.8-2&stamp=1515173584&raw=0)

**Comment by feeley** [comment]
I assume you got that with a ```make -j check```?  That's not the way to run the self checks...  I guess the makefile could be changed to force sequential execution when using a parallel make.
