### ISSUE TITLE
Failed building with musl-gcc

### ISSUE THREAD

**Issue by ChengCat** [gambit/gambit#332]
Hi, I was trying to build gambit with `musl`, which is an alternative implementation of libc. I got this error:

```
os_base.c: In function ‘___err_code_from_h_errno’:
os_base.c:968:12: error: ‘NETDB_INTERNAL’ undeclared (first use in this function)
   if (e == NETDB_INTERNAL)
            ^~~~~~~~~~~~~~
os_base.c:968:12: note: each undeclared identifier is reported only once for each function it appears in
os_base.c:983:12: error: ‘NETDB_SUCCESS’ undeclared (first use in this function)
   if (e == NETDB_SUCCESS)
            ^~~~~~~~~~~~~
```

It seems that `NETDB_INTERNAL` and `NETDB_SUCCESS` are not defined by POSIX.

Gambit was configured as:
```
CC=musl-gcc ./configure \
  --enable-single-host \
  --enable-c-opt \
  --enable-ansi-c \
  --enable-gcc-opts
```

I am not sure how to properly fix this.

**Comment by feeley** [comment]
Can you check if this helps: https://gist.github.com/mbuelte/3666df1345828a807526767eacf4f52e

**Comment by ChengCat** [comment]
Thanks for the reply. I simply did the following (which is basically the same with the gist patch), and gambit was compiled successfully.
```
CC=musl-gcc ./configure \
  --enable-single-host \
  --enable-c-opt \
  --enable-ansi-c \
  --enable-gcc-opts
CFLAGS="-DNETDB_INTERNAL=-1 -DNETDB_SUCCESS=0" make from-scratch -j 4
```

However I can't confirm this is a proper fix, because I am not using any related features.

**Comment by feeley** [comment]
Could you check if 490f0a7d50125478f374330f0b8754bc0aee3746 fixes the issue?

**Comment by feeley** [comment]
Please reopen if 490f0a7 did not fix the issue.
