### ISSUE TITLE
Segfaults in gsi on centos 6 and gcc7

### ISSUE THREAD

**Issue by kunabi** [gambit/gambit#333]
The full configure/build/segfault history is here https://gist.github.com/63e8aad5952995f87bc5f489edc8b2cc

root@e332287e977a pkgsrc]# /usr/pkg/gcc7/bin/gcc -v
Using built-in specs.
COLLECT_GCC=/usr/pkg/gcc7/bin/gcc
COLLECT_LTO_WRAPPER=/usr/pkg/gcc7/libexec/gcc/x86_64-redhat-linux/7.1.0/lto-wrapper
Target: x86_64-redhat-linux
Configured with: ../gcc-7.1.0/configure --disable-libstdcxx-pch --enable-nls --with-libiconv-prefix=/usr --disable-mu
ltilib --enable-__cxa_atexit --with-gxx-include-dir=/usr/pkg/gcc7/include/c++/ --enable-libssp --enable-languages='c
obj-c++ objc fortran c++' --enable-shared --enable-long-long --with-local-prefix=/usr/pkg/gcc7 --enable-threads=posix
--with-boot-ldflags='-static-libstdc++ -static-libgcc -Wl,-R/usr/pkg/lib ' --with-arch=nocona --with-tune=nocona --
with-fpmath=sse --prefix=/usr/pkg/gcc7 --build=x86_64-redhat-linux --host=x86_64-redhat-linux --infodir=/usr/pkg/gcc7
/info --mandir=/usr/pkg/gcc7/man
Thread model: posix
gcc version 7.1.0 (GCC)

Using --enable-c-opt=-O0 prevents the segfault.

**Comment by feeley** [comment]
Please also include the Gambit configure options and a transcript of the moment it actually segfaults (in a test? a compilation? gsi? gsc? ...).  How much of the self tests succeeded?

**Comment by kunabi** [comment]
Fixed link above with full configure/build/segfault history.

**Comment by feeley** [comment]
That transcript does not show the configure options.  Please report the details otherwise I can't reproduce the issue. Also please report the result of ```git show```.  The fact that gdb has no backtrace does not help... could you try with the ```--enable-debug``` so that gdb generates a backtrace.

**Comment by kunabi** [comment]
Sorry about that. Here is a complete log.
https://gist.github.com/ober/a8411a38262145317b69a14e60e6e09c

**Comment by kunabi** [comment]
sh-4.1# git show
commit 26bb866548afeaef6d59a40b14291400ce993d1d
Merge: 37b111a 5ef7020
Author: Marc Feeley <feeley@iro.umontreal.ca>
Date:   Thu Jan 11 18:50:50 2018 -0500

    Merge pull request #331 from abdelq/serial-tests
    
    Run tests serially

The gdb with the debug version produced:
sh-4.1# gdb gsc/gsc
GNU gdb (GDB) Red Hat Enterprise Linux (7.2-92.el6)
Copyright (C) 2010 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>...
Reading symbols from /pkgsrc/gambit/gsc/gsc...done.
(gdb) set args ./foo.scm
(gdb) run
Starting program: /pkgsrc/gambit/gsc/gsc ./foo.scm
warning: Error disabling address space randomization: Operation not permitted
During startup program terminated with signal SIGSEGV, Segmentation fault.
(gdb) bt
No stack.

**Comment by gambiteer** [comment]
OK, I looked at this a bit.  I don't have precisely your system, so I tried to match things as well as I could.

I used the following compiler:
```
heine:~/programs/gambit/gambit> /usr/local/gcc-7.1.0/bin/gcc -v
Using built-in specs.
COLLECT_GCC=/usr/local/gcc-7.1.0/bin/gcc
COLLECT_LTO_WRAPPER=/usr/local/gcc-7.1.0/libexec/gcc/x86_64-pc-linux-gnu/7.1.0/lto-wrapper
Target: x86_64-pc-linux-gnu
Configured with: ../../gcc-7.1.0/configure --disable-multilib --enable-languages=c --prefix=/usr/local/gcc-7.1.0
Thread model: posix
gcc version 7.1.0 (GCC) 
```
I used the following configure, build, make check, and your specific test commands:
```
    12	21:08	./configure CC='/usr/local/gcc-7.1.0/bin/gcc -g' --enable-openssl --enable-single-host
    13	21:08	make -j
    14	21:11	make check
    15	21:13	touch foo.scm
    16	21:13	./gsc/gsc foo.scm
```
The `-g` option does not change the generated code, it just adds annotations for gdb.

I used the latest git d1991ba7e90ed0149964320f7cafa1a8289e61f0.

The command `./gsc/gsc foo.scm` did not segfault.  I don't know how to try to reproduce your problem more precisely.

I notice that your gcc is configured with `--with-arch=nocona`.  I'm not actually sure how this affects files compiled with this compiler.

Perhaps you could configure gambit with `CC='/usr/local/gcc-7.1.0/bin/gcc -march=generic'` and see what happens.

**Comment by gambiteer** [comment]
Perhaps if you configured with
```
./configure CC='gcc -g' --enable-openssl --enable-single-host
```
then gdb might offer better information about the crash.

**Comment by jaimef-castlight** [comment]
Still got no stack on bt in gdb with that configure command.
The easiest way to reproduce is to run it in docker with.
<assuming docker is installed>
docker pull centos:centos6.9
docker run -it centos:centos6.9 bash
$ yum -y groupinstall 'Development tools'
$ git checkout https://github.com/gambit/gambit
$ cd gambit && ./configure --enable-openssl --enable-single-host && make -j4
$ touch foo.scm && ./gsc/gsc foo.scm -> segfault.

**Comment by kunabi** [comment]
Tried the above configure command and still got the "no stack" on the gdb.
The easiest way to reproduce this is via docker.
Assuming you have docker installed, the commands would be:
$ docker pull centos:centos6.9
$ docker run -it centos:centos6.9 bash
docker> $ yum -y groupinstall 'Development tools'yum -y groupinstall 'Development tools'
docker> $ git clone https://github.com/gambit/gambit
docker> $ cd gambit && ./configure --enable-openssl --enable-single-host && make -j4
docker> $ touch foo.scm && ./gsc/gsc foo.scm # segfault

**Comment by feeley** [comment]
Can you report the result of "make check"?

**Comment by feeley** [comment]
I installed centos 6.9 with the development tools.  The "make check" fails when ```shell-command``` is called.  After some investigation it seems that the value of ```___ps``` is incorrect after the call to ```___os_device_stream_open_process```, so to debug this in ```lib/_kernel.c``` I added a printout of ```___ps``` before/after the call to ```___os_device_stream_open_process```:

```
   printf("before ___ps=%p\n",___ps);
___CFUN_ASSIGN(___result,___os_device_stream_open_process(___arg1,___arg2,___arg3,___arg4))
   printf("after ___ps=%p\n",___ps);
```

The macros expand this to this C code:

```
   printf("before ___ps=%p\n",___ps);
___result = ___os_device_stream_open_process(___ps->fp[-((1 -(((((4 +1)+3)+(4)-1)/(4))*(4))))],___ps->fp[-((2 -(((((4 +1)+3)+(4)-1)/(4))*(4))))],___ps->fp[-((3 -(((((4 +1)+3)+(4)-1)/(4))*(4))))],___ps->fp[-((4 -(((((4 +1)+3)+(4)-1)/(4))*(4))))]);
   printf("after ___ps=%p\n",___ps);
```

Note that variable ```___ps``` (a local variable) is not changed between the printfs.

This is the output I get, which shows that ___ps has been changed:

```
Gambit v4.8.8

> (shell-command "echo hello")
before ___ps=0xaf9180
Detaching after fork from child process 384.
after ___ps=0xa024002
```

I strongly suspect a C compiler bug...

**Comment by feeley** [comment]
After further investigation it is not a C compiler bug.  There's a problem with Gambit's signal handling code. Will fix this.

**Comment by feeley** [comment]
Testing on centos confirms this issue is resolved.
