### ISSUE TITLE
Universal backend woes.

### ISSUE THREAD

**Issue by kunabi** [gambit/gambit#334]
echo '(display "hello world") (newline)' > hw.scm
gsc -o hw.py -target python -exe test.scm              
I did this for python, ruby, js, and php.
None of them appeared to work.

Python: Traceback (most recent call last):
  File "./hw.py", line 482274, in <module>
    g_module_register([g_make_interned_symbol("_gambit"),g_bb1__20___gambit,1,g_null_obj,False])
  File "./hw.py", line 639, in g_module_register
    g_trampoline(g_module_table[0][1])
  File "./hw.py", line 61, in g_trampoline
    pc = pc()
  File "./hw.py", line 1139, in g_bb1__20_test
    return g_check_procedure_glo(g_glo["display"],g_cst1_test)()
  File "./hw.py", line 364180, in g_bb1_display
    g_r2 = g_r2[6]
TypeError: 'NoneType' object has no attribute '__getitem__'

Php:
##thread-end-with-uncaught-exception! not implemented yet

Ruby: 
./hw.rb:380662:in `block in <main>': undefined method `[]' for nil:NilClass (NoMethodError)
        from ./hw.rb:1337:in `[]'
        from ./hw.rb:1337:in `block in <main>'
        from ./hw.rb:24:in `[]'
        from ./hw.rb:24:in `g_trampoline'
        from ./hw.rb:797:in `g_module_register'
        from ./hw.rb:503000:in `<main>'

Is there something I'm missing?

**Comment by feeley** [comment]
```
echo '(display "hello world") (newline)' > hw.scm
cd lib
make _gambit.py
make _gambit.rb
make _gambit.js
cd ..
gsc/gsc -:=. -o hw.py -target python -exe test.scm
gsc/gsc -:=. -o hw.rb -target ruby -exe test.scm
gsc/gsc -:=. -o hw.js -target js -exe test.scm
./hw.py
./hw.rb
./hw.js
```

They all run fine here.

**Comment by feeley** [comment]
Sorry... I compiled "test.scm" rather than "hw.scm" and it was a hello world program... stay tuned.

**Comment by feeley** [comment]
Here is a hello world program that works:

```
echo '(println "hello world")' > hw.scm
cd lib
make _gambit.py
make _gambit.rb
make _gambit.js
cd ..
gsc/gsc -:=. -o hw-py.py -target python -exe hw.scm
gsc/gsc -:=. -o hw-rb.rb -target ruby -exe hw.scm
gsc/gsc -:=. -o hw-js.js -target js -exe hw.scm
./hw-py.py
./hw-rb.rb
./hw-js.js
```
Note the use of println.  In your original program you are using display which is not fully working (because the Gambit I/O implementation is quite complex and is intertwined with the thread system, the scheduler, etc).  A lot of the Gambit library is currently working but a full implementation (in particular I/O and threads) is still a work in progress for the universal back-end.

For that reason, you might be better off interfacing directly with the host language with ```##inline-host-statement``` and ```##inline-host-expression```.  Here is an equivalent hello world program that directly uses the JavaScript ```console.log``` to do output:

```
(##inline-host-statement "console.log(g_scm2host(@1@));" "hello world")
```

**Comment by feeley** [comment]
By the way, the problem is not with the ```display``` procedure's logic.  It actually works fine when the output port is a string port:

```
% echo "(println (call-with-output-string '() (lambda (port) (display (list 1 2 car port 'hello) port))))" > hw.scm
% gsc/gsc -:=. -o hw-js.js -target js -exe hw.scm
% ./hw-js.js
(1 2 #<procedure #1 car> #<output-port #2 (string)> hello)
```

The problem is at a lower level when the data is drained from the I/O buffer.

**Comment by kunabi** [comment]
Thanks. will circle back after more testing.
