### ISSUE TITLE
missing easy checks - segfaulting code

### ISSUE THREAD

**Issue by rgh36167** [gambit/gambit#342]
I am using gsc 4.7.9 as compiled by lambdanative  (git/head) and noticed that the compiler doesn't complain on some trivial errors like too few arguments to locally defined functions and instead produces segfaulting code:

```
(define (fac x)
  (if (< x 3) x
        (* x (fac (- x 1))))
  )

(fac)
```

Did I miss some option to enable checking for this type of erros?

**Comment by feeley** [comment]
I'm not sure how the lambdanative system compiles Gambit.  Normally all predefined functions test the number and type of their arguments, so this should give an error.  For example here's what I get with v4.8.9:

```
$ gsc fac.scm 
$ gsi fac
*** ERROR IN ##load -- Wrong number of arguments passed to procedure
(fac)
```

Perhaps you should contact the lambdanative team.

**Comment by feeley** [comment]
By the way, the reason why the call ```(fac)``` does not give an error at compile time is that it is possible for a ```(set! fac ...)``` to change the value of ```fac``` that would make this code work, for example ```(set! fac list)``` just before the call ```(fac)```.  The assignment could also be done in another thread, so it is not directly visible when compiling the module.

**Comment by rgh36167** [comment]
On Mon, Mar 19, 2018 at 12:39:56AM +0000, Marc Feeley wrote:
> By the way, the reason why the call ```(fac)``` does not give an error at compile time is that it is possible for a ```(set! fac ...)``` to change the value of ```fac``` that would make this code work, for example ```(set! fac list)``` just before the call ```(fac)```.  The assignment could also be done in another thread, so it is not directly visible when compiling the module.

true, but it would be unusual. gsc also has the option to warn about undefined variables even if they could have been defined in some other thread?

So some kind of optional warning would be appreciated even if it would have some false positives. Is there some scheme-lint that has been tested to work well with gambit code?
