### ISSUE TITLE
clock_gettime only available since MacOS 10.12

### ISSUE THREAD

**Issue by philsuero** [gambit/gambit#346]
I'm running the OSX 10.9.5 and I'm not able to run gambit 4.8.9.
The following error is given:

```
$ gsc
dyld: lazy symbol binding failed: Symbol not found: _clock_gettime
  Referenced from: /usr/local/bin/gsc
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: _clock_gettime
  Referenced from: /usr/local/bin/gsc
  Expected in: /usr/lib/libSystem.B.dylib

Trace/BPT trap: 5

```

This happens because the clock_gettime is only available since MacOS 10.12
I would be glad if you could remove that, please.
The gambit 4.8.8 works fine.

**Comment by feeley** [comment]
Fixed with 2b42505ffdc8f5083b13a2e42aad02bde72825fc (however the prebuilt MacOS executable will only be available at the next release of Gambit).
