### ISSUE TITLE
ieee library is not shipped with new glibc 

### ISSUE THREAD

**Issue by danielsz** [gambit/gambit#352]
Starting with `glibc 2.27`, support for the `ieee` library (part of SVID specification) has been removed. The `libieee.a` library is therefore not shipped anymore. GCC tries to link with this library due to the use of the `-mieee-fp` option, causing compilation with `gsc` to fail.

**Comment by gambiteer** [comment]
Marc, is it just a matter of removing this line from configure.ac
```
    AC_CHECK_C_COMPILER_OPT(-mieee-fp,DASH_mieee_fp)
```
and rerunning `autoconf`?

**Comment by feeley** [comment]
Yes that should work.  And all references to DASH_mieee_fp

Marc

**Comment by gambiteer** [comment]
It should be fixed with 17973fe945883ff14a484b95d5e5359bf393d0b3

**Comment by danielsz** [comment]
https://github.com/gambit/gambit/commit/17973fe945883ff14a484b95d5e5359bf393d0b3 confirmed working fix. Thank you!
