### ISSUE TITLE
input-port-byte-position: position limited to int32

### ISSUE THREAD

**Issue by crocusino** [gambit/gambit#358]
Trying to seek in a large input file 

`(input-port-byte-position '#<input-port #2 "/scr/EIVE04.DAT"> 225453735936)`

fails due to

`(Argument 2) Can't convert to C int32`

I couldn't find the particular definition in the code to change the type to 64bit int (on 64bit machines at least)

**Comment by crocusino** [comment]
I see in `lib/os_io.h`: `typedef int ___stream_index;`, which goes to many macros like `___device_stream_seek_raw_virt(self,pos,whence)` in the same file. So this seems to be the candidate for the appropriate type change.

However, there are also quite a few explicit `int` types for position parameters like
` int new_pos;` in `___device_file_seek_raw_virt` in file `lib/os.io.c`. That should be rather fixed by someone closely familiar with the code...

**Comment by svenha** [comment]
This is still an annoying issue, esp. on a 64bit machine.
