### ISSUE TITLE
IPv6: open-tcp-server aborts with smashed stack

### ISSUE THREAD

**Issue by 0-8-15** [gambit/gambit#362]
u@mb ~ $  gsi
Gambit v4.2.8
> (define ser ( open-tcp-server (list server-address: (u16vector #xfd87 #xd87e #xeb43 #x4e52 #x1628 #x51a2 #x5245 #x8eef) port-number: 8080 reuse-address: #t)))  
*** stack smashing detected ***: gsi terminated

**Comment by feeley** [comment]
Fixed by 1f19fb05d1b3eec4b0352270e9c527ae60498fee
