### ISSUE TITLE
Gambit doesn't work with LibreSSL

### ISSUE THREAD

**Issue by zmyrgel** [gambit/gambit#366]
Gambits TLS functionality doesn't work with LibreSSL.
Gambit compiles just with `--enable-openssl` flag enabled but when trying to use TLS it errors out. Simple example as follows:

```
 $ gsi
Gambit v4.9.0

> (make-tls-context)
*** ERROR IN (console)@1.1 -- 
(make-tls-context)
1> 
```
I'm testing this with OpenBSD-current which uses libressl 2.8.0. I asked around on IRC from void linux users and same thing seems to happen there as well. Void linux also uses LibreSSL instead of OpenSSL so I assume LibreSSL is root of this issue.

LibreSSL API should be subset of OpenSSL 1.0.1 API so I would have expected Gambit to have worked with it just fine. If any, I would have expected issues during compilation. As the code compiles I'm not sure what is wrong with the code and the generic error doesn't help pointing to the root of this.

**Comment by zmyrgel** [comment]
Possibly found the issue, libressl doesn't support sslv2/v3 anymore so the min_tls_version check fails. I'll cook a patch for it. I have simple version to make tls 1.2, 1.1 working but setting min version to tls1.0 fails at the moment.

**Comment by belmarca** [comment]
PR https://github.com/gambit/gambit/pull/367 is supposed to fix this issue and has already been merged. Can this one be closed?

**Comment by juanfra684** [comment]
@belmarca yes, gambit has been building fine with libressl for a while on OpenBSD.

**Comment by gambiteer** [comment]
Reported to work
