### ISSUE TITLE
gsi doesn't read from stdin

### ISSUE THREAD

**Issue by ecraven** [gambit/gambit#370]
The following produces no output except for the prompt
```
echo '(display "foo")' | gsi
```
There are quite a few cases where I would like to call `gsi` in this way, is there any way to make this work?

**Comment by feeley** [comment]
By default, the REPL I/O goes to the controlling terminal, which is not the same thing as stdin. This is convenient to allow debugging with the REPL programs that read from stdin.  If you want gsi's REPL to read from stdin, use the -:d- runtime option, i.e.

```
echo '(display "foo")' | gsi -:d-
```

**Comment by feeley** [comment]
By the way, this may be a more interesting option as it avoids the banner and prompts:

```
gsi -e '(display "foo")'
```
