### ISSUE TITLE
Incorrect check in OpenSSL DH code

### ISSUE THREAD

**Issue by zmyrgel** [gambit/gambit#372]
https://github.com/gambit/gambit/blob/79f5bf774e89c1220bece667598877821ca94b7c/lib/os_io.c#L4205

The check here is incorrect, static arrays evaluate always to true. The code should check the return values of  the BN_bin2bn calls above it so it should read:

```
if (bp == NULL || bg == NULL)
```

**Comment by feeley** [comment]
Thank you for spotting this.  Could you make a PR?
