### ISSUE TITLE
iOS GambitREPL wiki tab gets 404 

### ISSUE THREAD

**Issue by KalmanReti** [gambit/gambit#376]
The requested URL /~gambit/~gambit/wiki/index.php/Gambit_REPL was not found on this server.

This version downloaded today from App Store on iPad mini 2 running latest available iOS, if that matters.

Kálmán Réti

**Comment by feeley** [comment]
I think there's a problem with the wiki site.  Will take a look.

**Comment by feeley** [comment]
Should be back up now.
