### ISSUE TITLE
call-with-output-string could be made more compatible

### ISSUE THREAD

**Issue by svenha** [gambit/gambit#378]
`call-with-output-string` is a popular extension of SRFI-6. Most implementations only support one argument (proc), see for example https://practical-scheme.net/wiliki/schemexref.cgi?call-with-output-string
Gambit requires an additional argument in the first position (string-or-settings). I think that turning this additional argument into an optional one with an adequate default would be a good idea.

**Comment by feeley** [comment]
Thanks for the suggestion.  Fixed by a5d0db9843a55052da4aa22fdd33e12898daa331

**Comment by svenha** [comment]
Thanks for the quick help!
