### ISSUE TITLE
Build under Visual Studio doesn't correctly initialize the compiler wrapper script

### ISSUE THREAD

**Issue by lucaregini** [gambit/gambit#380]
I have built the Gambit executables under windows 10, 64 bit, using the VS2015 x64 Native Tools Command Line prompt.
The source code has been cloned in C:\gambit and the binaries have been built by executing "misc\vstudio.bat c:\gambit" from the C:\gambit folder.

When I try to compile the c:\gambit\examples\pi\pi.scm file by executing:

c:\gambit\gsc\gsc.exe -o pi.exe -exe pi.scm from the c:\gambit\examples\pi\ folder I get the following: 

c:\gambit\examples\pi>c:\gambit\gsc\gsc.exe -o pi.exe -exe pi.scm
*** ERROR IN ##compile-file -- No such file or directory
(open-process
 '(path: "c:\\gambit\\bin\\gambcomp-C.bat" arguments: ("obj") directory: "c:\\gambit\\examples\\pi\\" environment: ...
)

The gambcomp-C.bat file does not exists as it is supposed to be created by a configure step which doesn't apply to a Visual Studio build

**Comment by feeley** [comment]
The misc/vstudio.bat script creates the file in bin/ but the name seems wrong (gsc-cc-o.bat rather than gambcomp-C.bat).  Could you rename the file manually and move it to c:\gambit\bin ?  If that works I will update the vstudio.bat file.

**Comment by feeley** [comment]
I took a better look at gsc-cc-o.bat and it is rather old and doesn't support -exe.  You are better off copying bin/gambcomp-C.bat.windows.in to bin/gambcomp-C.bat and replacing the @XXX@ in that file with appropriate definitions.  This is what is done by the configure script.  Of course misc/vstudio.bat should be modified to do this, but I'll wait for your tests before doing so.

**Comment by lucaregini** [comment]
The bin/gambcomp-C.bat.windows.in script is missing a coherent definition for these variables:
BUILD_OBJ_ECHO_BAT
BUILD_DYN_ECHO_BAT
BUILD_LIB_ECHO_BAT
BUILD_EXE_ECHO_BAT

I guess the intention is just to print the on stdout the command line commands for the corresponding build options so I am replacing them with 
BUILD_OBJ
BUILD_DYN
BUILD_LIB
BUILD_EXE

**Comment by lucaregini** [comment]
I have managed to build working executables under the VS 2015 x64 shell by using the attached gambcomp-C.bat file. 
My tests show that building the executable step by step works.
For example the following sequence of commands generate a working executable for the example program /examples/pi.scm:
-gsc -c pi.scm
-gsc -link pi.c
-gsc -obj pi.c pi_.c
-gsc  -o pi.exe -exe pi_.obj pi.obj

Likewise building the executable in one single step also works:
For example:
gsc -o pi.exe -exe pi.scm
generates the executable without any intermediate file.

**Comment by lucaregini** [comment]
rem gambcomp-C.bat
rem: https://docs.microsoft.com/en-us/cpp/build/reference/compiler-options-listed-alphabetically?view=vs-2017

@echo off

rem The following settings are determined by the configure script.
set GAMBCOMP_VERBOSE=yes

set C_COMPILER=cl
set C_PREPROC=cl /E


rem set FLAGS_OBJ=@FLAGS_OBJ_BAT@
rem set FLAGS_DYN=@FLAGS_DYN_BAT@
rem set FLAGS_LIB=@FLAGS_LIB_BAT@
rem set FLAGS_EXE=@FLAGS_EXE_BAT@

rem set FLAGS_OPT=@FLAGS_OPT_BAT@
rem set FLAGS_OPT_RTS=@FLAGS_OPT_RTS_BAT@

set DEFS_OBJ= 
set DEFS_DYN= -D___DYNAMIC
set DEFS_LIB= 
set DEFS_EXE= 


rem "BUILD_OBJ_ECHO_BAT": "%C_COMPILER% -I\"%GAMBITDIR_INCLUDE%\" -c -Fo%BUILD_OBJ_OUTPUT_FILENAME% %BUILD_OBJ_CC_OPTIONS% %BUILD_OBJ_INPUT_FILENAMES%",
rem "BUILD_DYN_ECHO_BAT": "%C_COMPILER% -I\"%GAMBITDIR_INCLUDE%\" -D___DYNAMIC -LD -Fe%BUILD_DYN_OUTPUT_FILENAME% %BUILD_DYN_CC_OPTIONS% %BUILD_DYN_LD_OPTIONS_PRELUDE% %BUILD_DYN_INPUT_FILENAMES% %BUILD_DYN_LD_OPTIONS%",
rem "BUILD_EXE_ECHO_BAT": "%C_COMPILER% -I\"%GAMBITDIR_INCLUDE%\" %GAMBITLIB_LOC% -Fe%BUILD_EXE_OUTPUT_FILENAME% %BUILD_EXE_CC_OPTIONS% %BUILD_EXE_LD_OPTIONS_PRELUDE% %BUILD_EXE_INPUT_FILENAMES% \"%GAMBITDIR_LIB%\\libgambit.lib\" Kernel32.Lib User32.Lib Gdi32.Lib WS2_32.Lib %GAMBITLIB_LINK% %BUILD_EXE_LD_OPTIONS%"


set BUILD_OBJ=%C_COMPILER% %FLAGS_OPT% %DEFS_OBJ% -I"%GAMBITDIR_INCLUDE%" -c -Fo"%BUILD_OBJ_OUTPUT_FILENAME%" %BUILD_OBJ_CC_OPTIONS% %BUILD_OBJ_INPUT_FILENAMES%
rem set BUILD_DYN=%C_COMPILER% %FLAGS_OPT% %FLAGS_DYN% %DEFS_DYN% -I"%GAMBITDIR_INCLUDE%" -o "%BUILD_DYN_OUTPUT_FILENAME%" %BUILD_DYN_CC_OPTIONS% %BUILD_DYN_LD_OPTIONS_PRELUDE% %BUILD_DYN_INPUT_FILENAMES% %BUILD_DYN_LD_OPTIONS%
set BUILD_DYN=%C_COMPILER% -I\"%GAMBITDIR_INCLUDE%\" -D___DYNAMIC -LD -Fe%BUILD_DYN_OUTPUT_FILENAME% %BUILD_DYN_CC_OPTIONS% %BUILD_DYN_LD_OPTIONS_PRELUDE% %BUILD_DYN_INPUT_FILENAMES% %BUILD_DYN_LD_OPTIONS%

set BUILD_LIB=echo BUILD_LIB not yet implemented
rem set BUILD_EXE=%C_COMPILER% %FLAGS_EXE% %DEFS_EXE% -I"%GAMBITDIR_INCLUDE%"  -o "%BUILD_EXE_OUTPUT_FILENAME%" %BUILD_EXE_CC_OPTIONS% %BUILD_EXE_LD_OPTIONS_PRELUDE% %BUILD_EXE_INPUT_FILENAMES% "%GAMBITDIR_LIB%/libgambit.a" %LIBS% %BUILD_EXE_LD_OPTIONS%
set BUILD_EXE=%C_COMPILER% %FLAGS_EXE% %DEFS_EXE% -I"%GAMBITDIR_INCLUDE%"  -Fe"%BUILD_EXE_OUTPUT_FILENAME%" %BUILD_EXE_CC_OPTIONS% %BUILD_EXE_LD_OPTIONS_PRELUDE% %BUILD_EXE_INPUT_FILENAMES% "%GAMBITDIR_LIB%\\libgambc.lib" Kernel32.Lib User32.Lib Gdi32.Lib WS2_32.Lib %LIBS% %BUILD_EXE_LD_OPTIONS%



set DEFS=
set LIBS= -lws2_32
set GAMBITLIB=gambit
set GAMBITGSCLIB=gambitgsc
set GAMBITGSILIB=gambitgsi
set LIB_PREFIX=lib
set LIB_EXTENSION=.lib
set OBJ_EXTENSION=.obj
set EXE_EXTENSION=.exe
set BAT_EXTENSION=.bat

echo gambcomp-C invoked with parameter ".%1" 

if "%1" == "obj" goto obj
if not "%1" == ""obj"" goto not_obj
:obj

if not "%GAMBCOMP_VERBOSE%" == "yes" goto not_obj_verbose
echo.%BUILD_OBJ%
:not_obj_verbose

%BUILD_OBJ%

goto end
:not_obj

if "%1" == "dyn" goto dyn
if not "%1" == ""dyn"" goto not_dyn
:dyn

if not "%GAMBCOMP_VERBOSE%" == "yes" goto not_dyn_verbose
echo.%BUILD_DYN%
:not_dyn_verbose

%BUILD_DYN%

goto end
:not_dyn

if "%1" == "lib" goto lib
if not "%1" == ""lib"" goto not_lib
:lib

if not "%GAMBCOMP_VERBOSE%" == "yes" goto not_lib_verbose
echo.%BUILD_LIB%
:not_lib_verbose

%BUILD_LIB%

goto end
:not_lib

if "%1" == "exe" goto exe
if not "%1" == ""exe"" goto not_exe
:exe

if not "%GAMBCOMP_VERBOSE%" == "yes" goto not_exe_verbose
echo.%BUILD_EXE%
:not_exe_verbose

%BUILD_EXE%

goto end
:not_exe


echo.gambcomp-C.bat unknown operation "%1"
exit /b 1

:end
exit /b 0

**Comment by feeley** [comment]
Fixed by e48a97fb6fdc2d66c279ddab3d6633f1e702c046
