### ISSUE TITLE
##processed-command-line returns incorrect path 

### ISSUE THREAD

**Issue by lucaregini** [gambit/gambit#381]
##processed-command-line returns an incorrect path when Gambit is compiled under Windows using visual studio and the VS2015 command prompt.

For example on my machine it returns the following output:
> ##processed-command-line
("\"C:\\Program Files (x86)\\Gambit\\v4.9.0\\bin\\gsi.exe\"")

and this cannot be parsed by path-normalize:

 (path-normalize (car ##processed-command-line))
*** ERROR IN (console)@2.1 -- The filename, directory name, or volume label syntax is incorrect.
(path-normalize "\"C:\\Program Files (x86)\\Gambit\\v4.9.0\\bin\\gsi.exe\"")

**Comment by feeley** [comment]
Don't know why ```PROCESS_PROGRAM_LIKE_OTHER_ARGS``` was not defined by default, but now it is and the ```(command-line)``` returns the correct path when the program is started with doublequotes.
