### ISSUE TITLE
websites not working

### ISSUE THREAD

**Issue by dorfsmay** [gambit/gambit#383]
Gambit's websites that aren't working:

http://gambitscheme.org/
Goes into a 301 loop between gambitscheme.org and dynamo.iro.umontreal.ca
Note that this is the site documented as the official site on [wikipedia](https://en.wikipedia.org/wiki/Gambit_(scheme_implementation))

https://webmail.iro.umontreal.ca/mailman/listinfo/gambit-list
Supposed to be the site for the mailing list, from  http://dynamo.iro.umontreal.ca/wiki/index.php/How_to_contribute

http://www.iro.umontreal.ca/~gambit/bugzilla/
From http://dynamo.iro.umontreal.ca/wiki/index.php/Main_Page
"Note that the bugzilla bug tracker previously used (Gambit bugzilla bug tracker) will be phased out". Looks like it's been phased out already. Should the page be updated?

**Comment by feeley** [comment]
Should be back up now.
