### ISSUE TITLE
define-syntax complains about syntax-error

### ISSUE THREAD

**Issue by mjkarki** [gambit/gambit#384]
It seems that v4.9.3 broke the `define-syntax` support.

Here is an example:
````
$ gsi -:s
Gambit v4.9.3

> (define-syntax test
  (syntax-rules ()
    ((test expression)
     (display 'expression))))
*** ERROR -- Ill-formed special form: syntax-error
(##syntax-error %%%%tmp16)
````

I'm not competent enough to debug this myself, but I'm guessing that this commit might be the cause: [
`719181e`](https://github.com/gambit/gambit/commit/719181e89d17b64cf1d95f9c4d44e6bb0ce1b593)

With the previous commit there seems to be no issues.

**Comment by belmarca** [comment]
I also get this error.

**Comment by svenha** [comment]
The current git version does not have this issue anymore.

**Comment by mjkarki** [comment]
Finally got around to verify the fix. It seems that the source code found from the home page and the master branch both include the fix and `define-syntax` works as expected. Thank you! Closing the issue.
