### ISSUE TITLE
Link error: unresolved symbol on Windows

### ISSUE THREAD

**Issue by junjiemars** [gambit/gambit#391]
The steps I'd do:

1. host ```msvc``` environment via ```vcvarsall.bat```

2.  open ```mintty terminal``` , MinGW64

3. ```./configure --enable-single-host``` 

4. ```make``` 

``` sh
making all in include
make[1]: Entering directory 'D:/opt/open/gambit/include'
make[1]: Leaving directory 'D:/opt/open/gambit/include'
making all in lib
make[1]: Entering directory 'D:/opt/open/gambit/lib'
if [ -e ../.git ]; then git update-index --skip-worktree _kernel.c _system.c _num.c _std.c _eval.c _io.c _nonstd.c _thread.c _repl.c _gambit.c; fi
make[1]: Leaving directory 'D:/opt/open/gambit/lib'
making all in gsi
make[1]: Entering directory 'D:/opt/open/gambit/gsi'
if [ -e ../.git ]; then git update-index --skip-worktree _gsilib.c _gsi.c _gambitgsi.c _gsi_.c; fi
cl -D_WINDOWS -D_WIN32_WINNT=0x0600 -DUNICODE -D_UNICODE -D_ATL_XP_TARGETING -nologo -MT -D_CRT_SECURE_NO_DEPRECATE   -I"../include"  -Fe"gsi.exe"    _gsi.obj _gsi_.obj "../lib/libgambit.lib" Kernel32.Lib User32.Lib Gdi32.Lib WS2_32.Lib libgambitgsi.lib -link -subsystem:console,5.02 -entry:WinMainCRTStartup
libgambit.lib(_system.obj) : error LNK2019: unresolved external symbol ___CHARDOWNCASE referenced in function ___H___system
libgambit.lib(_std.obj) : error LNK2001: unresolved external symbol ___CHARDOWNCASE
libgambit.lib(_io.obj) : error LNK2001: unresolved external symbol ___CHARDOWNCASE
libgambit.lib(_std.obj) : error LNK2019: unresolved external symbol ___CHARALPHABETICP referenced in function ___H___std
libgambit.lib(_io.obj) : error LNK2001: unresolved external symbol ___CHARALPHABETICP
libgambit.lib(_std.obj) : error LNK2019: unresolved external symbol ___CHARNUMERICP referenced in function ___H___std
libgambit.lib(_io.obj) : error LNK2001: unresolved external symbol ___CHARNUMERICP
libgambit.lib(_std.obj) : error LNK2019: unresolved external symbol ___CHARWHITESPACEP referenced in function ___H___std
libgambit.lib(_std.obj) : error LNK2019: unresolved external symbol ___CHARUPPERCASEP referenced in function ___H___std
libgambit.lib(_std.obj) : error LNK2019: unresolved external symbol ___CHARLOWERCASEP referenced in function ___H___std
libgambit.lib(_std.obj) : error LNK2019: unresolved external symbol ___CHARUPCASE referenced in function ___H___std
libgambit.lib(_io.obj) : error LNK2001: unresolved external symbol ___CHARUPCASE
gsi.exe : fatal error LNK1120: 7 unresolved externals
make[1]: *** [makefile;182: gsi.exe] Error 2
make[1]: Leaving directory 'D:/opt/open/gambit/gsi'
make: *** [makefile;469: all-recursive] Error 1

```

The error message means 7 symbols are missing? and how to resolve it?

**Comment by junjiemars** [comment]
I try ```./configure --prefix=d:/opt/run CFLAGS=-D___USE_C_RTS_CHAR_OPERATIONS``` and got:

```sh
LNK2019: unresolved external symbol WinMain referenced in function "int __cdecl __scrt_common_main_seh(void)" (?__scrt_common_main_seh@@YAHXZ)
```

**Comment by junjiemars** [comment]
I'd found there are the macro  checking in ```include/gambit.h``` about ```___CHARUPCASE```:

```h
#ifdef ___USE_C_RTS_CHAR_OPERATIONS
#define ___CHARALPHABETICP(x)___EXT(___iswalpha)(___INT(x))
#define ___CHARNUMERICP(x)___EXT(___iswdigit)(___INT(x))
#define ___CHARWHITESPACEP(x)___EXT(___iswspace)(___INT(x))
#define ___CHARUPPERCASEP(x)___EXT(___iswupper)(___INT(x))
#define ___CHARLOWERCASEP(x)___EXT(___iswlower)(___INT(x))
#define ___CHARUPCASE(x)___CHR(___EXT(___towupper)(___INT(x)))
#define ___CHARDOWNCASE(x)___CHR(___EXT(___towlower)(___INT(x)))
#endif

```

So, I append ```-D___USE_C_RTS_CHAR_OPERATIONS``` to ```misc/vstudio.bat```
```bat
set COMP_GEN=%C_COMPILER% %FLAGS_COMMON% -c -I..\include
set COMP_LIB_MH=%COMP_GEN% %FLAGS_OPT% %DEFS_LIB% -D___LIBRARY -D___USE_C_RTS_CHAR_OPERATIONS
set COMP_LIB_PR_MH=%COMP_GEN% %FLAGS_OPT% %DEFS_LIB% -D___LIBRARY -D___PRIMAL -D___USE_C_RTS_CHAR_OPERATIONS
set COMP_LIB=%COMP_GEN% %FLAGS_OPT% %DEFS_LIB% %DEFS_SH% -D___LIBRARY -D___USE_C_RTS_CHAR_OPERATIONS
set COMP_LIB_PR=%COMP_GEN% %FLAGS_OPT% %DEFS_LIB% %DEFS_SH% -D___LIBRARY -D___PRIMAL -D___USE_C_RTS_CHAR_OPERATIONS
set COMP_LIB_PR_RTS=%COMP_GEN% %FLAGS_OPT_RTS% %DEFS_LIB% %DEFS_SH% -D___LIBRARY -D___PRIMAL -D___USE_C_RTS_CHAR_OPERATIONS
set COMP_APP=%COMP_GEN% %FLAGS_OPT% %DEFS_SH%

```

Finally, I'd resolved ```gsi.exe : fatal error LNK1120: 7 unresolved externals``` issue, but I think there are missing something in ```misc/vstudio.bat```.

**Comment by abdelq** [comment]
I would recommend you checkout to the v4.9.3 tag (`git checkout v4.9.3`) and trying to build again.

**Comment by junjiemars** [comment]
@abdelq your are right, v4.9.3 is OK.

**Comment by comalice** [comment]
I'm running into this issue cloning from master. I'm running Artix Linux (Arch with open RC).

**Comment by abdelq** [comment]
@comalice, the issue is related to bootstrapping and is going to disappear on the next release. However, I'm surprised that you are getting that on GNU/Linux. I'm on Arch and it compiles just fine. Did you really make a fresh clone?

**Comment by comalice** [comment]
I'm not sure what I did to get those errors. I re-cloned and everything appears to work now. That's mildly frustrating. I'd really like to know what caused the error.

**Comment by abdelq** [comment]
@comalice A `make bootclean` and a `make` would have probably solved it too.

**Comment by feeley** [comment]
The Gambit runtime library and compiler are written in Scheme and must be compiled by the Gambit compiler, in other words Gambit is bootstrapped with itself. As the system evolves, a feature of the runtime library may depend on a new feature of the Gambit compiler (in the specific case of this issue, the character class testing primitives `char-alphabetic?`, etc have evolved to support the latest Unicode standard, to comply with R7RS).  If you clone the Gambit repo and then do `./configure;make` the build process first creates a `boot` subdirectory and then builds in `boot` the Gambit compiler of the latest release and  uses that to build the Gambit compiler corresponding to the repo HEAD (the executable `gsc-boot` that is the current Gambit compiler used for bootstrap), and finally uses that to compile the whole Gambit system, including the Gambit runtime library and compiler.  A subsequent `make` will skip the bootstrap because it sees that a bootstrap has already been done.  Changes of the Gambit runtime library are more frequent than changes of the Gambit compiler, so very often a `make` will succeed using the existing `gsc-boot`.  When that fails the `gsc-boot` is probably too old and you can either `rm -rf boot gsc-boot;./configure;make` or start from scratch with a fresh clone of the Gambit repo (this is the most reliable way).
