### ISSUE TITLE
JavaScript: There is no `Gambit` Object

### ISSUE THREAD

**Issue by amirouche** [gambit/gambit#397]
While trying to make the JavaScript backend work in the browser (ff 67.0.3) I noticed that the generated code is missing a `Gambit` object. But all the function it rely on are in the compiled file under another name. So i created `postlude.js` file that looks like:

```javascript
$ cat postlude.js 
Gambit = {};
Gambit.stack = [];
Gambit.underflow = {};
Gambit.trampoline = g_trampoline;
Gambit.scm2js = g_scm2js;
Gambit.js2scm = g_js2scm;
Gambit.js2scm_call = g_js2scm_call;
Gambit.String = G_ScmString;
Gambit.Flonum = G_Flonum;
Gambit.Pair = G_Pair;
Gambit.Structure = G_Structure;
Gambit.heapify_cont = g_heapify_cont;
```

When I build the `linked_app.js` I add it before `app.js`.

See https://github.com/scheme-live/scheme-fuss/releases/tag/v0 or https://scheme-live.github.io/scheme-fuss/

**Comment by feeley** [comment]
Nice experiment!

The `Gambit` object is actually part of dead code and will go away soon.  It is part of the implementation of `js2scm` and `scm2js` that have been replaced by `host2scm` and `scm2host`.

**Comment by amirouche** [comment]
I tried to replace `g_scm2js` with `g_scm2host`, I noticed a typo in the definition of `g_scm2host`, here is the diff:

```diff
@@ -396,12 +396,13 @@ function g_scm2host(obj) {
   if (obj instanceof G_Pair) {
     var jsobj = {};
     var i = 0;
       while (obj instanceof G_Pair) {
       var elem = obj.car;
       if (elem instanceof G_Pair) {
-        obj[g_scm2host(elem.car)] = g_scm2host(elem.cdr);
+        jsobj[g_scm2host(elem.car)] = g_scm2host(elem.cdr);
       } else {
-        obj[i] = g_scm2host(elem);
+        jsobj[i] = g_scm2host(elem);
       }
       ++i;
       obj = obj.cdr;
```

I think there is typof around `obj` and `jsobj`...

**Comment by feeley** [comment]
Indeed! That part of scm2host converts an alist to an object and it isn't actually used anywhere, so it is rarely if ever tested. Will fix.
