### ISSUE TITLE
gsc isn't always called gsc

### ISSUE THREAD

**Issue by chopptimus** [gambit/gambit#398]
For instance on Arch it's called gambitc. Probably worth mentioning in the build dependencies or build sections in the guide.

**Comment by lassik** [comment]
Other Schemes that use three-letter command names have the same problem. Name clashes are unfortunately bound to happen eventually, and distros often decide who wins based on current popularity. In Gambit's case, `gsc` clashes with Ghostscript (interestingly, both Gambit and Ghostscript were first released in 1988).

I would like there to be a community-wide effort to pick standard long-form names for each Scheme implementation. I can do some legwork and talk to people in an attempt to organize it.

The Gambit package also goes by different names (e.g. on Debian it's `gambc`). These would also be nice to standardize.

**Comment by lassik** [comment]
Just to be clear, the short 3-4 letter names could continue exist, as would names aliased to more than one implementation such as `scheme`, but the long-form names would be something we could always rely on to be there.
