### ISSUE TITLE
gsi REPL banner colors

### ISSUE THREAD

**Issue by lassik** [gambit/gambit#401]
When `gsi` starts up, it prints a banner that says `Gambit v4.9.3`. This banner uses cyan for the background color, and the ANSI terminal "default" color for the foreground. I recommend changing it to explicitly use `color-white` instead of `default-color` since the combination of cyan and the default color is unpredictable and unreadable on some terminals (esp. with a translucent terminal window).

Patch (untested):

```
diff --git a/lib/_repl.scm b/lib/_repl.scm
index 520f207..abade90 100644
--- a/lib/_repl.scm
+++ b/lib/_repl.scm
@@ -2522,7 +2522,7 @@
 
        (case kind
          ((banner)
-          (make-text-attr style-bold   default-color color-cyan))
+          (make-text-attr style-bold   color-white color-cyan))
          ((input)
           (make-text-attr style-bold   default-color default-color))
          (else
```

**Comment by feeley** [comment]
This sounds reasonable, but I'd like to try it out on Windows first.

**Comment by lassik** [comment]
Tested the above patch and sent it as a pull request.

Here's a before and after screenshot:

![gambit-banner-colors-before-and-after](https://user-images.githubusercontent.com/2564245/63679398-e6887f00-c7f9-11e9-9d80-392b2f536aa3.png)

White on cyan is still not the most legible combination on all setups, but is much easier to read anyway.

**Comment by lassik** [comment]
The version number might be easier to read with some space on the sides, plus IMHO it looks more balanced.

![gambit-banner-with-extra-space-on-the-sides](https://user-images.githubusercontent.com/2564245/63681925-77158e00-c7ff-11e9-83e0-0837aa2f7b74.png)

**Comment by lassik** [comment]
From PR #407:

> On macOS with a white background Terminal, I get a faint white... which is not nice. Perhaps a "high brightness" version of the colors should be added.

That's funny, I also get that in Apple's Terminal app:

![gambit-gsi-macos-terminal-faint-white](https://user-images.githubusercontent.com/2564245/63704566-00df4e80-c834-11e9-9421-cafb35c94c34.png)

So that's not reliable either.

**Comment by lassik** [comment]
Works for me.

![gambit-a](https://user-images.githubusercontent.com/2564245/63838156-7e66a400-c985-11e9-8464-6b1d61151e23.png)

![gambit-b](https://user-images.githubusercontent.com/2564245/63838163-832b5800-c985-11e9-8e0d-7a59e4575cc2.png)

The first screenshot (from Apple's Terminal) is still a bit faint but definitely legible. It's really hard to find color combinations that look crisp everywhere.

**Comment by lassik** [comment]
![gambit-c](https://user-images.githubusercontent.com/2564245/63857023-9e10c300-c9ab-11e9-9f1a-f8688a04ad39.png)

![gambit-d](https://user-images.githubusercontent.com/2564245/63857021-9a7d3c00-c9ab-11e9-918e-c0d53c35bb40.png)

I like it :)
