### ISSUE TITLE
Cannot build gambit on macos

### ISSUE THREAD

**Issue by bentxt** [gambit/gambit#415]
Hi 

after running 

   ./configure
   make

Error:
../gsc-boot -:~~bin=../bin,~~lib=../lib,~~include=../include -f  -prelude "(##n
amespace(\"c#\"))(##include\"../lib/header.scm\")" -warnings -c _t-univ-2.scm
make[3]: *** [_t-univ-2.c] Segmentation fault: 11
make[2]: *** [boot-wip-compiler-gsc-gsc] Error 2
make[1]: *** [boot-wip-compiler] Error 2
make: *** [gsc-boot] Error 2

**Comment by feeley** [comment]
Please give some context.  Could you try to build Gambit from a fresh clone of the github repo as shown in the README?

**Comment by bentxt** [comment]
this is from a fresh clone

git rev-parse  HEAD
c766519e7e692aaf44c8d4562ea3902b92ac32e2

sw_vers
ProductName:    Mac OS X
ProductVersion: 10.15
BuildVersion:   19A602

**Comment by bentxt** [comment]
I just made another unsuccesfull attempt, here is the entire history of the commands taken from the readme:
```
git clone https://github.com/gambit/gambit.git
cd gambit
./configure        # --enable-single-host optional but recommended
make -j            # build runtime library, gsi and gsc
make modules       # compile the builtin modules (optional but recommended)
make check         # run self tests (optional but recommended)
make doc           # build the documentation
sudo make install  # install
```

Error
```
../gsc-boot -:~~bin=../bin,~~lib=../lib,~~include=../include -f  -prelude "(##namespace(\"c#\"))(##include\"../lib/header.scm\")" -warnings -c _t-univ-2.scm
make[3]: *** [_t-univ-2.c] Segmentation fault: 11
make[2]: *** [boot-wip-compiler-gsc-gsc] Error 2
make[1]: *** [boot-wip-compiler] Error 2
make: *** [gsc-boot] Error 2
```

Version:
git rev-parse HEAD
c766519e7e692aaf44c8d4562ea3902b92ac32e2

**Comment by feeley** [comment]
Between the `make -j` and `make modules` could you try:

**Comment by bentxt** [comment]
> Between the `make -j` and `make modules` could you try:

you mean 
make -j
make bootstrap
make bootclean 
make modules

**Comment by feeley** [comment]
Actually, where in the sequence of steps do you get the error?  I have the impression the first `make -j` gives the segfault.  If that's the case my suggestion is moot and the problem is probably that clang has a bug and you should try `brew install gcc@8` and use `./configure CC=gcc-8`.

**Comment by bentxt** [comment]
Unfortunately gcc@8 seems to be broken for the latest macos update.

**Comment by lassik** [comment]
With `brew install gcc` you currently get a `gcc-9` executable. I've been using that one to build Gambit on Mac.

**Comment by bentxt** [comment]
Yes, I've tried that, but gcc-9 doesn't work either

```
checking whether the C compiler works... no
configure: error: in `.../gambit.git':
configure: error: C compiler cannot create executables
```

**Comment by lassik** [comment]
Interesting. The `./configure` script should have created a `config.log` file in the same directory. Try searching for `checking whether the C compiler works` in that file. Does it shed any light on the cause of the problem?

**Comment by bentxt** [comment]
I'm not sure if that makes sense, but here is the questionable part of the config.log

configure:3279: result: /usr/local/bin/gcc-9
configure:3508: checking for C compiler version
configure:3517: /usr/local/bin/gcc-9 --version >&5
gcc-9 (Homebrew GCC 9.1.0) 9.1.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

configure:3528: $? = 0
configure:3517: /usr/local/bin/gcc-9 -v >&5
Using built-in specs.
COLLECT_GCC=/usr/local/bin/gcc-9
COLLECT_LTO_WRAPPER=/usr/local/Cellar/gcc/9.1.0/libexec/gcc/x86_64-apple-darwin18/9.1.0/lto-wrapper
Target: x86_64-apple-darwin18
Configured with: ../configure --build=x86_64-apple-darwin18 --prefix=/usr/local/Cellar/gcc/9.1.0 --libdir=/usr/local/Cellar/gcc/9.1.0/lib/gcc/9 --disable-nls --enable-checking=release --enable-languages=c,c++,objc,obj-c++,fortran --program-suffix=-9 --with-gmp=/usr/local/opt/gmp --with-mpfr=/usr/local/opt/mpfr --with-mpc=/usr/local/opt/libmpc --with-isl=/usr/local/opt/isl --with-system-zlib --with-pkgversion='Homebrew GCC 9.1.0' --with-bugurl=https://github.com/Homebrew/homebrew-core/issues --disable-multilib --with-native-system-header-dir=/usr/include --with-sysroot=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk
Thread model: posix
gcc version 9.1.0 (Homebrew GCC 9.1.0) 
configure:3528: $? = 0
configure:3517: /usr/local/bin/gcc-9 -V >&5
gcc-9: error: unrecognized command line option '-V'
gcc-9: fatal error: no input files
compilation terminated.
configure:3528: $? = 1
configure:3517: /usr/local/bin/gcc-9 -qversion >&5
gcc-9: error: unrecognized command line option '-qversion'; did you mean '--version'?
gcc-9: fatal error: no input files
compilation terminated.
configure:3528: $? = 1
configure:3548: checking whether the C compiler works
configure:3570: /usr/local/bin/gcc-9    conftest.c  >&5
ld: library not found for -lSystem
collect2: error: ld returned 1 exit status

**Comment by bentxt** [comment]
What's also strange, I try to build the latest release of gambit ("gambit-v4_9_3-devel"). Configuration and building works, but the resulting binaries don't work:

```
/gsc-script
fish: './gsc-script' terminated by signal SIGSEGV (Address boundary error)
```

**Comment by gambiteer** [comment]
I just want to point out that bentxt is building on the latest Mac OS, Catalina:
```
sw_vers
ProductName: Mac OS X
ProductVersion: 10.15
BuildVersion: 19A602
```
I built OK on Mojave (10.14), but that doesn't prove anything.

**Comment by jxy** [comment]
If you are getting segfault using clang from Xcode 11 on macOS Catalina?  You need to pass `-fno-stack-check`.

In the Xcode 11 Release Notes:
> Stack checking is on by default on all platforms to prevent memory corruptions. (25859140)

which brought a quite amount of segfaults lately.

**Comment by feeley** [comment]
I don't have Catalina installed so I can't reproduce this.  When on Mojave I try `./configure CC="gcc-8 -fstack-check"` I don't encounter the problem.

**Comment by lassik** [comment]
`ld: library not found for -lSystem` seems to be the cause of the problem with gcc-9 and Catalina

**Comment by bentxt** [comment]
just a quick note, I could build gambit with 
`
./configure  CC="gcc -fno-stack-check"`

**Comment by feeley** [comment]
Good.  It would be nice to figure out where the executable segfaults when `-fstack-check` is used.  So if you can, configure Gambit with `./configure --enable-debug` and run `gsc` under `lldb` and report back.

**Comment by bentxt** [comment]
In the latest git version I couldn't compile it with -fstack-check

```
./configure  CC="/usr/bin/gcc -fstack-check"
make -j 
```

Again the error:
```
../gsc-boot -:~~bin=../bin,~~lib=../lib,~~include=../include -f  -prelude "(##namespace(\"c#\"))(##include\"../lib/header.scm\")" -warnings -c _t-univ-2.scm
make[3]: *** [_t-univ-2.c] Segmentation fault: 11
make[2]: *** [boot-wip-compiler-gsc-gsc] Error 2
make[1]: *** [boot-wip-compiler] Error 2
make: *** [gsc-boot] Error 2
```

**Comment by bentxt** [comment]
> Good. It would be nice to figure out where the executable segfaults when `-fstack-check` is used. So if you can, configure Gambit with `./configure --enable-debug` and run `gsc` under `lldb` and report back.

The binaries in gambit-v4_9_3-devel built by default gcc are no longer segfaulting.

Maybe this had something to do with the update to Catalina and running xcode-select --install fixed those problems.

**Comment by feeley** [comment]
OK... let's consider this issue solved then...

**Comment by gambiteer** [comment]
Does this mean that git head now builds on Mac OS Catalina?

**Comment by bentxt** [comment]
I think this case was close a bit prematurely, because I just now finished my own "investigations" in the problem. 

Because the whole case is a bit long and a little bit messy (sorry my bad) I would like to first make a quick summary of the whole thing:

1. Initially I tried to compile the latest version of gambit on macos 'Catalina' with the default gcc compiler from Xcode. It didn't compile then and it still doesn't compile.

2. Then I tried to compile 'gambit-v4_9_3-devel' release. It compiled with the default Xcode gcc, but the resulting binaries segfaulted. 

3. Because of thes problems I try to install gcc (gcc-9) with 'brew install gcc'. First this failed also, but after reinstallation of Xcode Commandline Tools of my freshly updated 'Catalina'  I finally could install gcc from brew.

4. With this gcc-9 I can build and run the latest release 'gambit-v4_9_3-devel' and also the git clone with by defining this CC compiler, as in

Which means this with brew gcc works:
```
git clone https://github.com/gambit/gambit.git 
cd gambit
./configure CC=gcc-9 # gcc from brew
make -j 
```          
but this with Xcode gcc doesn't
```
git clone https://github.com/gambit/gambit.git 
cd gambit
./configure  # gcc from Xcode
make -j 
```

**Comment by abdelq** [comment]
@bentxt But your "Xcode gcc" is actually clang and not GNU's GCC...

**Comment by gambiteer** [comment]
I'm going to reopen this in case someone does fire up a debugger and find out why the resulting binaries segfault.

**Comment by bentxt** [comment]
in gambit-v4_9_3-devel
with /usr/bin/gcc -v
```
$  /usr/bin/gcc -v
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/4.2.1
Apple clang version 11.0.0 (clang-1100.0.33.8)
Target: x86_64-apple-darwin19.0.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

```
./configure --enable-debug CC=/usr/bin/gcc
make
```

Debug:

lldb gsc/gsc
(lldb) target create "gsc/gsc"
Current executable set to 'gsc/gsc' (x86_64).
(lldb) run
Process 98905 launched: '/Users/bkb/local/gambit/gambit-v4_9_3-devel/gsc/gsc' (x86_64)
Process 98905 stopped
* thread #1, queue = 'com.apple.main-thread', stop reason = signal SIGTTOU
    frame #0: 0x00007fff6c6a4aba libsystem_kernel.dylib`__ioctl + 10
libsystem_kernel.dylib`__ioctl:
->  0x7fff6c6a4aba <+10>: jae    0x7fff6c6a4ac4            ; <+20>
    0x7fff6c6a4abc <+12>: movq   %rax, %rdi
    0x7fff6c6a4abf <+15>: jmp    0x7fff6c6a4361            ; cerror
    0x7fff6c6a4ac4 <+20>: retq
Target 0: (gsc) stopped.

**Comment by feeley** [comment]
The SIGTTOU signal suggests that you are not running the latest Gambit.  The `gambit-v4_9_3-devel` suggests that you are building from the v4.9.3 release (from 9 months ago), unless you did a `git pull` to get the repo HEAD.  Are you sure you built from a clone of the github repo?

Note that you can avoid the SIGTTOU by doing `run -:d-` in lldb.

**Comment by bentxt** [comment]
a quick update on this problem, sorry but not much changed, because it is still not compiling with the default CC compiler. It is working with gcc-9 though.

This is from a fresh clone in an empty directory.


## This doesn't work
```
gcc -v
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/4.2.1
Apple clang version 11.0.0 (clang-1100.0.33.8)
Target: x86_64-apple-darwin19.0.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

```
./configure
make

gcc -Wno-unused -Wno-write-strings -Wdisabled-optimization -fwrapv -fno-strict-aliasing -fno-math-errno -fomit-frame-pointer -fPIC -fno-common    -I"../include"  -o "gsi"    _gsi.o _gsi_.o "../lib/libgambit.a"  libgambitgsi.a
if [ -e ../.git ]; then git update-index --skip-worktree _host.c _utils.c _source.c _parms.c _env.c _ptree1.c _ptree2.c _gvm.c _back.c _front.c _prims.c _assert.c _asm.c _x86.c _arm.c _riscv.c _codegen.c _t-univ-1.c _t-univ-2.c _t-univ-3.c _t-univ-4.c _t-cpu-abstract-machine.c _t-cpu-primitives.c _t-cpu-object-desc.c _t-cpu-utils.c _t-cpu-backend-x86.c _t-cpu-backend-arm.c _t-cpu-backend-riscv.c _t-cpu.c _t-c-1.c _t-c-2.c _t-c-3.c _gsclib.c _gsc.c _gambitgsc.c _gsc_.c; fi
../gsc-boot -:~~bin=../bin,~~lib=../lib,~~include=../include -f  -prelude "(##namespace(\"c#\"))(##include\"../lib/header.scm\")" -warnings -c _t-univ-2.scm
make[3]: *** [_t-univ-2.c] Segmentation fault: 11
make[2]: *** [boot-wip-compiler-gsc-gsc] Error 2
make[1]: *** [boot-wip-compiler] Error 2
make: *** [gsc-boot] Error 2
```



## This works

```
gcc-9 -v
Using built-in specs.
COLLECT_GCC=gcc-9
COLLECT_LTO_WRAPPER=/usr/local/Cellar/gcc/9.2.0_1/libexec/gcc/x86_64-apple-darwin19/9.2.0/lto-wrapper
Target: x86_64-apple-darwin19
Configured with: ../configure --build=x86_64-apple-darwin19 --prefix=/usr/local/Cellar/gcc/9.2.0_1 --libdir=/usr/local/Cellar/gcc/9.2.0_1/lib/gcc/9 --disable-nls --enable-checking=release --enable-languages=c,c++,objc,obj-c++,fortran --program-suffix=-9 --with-gmp=/usr/local/opt/gmp --with-mpfr=/usr/local/opt/mpfr --with-mpc=/usr/local/opt/libmpc --with-isl=/usr/local/opt/isl --with-system-zlib --with-pkgversion='Homebrew GCC 9.2.0_1' --with-bugurl=https://github.com/Homebrew/homebrew-core/issues --disable-multilib --with-native-system-header-dir=/usr/include --with-sysroot=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk
Thread model: posix
gcc version 9.2.0 (Homebrew GCC 9.2.0_1)

```

```
./configure  CC=gcc-9
make
```

**Comment by feeley** [comment]
After installing Catalina and Xcode 11 I managed to reproduce the error.  The lldb debugger indicates that the problem is an unaligned stack pointer.  After a failed `./configure;make` I did:

```
% cd boot
% lldb ./gsc-boot
(lldb) target create "./gsc-boot"
Current executable set to './gsc-boot' (x86_64).
(lldb) run
run
Process 63972 launched: '/Users/feeley/catalina/gambit/boot/gsc-boot' (x86_64)
Process 63972 stopped
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=EXC_I386_GPFLT)
    frame #0: 0x00007fff6fafe386 libdyld.dylib`stack_not_16_byte_aligned_error
libdyld.dylib`stack_not_16_byte_aligned_error:
->  0x7fff6fafe386 <+0>: movdqa %xmm0, (%rsp)
    0x7fff6fafe38b <+5>: int3   
    0x7fff6fafe38c <+6>: nop    
    0x7fff6fafe38d <+7>: nop    
Target 0: (gsc-boot) stopped.
```

This is probably a bug in the stack handling of Apple clang version 11.0.0 and specifically how it handles the `-fomit-frame-pointer` option.  I suspect it is related to `goto*`.  When I build manually using `./configure --enable-debug` in the `boot` subdirectory the problem goes away.

Unfortunately, the debug configure setting of the main `./configure` is not propagated to the `./configure` of the `boot` subdirectory.  I'll see if I can change that to have a way to circumvent such problems in the future.  In addition, I'll see if this version of clang can be detected so that the `-fomit-frame-pointer` can be disabled for that version (that clang option worked fine in the past).

**Comment by lassik** [comment]
FWIW, Catalina support is planned for Cirrus CI in early December: https://github.com/cirruslabs/osx-images/issues/18

**Comment by feeley** [comment]
I have added an automatic propagation of the debug related configure options to the bootstrap configure, so to circumvent the problem with Clang 11.0.0 on macOS you will have to build Gambit like this:

```
% ./configure --enable-debug     # this is for the side-effect of building gsc-boot without -fomit-frame-pointer
% make
% ./configure --enable-single-host  # use whatever flags you want... at this step the configure script knows to disable -fomit-frame-pointer on clang 11.0.0
% make
```

**Comment by lassik** [comment]
Can someone with access to Catalina confirm whether `brew install gcc` and then `./configure CC=gcc-9` can successfully build Gambit there?

**Comment by feeley** [comment]
Just tried `brew install gcc@9` and yes it works (and the execution is about 2x faster than when compiled with clang).

```
% gcc-9 -v
Using built-in specs.
COLLECT_GCC=gcc-9
COLLECT_LTO_WRAPPER=/usr/local/Cellar/gcc/9.2.0_1/libexec/gcc/x86_64-apple-darwin19/9.2.0/lto-wrapper
Target: x86_64-apple-darwin19
Configured with: ../configure --build=x86_64-apple-darwin19 --prefix=/usr/local/Cellar/gcc/9.2.0_1 --libdir=/usr/local/Cellar/gcc/9.2.0_1/lib/gcc/9 --disable-nls --enable-checking=release --enable-languages=c,c++,objc,obj-c++,fortran --program-suffix=-9 --with-gmp=/usr/local/opt/gmp --with-mpfr=/usr/local/opt/mpfr --with-mpc=/usr/local/opt/libmpc --with-isl=/usr/local/opt/isl --with-system-zlib --with-pkgversion='Homebrew GCC 9.2.0_1' --with-bugurl=https://github.com/Homebrew/homebrew-core/issues --disable-multilib --with-native-system-header-dir=/usr/include --with-sysroot=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk
Thread model: posix
gcc version 9.2.0 (Homebrew GCC 9.2.0_1)
```

**Comment by lassik** [comment]
Thanks!
