### ISSUE TITLE
No way to specify encoding with (load ...) or (include ...)

### ISSUE THREAD

**Issue by Sunlighter** [gambit/gambit#418]
I'm trying to load a UTF-8 Scheme source file with katakana in it, and it doesn't work. I tried it both with and without a byte-order mark. (I'm using Amazon Linux 2.)

If I specify `-:t8` when I start the interpreter, I can paste the file into Gambit in the console, and that works. I can do `(symbol? 'ム)` and it returns `#t`.

`open-input-file` allows a `char-encoding:` to be specified, which can be set to `UTF-8`, but there appears not to be a comparable option for `load` or `include`, and there needs to be.

**Comment by feeley** [comment]
You need to use `-:f8` or `-:fU`.  The `-:t8` only applies to terminals.

**Comment by Sunlighter** [comment]
Looks like `-:f8,t8` does what I want. (I thought I had searched the manual extensively, but I didn't see this. I did not know about `-:h` either). Sorry for missing it, and thank you for your help!
