### ISSUE TITLE
Problem with a library function in the Js backend

### ISSUE THREAD

**Issue by bentxt** [gambit/gambit#419]
Hi,
I try to run the example for Js backend from 
https://mailman.iro.umontreal.ca/pipermail/gambit-list/2019-July/009103.html

All the code compiles but I get a runtime error from node

```
gambit-test/linked_app.js:1066
    return g_peps["##append"]();
                             ^
TypeError: g_peps.##append is not a function
```

I guess it has something to do with the name 'append'? That this name cannot be overwritten in a local library?

Regards Ben

PS. Because this problem first occurred in the context of the example on the mailing-list, I initially reported the problem to that list. Sorry for the unnecessary duplication. Here for reference the link to the post: https://mailman.iro.umontreal.ca/pipermail/gambit-list/2019-October/009209.html

**Comment by feeley** [comment]
Please try defining the procedure `app` instead of `append`, and if that works I will look into why it is mapping `append` to `##append`.

**Comment by bentxt** [comment]
> Please try defining the procedure `app` instead of `append`
yes, I can confirm that this change "solves" the problem

**Comment by feeley** [comment]
The problem is due to the "incorrect" declarations at the top of the files app.scm and lib.scm.  The declarations should be:

```
(declare (standard-bindings) (extended-bindings) (not safe) (not run-time-bindings))
(declare (not standard-bindings append for-each))
```

The second line is important because the append and for-each global variables don't have the standard bindings provided by the Gambit runtime library.  Previously the second declaration was not needed because the compiler did not optimize calls to append and for-each, but now the compiler converts `(append ...)` to `(##append ...)` when append has the standard bindings and `(not safe)` is also declared (in this case, calling `##append` avoids the type checks on the parameters).  So alternatively you could remove the `(not safe)` declaration.

**Comment by bentxt** [comment]
sorry to bother again, but I try this with the latest gsc and it doesnt work:

Error from node: 

`TypeError: pc is not a function`

cat app.scm
```
;; file: app.scm

(declare (standard-bindings) (extended-bindings) (not safe) (not run-time-bindings))
(declare (not standard-bindings append for-each))

(println ">>> app.scm")

(define (fib n) (if (fx< n 2) n (fx+ (fib (fx- n 1)) (fib (fx- n 2)))))

 (for-each
  (lambda (x)
    (println (fib x))))
```

cat lib.scm
```
;; file: lib.scm

(declare (standard-bindings) (extended-bindings) (not safe) (not run-time-bindings))
(declare (not standard-bindings append for-each))

(println ">>> lib.scm")

(define (for-each f lst)
  (if (pair? lst)
      (begin
        (f (car lst))
        (for-each f (cdr lst)))))

(define (append lst1 lst2)
  (if (pair? lst1)
      (cons (car lst1) (append (cdr lst1) lst2))
      lst2))

(define (current-milliseconds)
  (##inline-host-expression "Date.now()"))

(define (js-alert obj)
  (##inline-host-statement "alert(g_scm2js(@1@));" obj))

(app#) ;; execute app.scm module
```

Error:
```
universal-backend/linked_app.js:336
    pc = pc();
         ^

TypeError: pc is not a function
    at g_trampoline (universal-backend/linked_app.js:336:10)
    at g_module_register (universal-backend/linked_app.js:393:9)
    at Object.<anonymous> (universal-backend/linked_app.js:1099:1)
    at Module._compile (internal/modules/cjs/loader.js:774:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
    at Module.load (internal/modules/cjs/loader.js:641:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:837:10)
    at internal/main/run_main_module.js:17:11
make: *** [run] Error 1

```
