### ISSUE TITLE
JavaScript backend: support syntax-rules

### ISSUE THREAD

**Issue by amirouche** [gambit/gambit#423]
At least `(scheme mapping)` (SRFI-146) requires `syntax-rules`, see https://github.com/scheme-requests-for-implementation/srfi-146/blob/master/nieper/rbtree.scm#L146

**Comment by feeley** [comment]
Gambit has `syntax-rules` builtin:

```
> (define-syntax thunk (syntax-rules () ((thunk body) (lambda () body))))
> (with-output-to-file "foo" (thunk (display "hello\n")))
```

There is also a carefully tuned and fast implementation of red-black trees in `lib/_thread#.scm`.  It should probably be moved out of there to its own module now that the Gambit module system is in place.

**Comment by lassik** [comment]
BTW does Gambit's syntax-rules implementation support SRFI 46 tail patterns?

**Comment by feeley** [comment]
It doesn't support the SRFI 46 extension.

**Comment by lassik** [comment]
If my reading is correct, tail patterns are a standard feature of R7RS syntax-rules. From page 23: ```
(〈pattern〉...〈pattern〉 〈ellipsis〉 〈pattern〉...)
#(〈pattern〉...〈pattern〉 〈ellipsis〉 〈pattern〉...)
```

It's true that they are not in R5RS

**Comment by amirouche** [comment]
Indeed, I just pulled master and got it working:

```sh
amirouche@ubujan19:~/src/scheme/live/fuss$ cat Makefile 
help: ## This help.
	@awk 'BEGIN {FS = ":.*?## "} /^[a-zA-Z_-]+:.*?## / {printf "\033[36m%-30s\033[0m %s\n", $$1, $$2}' $(MAKEFILE_LIST) | sort

gambit: ## Compile gambit
	cd submodules/gambit/ && ./configure
	cd submodules/gambit/ && make -j4

gambit.js: gambit ## Prepare JavaScript backend
	cd submodules/gambit/lib && make -j4 _gambit.js

amirouche@ubujan19:~/src/scheme/live/fuss$ sh gambit-to-javascript.sh app.scm 
+ ./submodules/gambit/gsc/gsc -:=./submodules/gambit/ -target js -exe app.scm
amirouche@ubujan19:~/src/scheme/live/fuss$ node app
42
hello syntax-rules
```

**Comment by amirouche** [comment]
@lassik you can close this issue, if you have no more questions related to this one :+1:

**Comment by amirouche** [comment]
> There is also a carefully tuned and fast implementation of red-black trees in lib/_thread#.scm. It should probably be moved out of there to its own module now that the Gambit module system is in place.

Ok, that is better that what I was looking for :+1: This another case where it is better to ask than walk away...

FWIW, what is the status of `syntax-case`?

I just tried the following:

```scheme
amirouche@ubujan19:~/src/scheme/live/fuss$ cat app.scm 
(println 42)

(define-syntax thunk
  (syntax-rules ()
                       ((thunk body) (lambda () body))))

((thunk (println "hello syntax-rules")))

(define-syntax (while stx)
  (define subs (syntax->list stx))
  (datum->syntax
   stx
   `(let loop ()
      (when ,(cadr subs)
        ,@(cddr subs)
        (loop)))
   stx))

(while #t
  (println "while..."))
amirouche@ubujan19:~/src/scheme/live/fuss$ sh gambit-to-javascript.sh app.scm 
+ ./submodules/gambit/gsc/gsc -:=./submodules/gambit/ -target js -exe app.scm
*** ERROR IN "/home/amirouche/src/scheme/live/fuss/app.scm"@9.1 -- Ill-formed special form: define-syntax

```

**Comment by amirouche** [comment]
> syntax-case

I do not need it yet. And it belongs to another issue.
