### ISSUE TITLE
apropos procedure

### ISSUE THREAD

**Issue by lassik** [gambit/gambit#425]
Can we add `apropos` and `apropos-list` procedures as standard to `gsi`? Precedent: Common Lisp (http://www.lispworks.com/documentation/HyperSpec/Body/f_apropo.htm).

I can try making a PR using `(##symbol-table)` if you tell me which file it should go in, as well as which built-in procedures to use for `string-contains?` and to sort the results list.

**Comment by feeley** [comment]
This is debugging related, so how about a REPL command instead?  Like `,(a foo)`.

**Comment by lassik** [comment]
Works just as well.

The advantage of ordinary procedures is that they work the same way in different implementations, whereas most of them don't have the `,(foo ...)` syntax.  I have a pre-SRFI about some REPL commands useful for debugging (I won't submit it for a while since people would like to keep SRFI email traffic at a reasonable level) that is based mostly on the functions in Common Lisp. It doesn't specify many details about the commands, but uses the same names as CL as far as reasonable.

**Comment by feeley** [comment]
Did you check which other Schemes have `apropos`?

**Comment by lassik** [comment]
Chez and MIT have it accessible from the REPL by default. I don't know of any other ones.

**Comment by lassik** [comment]
Gauche and Guile too.

**Comment by feeley** [comment]
You had me at "Chez"...

**Comment by lassik** [comment]
Emacs, used by most Unix Lispers, also has an `apropos` command so it's quite well known :)

**Comment by lassik** [comment]
What's the best way to sort a list and do `(string-contains? a b)` using gsi's built-in procedures?

**Comment by feeley** [comment]
I have an idea for apropos, so give me some time to experiment.

**Comment by lassik** [comment]
Sure. I'll let you implement it and I'll work on something else :)

I find it nice if it accepts either a string or a symbol as the argument, since I can never remember which one it should be. Maybe matching should be case-insensitive.

Bonus points if it can show which library/namespace everything has been imported from.

**Comment by lassik** [comment]
Chibi-Scheme can search for identifiers in un-imported libraries if you try to use something that is not defined. I think they just added Levenshtein matching to it. There should probably be separate apropos commands for imported and not-yet-imported identifiers, but I don't know of any implementations that has that yet.

**Comment by feeley** [comment]
One problem is that the universal backend represents the symbol table differently.  So for now I will implement something C backend specific.

**Comment by lassik** [comment]
(Initial implementation by @feeley in PR #429, pushed to master)

**Comment by lassik** [comment]
Tested the patch, looks good!

It might be nice to have a symbol table fold as part of Gambit's "public" API. But not sure about the precise semantics. Does the universal backend complicate implementing it.

Common Lisp has a standard `apropos-list` function that returns the apropos results as a list.

**Comment by lassik** [comment]
I've been using the `apropos` procedure a lot ever since you pushed it into master, and it has worked perfectly for my needs (and been a huge help when exploring Gambit's features). As far as I'm concerned, this issue is solved :) Thanks a lot for this functionality.

**Comment by feeley** [comment]
Great!
