### ISSUE TITLE
Possible interpreter bug with `let` variable

### ISSUE THREAD

**Issue by lassik** [gambit/gambit#459]
With gambit commit `v4.9.0-1067-gd60fdeb1` and this script `intbug.scm`:

```
(import (srfi 132))

(define (writeln x) (write x) (newline))

(define v (vector 8 22 19 19 13 9 21 13 3 23))
(writeln v)
(vector-separate! < v 3 2)
(writeln v)
(newline)

(let ((v (vector 8 22 19 19 13 9 21 13 3 23)))
  (writeln v)
  (vector-separate! < v 3 2)
  (writeln v)
  (newline))

(define v (vector 8 22 19 19 13 9 21 13 3 23))
(writeln v)
(vector-separate! < v 3 2)
(writeln v)
(newline)

(let ((v (vector 8 22 19 19 13 9 21 13 3 23)))
  (writeln v)
  (vector-separate! < v 3 2)
  (writeln v)
  (newline))
```

`gsi intbug.scm` outputs:

```
#(8 22 19 19 13 9 21 13 3 23)
#(8 22 9 3 13 13 19 19 21 23)

#(8 22 19 19 13 9 21 13 3 23)
2

#(8 22 19 19 13 9 21 13 3 23)
#(8 22 9 3 13 13 19 19 21 23)

#(8 22 19 19 13 9 21 13 3 23)
2
```

Whereas `rm -f intbug.o1 && gsc intbug.scm && gsi intbug.o1` produces:

```
*** WARNING -- Variable "srfi/132#vector-separate!" used in module "intbug" is undefined
#(8 22 19 19 13 9 21 13 3 23)
#(8 22 9 3 13 13 19 19 21 23)

#(8 22 19 19 13 9 21 13 3 23)
#(8 22 9 3 13 13 19 19 21 23)

#(8 22 19 19 13 9 21 13 3 23)
#(8 22 9 3 13 13 19 19 21 23)

#(8 22 19 19 13 9 21 13 3 23)
#(8 22 9 3 13 13 19 19 21 23)
```

So it looks like the interpreter overwrites the value of the `v` variable, whereas the compiler produces the correct result.

**Comment by lassik** [comment]
(The file repeats the same pair of tests just to show that the problem persists with subsequent runs.)

**Comment by lassik** [comment]
`vector-separate!` is an ordinary procedure implemented in Scheme, not a macro or an FFI function, so it shouldn't be able to touch `v` which is outside its lexical context.

**Comment by feeley** [comment]
Problem was an improper bound in the definition of vector-copy! in srfi/132

**Comment by lassik** [comment]
Thank you for the quick turnaround once again!

However, it would seem that there's something else going on as well. `vector-copy!` is implemented in terms of `subvector-move!`, so even if the definition of `vector-copy!` was incorrect, `subvector-move!` should have guarded against being given out-of-bounds indices.

As far as I can tell, in the above interpreter run with `(let ...)` the local variable `v` is first assigned a vector, which is then assigned the fixnum `2` by `vector-separate!`. But since `vector-separate!` is an ordinary procedure it should not be able to re-assign any variables in the caller's lexical environment even if it has been implemented incorrectly.

**Comment by feeley** [comment]
The "other thing going on" is that the file 132.scm has this inclusion close to the top:

```
(##include "~~lib/_prim#.scm")
```

What this does is map many primitive procedures to their unsafe variant, i.e. `fx+` mapped to `##fx+`, `subvector-move!` to `##subvector-move!`, etc  This is more or less like a combination of importing `gambit` and declaring `(not safe)`.  If that line is replaced by:

```
(##include "~~lib/gambit#.scm")
```

and the srfi 132 code is reverted to the previous state with the error in `r7rs-vector-copy!` then the following error message appears:

```
% gsi/gsi -:=. intbug.scm
#(8 22 19 19 13 9 21 13 3 23)
*** ERROR IN #<procedure #2>, "lib/srfi/132/select.scm"@94.16 -- (Argument 3) Out of range
(subvector-move! #(9 3) 0 10 #(8 22 19 19 13 9 21 13 3 23) 2)
```

So the problem is not the interpreter, but rather the use of unsafe code (that probably corrupted the heap or stack).

**Comment by lassik** [comment]
Ah, so the unsafe variant of `subvector-move!` was imported. Makes sense!
