### ISSUE TITLE
read-u8 cannot read piped string on Manjaro

### ISSUE THREAD

**Issue by omelancon** [gambit/gambit#469]
Code snippet to reproduce:  

```
(tprint (read-u8))
```

Which I run by piping some input to it

```
echo "a" | gsi test.scm
```

The program does not terminate and gets stuck with no output

```
echo "a" | strace gsi test.scm
```

When using `strace`, I see this line spammed to my terminal

```
ioctl(0, TCGETS, 0xffcbe7b8)            = -1 ENOTTY (Inappropriate ioctl for device)
```

### System info

Gambit version

```
4.9.3
```

System information from `uname -a`

```
Linux 4.19.69-1-MANJARO #1 SMP PREEMPT Thu Aug 29 08:51:46 UTC 2019 x86_64 GNU/Linux`
```
Bash version

```
5.0.9(1)-release
```

**Comment by feeley** [comment]
I installed Manjaro on VirtualBox and could not reproduce the problem.

Linux Manjaro 5.4.6-2-MANJARO
bash 5.0.11(1)-release
the "tty" command gives /dev/pts/0 and stty gives
speed 38400 baud; line = 0;
-brkint -imaxbel iutf8

Could you check that your setup gives similar results?

The problem might also be the terminal emulator.  Are you using something out of the ordinary?

**Comment by omelancon** [comment]
I had installed Gambit from arch `pacman`, which was not quite up-to-date with `gambit/gambit`. The problem was solved by cloning the latest commit.
