### ISSUE TITLE
Re-exporting identifiers from the (gambit) library

### ISSUE THREAD

**Issue by lassik** [gambit/gambit#474]
How do you use `(only ...)` or `(rename ...)` to get things from the `(gambit)` library (i.e. `##` namespace)? E.g. these currently cause an error:

```scheme
(define-library (foo)
  (export random-integer)
  (import (only (gambit) random-integer)))

(define-library (bar)
  (export xx)
  (import (rename (gambit) random-integer xx)))
```

The import parser is in `lib/_define-library/define-library-expand.scm`; as far as I can tell, it fails to parse these because the library name `(gambit)` is a list with only one element. Library names with more than one element like `(scheme base)` work fine.

**Comment by feeley** [comment]
I will look into this.  Allowing reexports of the Gambit runtime system primitives is definitely the way to go because then the compiler will be able to optimize calls to these primitives (constant folding, inlining, specialization, etc).

**Comment by feeley** [comment]
Duh! the problem is that there's no `gambit.sld` file... in other words `gambit` is not an R7RS library.  So this should work when there's also an R7RS `gambit` library (which should be the case for many reasons).  Currently there's only a primitive module named `gambit`.

**Comment by lassik** [comment]
`(import (gambit))` currently works anyway. Does this imply that `import` can import a primitive module just as well as a R7RS library?

**Comment by lassik** [comment]
> Allowing reexports of the Gambit runtime system primitives is definitely the way to go because then the compiler will be able to optimize calls to these primitives (constant folding, inlining, specialization, etc).

Yeah, that would probably be the best way to provide SRFI 27 (Sources of Random Bits) as well as most of the bitwise procedures and as many hash-table ones as we can.

**Comment by feeley** [comment]
Sorry but reexporting an imported identifier is not currently supported.  I will see what can be done to fix this.

**Comment by lassik** [comment]
No problem. For the SRFIs that would benefit from re-exporting identifiers, we can instead use shim procedures for the time being. Once re-exporting is supported we can then convert those SRFIs to take advantage of it.

**Comment by feeley** [comment]
Reexporting imported bindings is now possible.  For SRFI 151, something along these lines should work:

```
(define-library (srfi 151)
  (export bitwise-and
          bitwise-ior
          bitwise-xor
          bitwise-not
          bits->list
          list->bits
          ...
          )
  (import (gambit))
  (begin
    (define (bits->list x) ...)
    (define (list->bits x) ...)))
```

Because of the `(import (gambit))` the binding for `bitwise-and` comes from the empty namespace and the binding for `bits->list` comes from the `srfi/151#` namespace (the default namespace of the `(srfi 151)` library).

By the way I went ahead and implemented SRFI 27 which was low hanging fruit...

**Comment by alvatar** [comment]
🍾 !!

**Comment by lassik** [comment]
Awesome, thanks a lot! I had to delete `boot` and `gsc-boot` and re-run `./configure`, but it works:

```scheme
(define-library (randtest)
  (import (srfi 27) (scheme base) (scheme write))
  (begin (random-source-randomize! default-random-source)
         (write (map (lambda (_) (random-integer 100))
                     (##iota 30)))
         (newline)))
```
