### ISSUE TITLE
test failure on ppc64le

### ISSUE THREAD

**Issue by jxy** [gambit/gambit#490]
```
------------ TEST 5 (compiler generating C code)
rm -f mix.c
../gsc/gsc -:~~bin=../bin,~~lib=../lib,~~include=../include -f -warnings -c -nb-gvm-regs 5 -nb-arg-regs 3 mix.scm
diff test5.ok mix.c
3419c3419
< ___DEF_SUB_FLO(___X248,-0x1L,-0x1L)
---
> ___DEF_SUB_FLO(___X248,0x7fffffffL,-0x1L)
```

All other tests passed except for this one.  Do I need to worry about this?

**Comment by gambiteer** [comment]
It appears that `___X248` is encoding a Not-a-Number (NaN) in IEEE arithmetic.
In `test5.ok` (probably generated on x86-64) this NaN has a the sign bit set; on ppc64le, the NaN has the sign bit cleared.
I don't believe that this matters, at least according to https://en.wikipedia.org/wiki/NaN#Encoding,

**Comment by gambiteer** [comment]
I’m going to close this, I don’t think this is a problem, but I don’t see how to avoid it either.

**Comment by jxy** [comment]
Sure.  All of my own tests pass too.

**Comment by gambiteer** [comment]
Just as a note, the same thing shows up on a Raspberry Pi:
```
diff test5.ok mix.c
3419c3419
< ___DEF_SUB_FLO(___X248,-0x1L,-0x1L)
---
> ___DEF_SUB_FLO(___X248,0x7fffffffL,-0x1L)
```
