### ISSUE TITLE
Gambit mailing list URL seems broken

### ISSUE THREAD

**Issue by pclouds** [gambit/gambit#495]
From the main page http://gambitscheme.org/wiki/index.php/Main_Page the Mailing list link points to https://webmail.iro.umontreal.ca/mailman/listinfo/gambit-list which seems dead. Googling reveals that https://mailman.iro.umontreal.ca/cgi-bin/mailman/listinfo/gambit-list works. Maybe we could update and point to that (if it's the right one)?

**Comment by adam-7** [comment]
+1

**Comment by lassik** [comment]
Current links on the page:

```HTML
<a href="https://mailman.iro.umontreal.ca/cgi-bin/mailman/listinfo/gambit-list">Mailing-list</a>

<a href="http://mailman.iro.umontreal.ca/pipermail/gambit-list/">Mailing-list archive</a>
```

These seem to be working fine.

**Comment by lassik** [comment]
Presumably the mailing list service was migrated from `webmail.iro.umontreal.ca` to `mailman.iro.umontreal.ca` by the university IT department.

**Comment by lassik** [comment]
The shorter URL `https://mailman.iro.umontreal.ca/mailman/listinfo/gambit-list` without the `cgi-bin` also works. I had got that from somewhere.

**Comment by pclouds** [comment]
Great, closing.

**Comment by bheesham** [comment]
Triage: I believe this ticket can be closed. The links referred to in the ticket were fixed. As an additional pass the links on the [Gambit Scheme Community page](http://gambitscheme.org/community/) are working as well.
