### ISSUE TITLE
#T and #F are invalid lexical syntax in Gambit

### ISSUE THREAD

**Issue by johnwcowan** [gambit/gambit#505]
Gambit should accept #T and #F as an alternative spelling of #t and #f.  The capital forms were definitely valid in R5RS sub silentio.  R6RS explicitly says that boolean literals are case-insensitive, as does R7RS.  Most major case-sensitive Schemes accept them.  And it's a trivial change.

**Comment by abdelq** [comment]
Not sure what version you have, but it's supported at least since `4.9.1`.

**Comment by gambiteer** [comment]
It Works For Me, so I suppose it should work for everyone.  Closing.
