### ISSUE TITLE
01-fixnum/fxeqv.scm never terminates with Javascript back end.

### ISSUE THREAD

**Issue by gambiteer** [gambit/gambit#513]
I don't know what's going on, I killed this test after >5 minutes execution time.

This is with `node-v12.16.1` that  I built myself, and 8.10.0 that's shipped with Ubuntu 18.04.

Things work fine on Mac OS Catalina with  `node-v12.16.1` .

Advice on debugging?

**Comment by feeley** [comment]
You need to `make bootstrap` to get an up to date `gsc-boot` and then `make bootclean;make` to compile the Gambit runtime system with a `gsc-boot` that knows about `##fxeqv` (and others that were implemented recently)

**Comment by feeley** [comment]
The reason is the way the `##fxeqv` procedure is implemented in the runtime system (in `lib/_num.scm`):

```
(define-prim-nary (##fxeqv x y)
  -1
  x
  (##fxeqv x y)  ;; problem is here
  macro-no-force
  macro-no-check)
```

The `(##fxeqv x y)` will be an actual procedure call when the backend does not define `##fxeqv` as an "inlinable" primitive.  So this call will be an infinite recursion.
