### ISSUE TITLE
Auto-detect Gambit installation directory based on executable filename?

### ISSUE THREAD

**Issue by lassik** [gambit/gambit#569]
From PR #568:

> * Produce usable artifacts for all platforms that can be downloaded for testing purposes

This would be very useful indeed. Gambit hardcodes the installation directory into its executable. The directory can be overridden using a command line option:

```
$ gsi -:help 2>&1 | grep -A 1 -- ~~
  ~~NAME=DIR         override Gambit installation directory ~~NAME where NAME
                     can be the special "bin" and "lib", or empty, or any id
```

but it would be nice to set a useful default in the CI artifacts so `-:~~` doesn't need to be set separately each time when running Gambit.

We talked earlier about CI build artifacts with @feeley. The conversation starts at comment https://github.com/udem-dlteam/libs/issues/4#issuecomment-549296234 but we didn't come up with an ideal installation directory to use for the artifacts.

It only now occurred to me that it's possible for an executable to find its own filename on many OSes. Could Gambit optionally support finding its installation directory relative to the executable filename? That would probably be easiest for CI artifacts.

(Ping @feeley @daviwil @FredericHamel)

**Comment by lassik** [comment]
For example, if `gsi` is run as `~/gambit/05060cf/bin/gsi` then `gsi` would deduce that the the installation directory is `~/gambit/05060cf`. Any other directory could be used as well. E.g. `/tmp/Gambit-master/` or whatever else. This would also mean that the directory can be completely different on the CI server and on people's personal computers. That extra flexibility would be nice.

**Comment by lassik** [comment]
If runtime auto-detection is supported, it should still be possible to set `./configure --prefix=...` to a particular directory at build time and there's `--enable-multiple-versions`.

The auto-detection should probably be enabled via a new configure flag.

**Comment by daviwil** [comment]
I would very much appreciate this improvement because I am currently using a CI-built Gambit on CI for other projects and I have to make sure to specify `~~bin`, etc everywhere I invoke `gsc` or `gsi`.  I'm actually dealing with a problem with this very issue today because it seems `~~bin` isn't being propagated when building imported modules that need compilation, but that's a separate issue :)

I agree with your suggestion that Gambit should probably try to resolve the path from the relative path to the executable.

**Comment by lassik** [comment]
Gambit is meant to be extremely portable, and the OS APIs to get the executable filename can be brittle under unusual circumstances, so the default choice should probably remain to hardcode the installation directory.

But for situations like CI where we know it's OK to auto-detect it, the option would be nice.

**Comment by lassik** [comment]
Perhaps a blank install dir (i.e. a zero-length string) could mean auto-detect.

A blank `--prefix` would mess up GNU autotools for sure, so the install dir would have to be stored in a variable distinct from the prefix. IIRC it already is.

**Comment by lassik** [comment]
> Perhaps a blank install dir (i.e. a zero-length string) could mean auto-detect.

This would also have the nice property that `gsi -:~~=` could be used for auto-detection even in pre-built Gambit versions that default to a hard-coded install dir.

**Comment by daviwil** [comment]
Maybe it doesn't need to be based on checking the value of `--prefix`, if you use a configure flag to enable the behavior then it could be injected into the Gambit code via `cond-expand` or similar.  I could be wrong, though.

**Comment by lassik** [comment]
In fact, `./configure --help` says there's already a `--enable-gambitdir=DIR` option which defaults to the same one as `--prefix`. I think Marc mentioned the value goes into a global variable in C/Scheme.

Could it be as simple as having `--enable-gambitdir=""` do the auto-detection?

**Comment by daviwil** [comment]
Could also set it to an expected special value like `_auto_`, but either way I think this sounds like a possibility!

**Comment by lassik** [comment]
And `gsi -:~~=foo` sets gambitdir to `foo` at runtime. So the runtime check could be something along these lines:

```scheme
(set! gambitdir
  (if (not (= 0 (string-length gambitdir)))
      gambitdir
      (let ((exe (os-executable-file)))
        (if exe
            (remove-directory "bin" (dirname exe))
            (error "Cannot auto-detect gambitdir")))))
```

**Comment by lassik** [comment]
(pseudo-code - maybe it needs to be done in C)

**Comment by lassik** [comment]
While we're at it, we could also support passing a relative directory as the gambitdir at runtime. Not sure whether this is useful or harmful.

> Could also set it to an expected special value like `_auto_`

If the auto-detect is done using a blank gambitdir, that has the advantage that it resolves the ambiguity about what the blank value means. Blank pathnames are traditionally perplexing - does it mean the current directory, or a file with a blank name, or is it invalid, or something else?

**Comment by feeley** [comment]
PR #572 adds the `~~execdir` notation to refer to the current executable's directory, something I've been meaning to do for a while.  It allows starting `gsi` like this:

    % gsi -:=~~execdir/..

This will cause `~~` in a path to refer to the parent directory of the directory containing the executable, so `~~bin` will (typically) refer to the right directory if `gsi`'s path is `.../bin/gsi`.

This way of finding the installation directory can be "burned into" a build of Gambit with the configuration:

    % ./configure --enable-gambitdir=~~execdir/..

**Comment by daviwil** [comment]
That's great!

**Comment by feeley** [comment]
> While we're at it, we could also support passing a relative directory as the gambitdir at runtime. Not sure whether this is useful or harmful.
> 
> > Could also set it to an expected special value like `_auto_`
> 
> If the auto-detect is done using a blank gambitdir, that has the advantage that it resolves the ambiguity about what the blank value means. Blank pathnames are traditionally perplexing - does it mean the current directory, or a file with a blank name, or is it invalid, or something else?

Indeed currently a blank directory means the current directory.

**Comment by lassik** [comment]
Great to have this finally implemented, and I'm very happy with how simple it turned out to be!

> Indeed currently a blank directory means the current directory.

Is this behavior deliberate or just a consequence of the way it's implemented?

**Comment by feeley** [comment]
It is a deliberate choice.  I use it all the time when running gsi in my local Gambit work directory with:

    % gsi/gsi -:=

That way it will find the correct files in `bin`, `include`, `lib`, etc

**Comment by lassik** [comment]
Right, so you can run it easily from the Git checkout of github.com/gambit/gambit.

I think your implementation solves all our concerns handily so I'm closing this :)

**Comment by daviwil** [comment]
I can confirm that a CI build of Gambit compiled with `--enable-gambitdir=~~execdir/..` properly resolves the path for `~~execdir`, `~~bin`, etc to where Gambit was downloaded to a local machine!  You can try one of the builds here to see for yourself: 

https://github.com/daviwil/gambit/releases/tag/latest-39735fd

**Comment by lassik** [comment]
Great! I tried the Mac `.zip` file and it works. `gsi -v` shows the right configure option.

The banner `Gambit v4.9.3-1131-g39735fd6` showing the `git describe` output is a nice touch.

**Comment by lassik** [comment]
Currently `chmod +x bin/gsc bin/gsi` needs to be done to set the Unix execute bit. Would it be easy to serve the Mac and Linux builds as `.tar.gz` instead of `.zip` archives? Tar can remember the execute bit.

For tar archives it's customary to put all files in the archive into one top-level directory (usually one with the same name as the archive file, e.g. `gambit-linux-x64.tar.gz` would extract all its files into a `gambit-linux-x64/` directory, avoiding so-called "tar bombs"). Not sure whether Windows has a similar custom for zip files - maybe not?

**Comment by feeley** [comment]
Yes I also tried the `.zip` file for macOS and I get:

```
$ ~/Desktop/gambit-macos-x64/bin/gsi -v
v4.9.3-1131-g39735fd6 20200526160520 x86_64-apple-darwin19.4.0 "./configure '--enable-single-host' '--enable-gambitdir=~~execdir/..' '--prefix=/Users/runner/runners/2.262.1/work/gambit/gambit/dist' 'CC=gcc-9'"
```

However I had to `chmod +x ~/Desktop/gambit-macos-x64/bin/gsi`... are the permissions not preserved by zip files?

@daviwil Can we also add artifacts to the gambit repo?  That could become a good way for some users to solve bootstrapping problems...

**Comment by feeley** [comment]
BTW I tend to prefer the term `x86_64` rather than `x64`.

**Comment by daviwil** [comment]
The most recent macOS releases have become more and more restrictive on random binaries you download from the internet.  They will automatically remove the `+x` permission and add some "quarantine" attributes to executable and compiled shared libraries to prevent you from running it outright.  I'm looking into a mitigation for that now.

Yep, I'll get the naming of everything right when I send a PR for this behaviro to the Gambit repo.

**Comment by daviwil** [comment]
Ahhh, I see some extra context on tar vs zip above, that could be why `+x` isn't being carried along.  I'll create a tar file instead.

**Comment by lassik** [comment]
> re the permissions not preserved by zip files?

They are not preserved by zip, we'd need tar.

> The most recent macOS releases have become more and more restrictive on random binaries you download from the internet. They will automatically remove the `+x` permission and add some "quarantine" attributes to executable and compiled shared libraries to prevent you from running it outright. I'm looking into a mitigation for that now.

Wow, I had no idea! Still on Mojave; `wget` of random archives from the internet and running the binaries still works I think.

> Yep, I'll get the naming of everything right when I send a PR for this behaviro to the Gambit repo.

Thanks!

**Comment by lassik** [comment]
> BTW I tend to prefer the term `x86_64` rather than `x64`.

Maybe we should use whichever name is the custom on the target OS. The Unix command `uname -m` gives `x86_64` on both Mac and Linux so it would be good to use that name on those platforms. That's good for scripts that get the architecture name from a variable or from `uname`.

On Windows the customary name is `x64` I suppose?

**Comment by daviwil** [comment]
Didn't know about `uname -m`, will try that!  I will also try using Gambit's `make dist` since it should do this nicely for us already.  I had trouble running it the one time I tried it because I wasn't able to build the docs, probably just need the necessary tools installed.

**Comment by lassik** [comment]
Once again, thank you very much for all the hard work you're putting into this! Getting the CI right for a complex project is always a massive undertaking.

**Comment by daviwil** [comment]
Thanks a lot!  I'm happy to be able to contribute something useful back to Gambit :)

**Comment by daviwil** [comment]
Thanks to @feeley's comment https://github.com/gambit/gambit/issues/574#issuecomment-634159157 I now know that `make dist` is more about packaging up source files, not binaries, so I'll continue to use my approach of using `--prefix` to capture build output and then package them up the proper way per-platform.

**Comment by lassik** [comment]
The pre-built binaries are definitely useful as well! I'd imagine by far the most Linux users have a GNU libc based distro. And Windows and Mac libraries ought to be widely compatible.

**Comment by daviwil** [comment]
Yep, for the vast majority of Linux users the prebuilt binaries will work fine since the mainline distros conform to the Linux Standard Base.

**Comment by lassik** [comment]
Maybe the Linux binaries artifact should be named `gambit-linux-x86_64-glibc.tar.gz` for maximum clarity? It's getting a little verbose but it would drive home the point :)

**Comment by lassik** [comment]
Or does GNU autotools have a standard naming conventions covering different architectures and libc implementations? If it does, we should probably stick with that.
