### ISSUE TITLE
Parameter bindings leaking into other threads

### ISSUE THREAD

**Issue by fare** [gambit/gambit#607]
While debugging a concurrent program with a lot of tracing, I discovered to my dismay that the dynamic binding of a parameter will sometimes leak from one thread to another during context switching. For an admittedly too long reproduction example, see:
https://github.com/fare/gerbil-utils/tree/gambit-bug/bug

Printing the trace data seems to help trigger the leak, presumably because it lengthens the time that some fragments of code being traced are in the critical section.

**Comment by fare** [comment]
Note that in a failing trace, I see:
```
<<< 3 (db-put! 65547 3682533387 #<DbTransaction #61 connection: #0=#<DbConnection #3 name: "testdb" leveldb: #<table #4> mx: #<mutex #5 "testdb"> txcounter: 11 blocked-transactions: () open-transactions: #<table #6> pending-(test-commit 12)
>>> 1 (current-db-transaction) 
<<< 1 (current-db-transaction) 
=== 1 (#<DbTransaction #61 connection: #0=#<DbConnection #3 name: "testdb" leveldb: #<table #4> mx: #<mutex #5 "testdb"> txcounter: 11 blocked-transactions: () open-transactions: #<table #6> pending-transactions: (#<DbTransaction #41 connection: #0# txid: 6 status: pending completion: #<completion #42 mx: #<mutex #43 completion> cv: #<condition-variable #44 completion> ready?: #f val: #f exn: #f>> #<DbTransaction #36 connection: #0# txid: 5 status: pending completion: #<completion #37 mx: #<mutex #38 completion> cv: #<condition-variable #39 completion> ready?: #f val: #f exn: #f>> #<DbTransaction #26 connection: #0# txid: 3 status: pending completion: #<completion #27 mx: #<mutex #28 completion> cv: #<condition-variable #29 completion> ready?: #f val: #f exn: #f>> #<DbTransaction #21 connection: #0# txid: 2 status: pending completion: #<completion #22 mx: #<mutex #23 completion> cv: #<condition-variable #24 completion> ready?: #f val: #f exn: #f>> #<DbTransaction #16 connection: #0# txid: 1 status: pending completion: #<completion #17 mx: #<mutex #18 completion> cv: #<condition-variable #19 completion> ready?: #f val: #f exn: #f>> #<DbTransaction #10 connect
```
So the evaluation was interrupted while printing the `db-put` tracing information (which happens while in the binding), and next thing, another thread consults the dynamic binding via `(current-db-transaction)` and gets the wrong value.

**Comment by fare** [comment]
So, this all suggests a much better bug reproduction:
```
(define (writeln x)
  (write x)
  (newline)
  (force-output))
(define (fail! x)
  (display "FAIL: ")
  (writeln x)
  (exit 42))
(define (spawn/name n f . as)
  (define thr (make-thread (lambda () (apply f as)) n))
  (thread-start! thr)
  thr)
(define (parallel-map name f . ls)
  (map thread-join! (apply map (lambda es (apply spawn/name `(parallel-map: ,name ,@es) f es)) ls)))

(define n-workers 1000)
(define n-work 1000)

(define foo (make-parameter #f))
(define bar (make-parameter #f))
(define baz (make-parameter #f))
(define quux (make-parameter #f))
(define quuux (make-parameter #f))
(define quuuux (make-parameter #f))

(define (test-worker i)
  (with-exception-handler
   (lambda (e)
     (fail! (list IN-TEST: i e)))
   (lambda ()
     (let ((l (list (foo) (bar) (baz) (quux) (quuux) (quuuux))))
       (writeln (list i l))
       (unless (equal? (list #f #f #f #f #f #f) l)
         (fail! (list BUG2: i l))))
     (parameterize ((foo i)
                    (bar i)
                    (baz i)
                    (quux i)
                    (quuux i)
                    (quuuux i)
                    )
       (let loop ((i n-work))
         (unless (zero? i)
           (let ((l (list (foo) (bar) (baz) (quux) (quuux) (quuuux))))
             (writeln (list i l))
             (unless (equal? (list i i i i i i) l)
               (fail! (list BUG: i l))))
           (loop (- i 1))))))))

(with-exception-catcher
 (lambda (e)
   (fail! (list BLAH: e)))
 (lambda ()
   (parallel-map "foo" test-worker (iota n-workers 1))))
```

**Comment by fare** [comment]
Builtin trace actually works better:
```
(define-syntax defrules (syntax-rules () ((_ name foo ...) (define-syntax name (syntax-rules foo ...)))))
(defrules defrule () ((_ (name args ...) body ...) (defrules name () ((_ args ...) body ...))))
(defrule (def formals body ...) (define formals body ...))

(define (writeln x)
  (write x)
  (newline)
  (force-output))
(define (fail! x)
  (display "FAIL: ")
  (writeln x)
  (exit 42))

(define n-workers 100000000)
(define n-work 10)

(define foo (make-parameter 0))
(define bar (make-parameter 0))
(define baz (make-parameter 0))
(define quux (make-parameter 0))
(define quuux (make-parameter 0))
(define quuuux (make-parameter 0))

;;(trace! foo bar baz quux quuux quuuux)
(trace foo) (trace bar) (trace baz) (trace quux) (trace quuux) (trace quuuux)

(define (vars) (list (foo) (bar) (baz) (quux) (quuux) ;;(quuuux)
                     ))
(defrule (with-vars i body ...)
  (parameterize ((foo i) (bar i) (baz i) (quux i) (quuux i) ;;(quuuux i)
                 ) body ...))

(define (spawn/name n f . as)
  (unless (zero? (foo)) (fail! (list s/n1: (foo))))
  (let ((thr (make-thread (lambda () (apply f as)) n)))
    (unless (zero? (foo)) (fail! (list s/n2: (foo))))
  (thread-start! thr)
  (unless (zero? (foo)) (fail! (list s/n3: (foo))))
  thr))
(define (parallel-map name f . ls)
  (map thread-join! (apply map (lambda es (apply spawn/name `(parallel-map: ,name ,@es) f es)) ls)))

(define (test-worker i)
  (writeln `(test-worker ,i))
  (with-exception-handler
   (lambda (e)
     (fail! (list IN-TEST: i e)))
   (lambda ()
     (let ((l (vars)))
       (writeln (list i l))
       (unless (apply = 0 l)
         (fail! (list BUG2: i l))))
     (with-vars i
       (let loop ((j n-work))
         (unless (zero? j)
           (let ((l (vars)))
             (writeln (list i l))
             (unless (apply = i l)
               (fail! (list BUG: i l))))
           (loop (- j 1))))))))

(with-exception-catcher
 (lambda (e)
   (fail! (list BLAH: e)))
 (lambda ()
   (parallel-map "foo" test-worker (iota n-workers 1))))
```
If I comment the `(vars)` to have only three variables, I can't reproduce the bug, but with four to six variables, in a few seconds is enough to trigger the bug.

**Comment by feeley** [comment]
Gambit extends the `parameterize` form whose R7RS spec is:

    (parameterize ((⟨param1⟩ ⟨value1⟩) ...) ⟨body⟩)       syntax

    Syntax: Both ⟨param1⟩ and ⟨value1⟩ are expressions.

    It is an error if the value of any ⟨param⟩ expression is not a parameter object.

So Gambit supports the following conventional usage:

    (define param (make-parameter 42))

    (pp (param))

    (parameterize ((param (+ 1 (param))))
      (pp (param)))

    (pp (param))

    ;; output:
    ;;
    ;; 42
    ;; 43
    ;; 42

As an extension, Gambit's `parameterize` also accepts arbitrary procedures as the `param`. The procedure must obey the protocol that when it is called with one argument it conceptually "sets" an abstract parameter, and when it is called with no argument it conceptually "reads" the abstract parameter.  So when `param` is a procedure that is not a parameter object, a `(parameterize ((param <expr>)) <body>)` is equivalent to:

    (let ((old (param)))
      (dynamic-wind
       (lambda () (param <expr>))
       (lambda () <body>)
       (lambda () (param old))))

This allows using `parameterize` like this:

    (define myparam
      (let ((state 42))
        (lambda rest
          (if (pair? rest)
              (set! state (car rest))
              state))))

    (pp (myparam))

    (parameterize ((myparam (+ 1 (myparam))))
      (pp (myparam)))

    (pp (myparam))

    ;; output:
    ;;
    ;; 42
    ;; 43
    ;; 42

Not that this second usage is not thread safe because `dynamic-wind` is not affected by context switches between threads.

Why is all of this relevant to your code?  Because a `(trace foo)` is essentially equivalent to

    (set! foo
          (let ((old foo))
            (lambda args
              (pp `(foo ,@args))
              (let ((r (apply old args)))
                (pp r)
                r))))

But when `foo` is bound to a parameter object, it is no longer bound to a parameter object after a `(trace foo)`.  It becomes bound to a normal procedure.  This fact is even mentioned as a warning:

    > (define foo (make-parameter 42))
    > (trace foo)
    *** WARNING -- Rebinding global variable "foo" to an interpreted procedure

And when this happens, a `parameterize` of `foo` will fall into the extended behaviour which uses `dynamic-wind`, which works in a single threaded program, but does not when there are multiple threads.

This is an unfortunate case where separate extensions to the standard (`trace` and extended `parameterize`) interact non-intuitively.  If you remove either extension then there are no surprises.  Note that tracing is not transparent in other respects too:

    > (define foo list)
    > (eq? foo list)
    #t
    > (trace foo)
    *** WARNING -- Rebinding global variable "list" to an interpreted procedure
    > (eq? foo list)
    #f

So your options for your use case are:

1) don't "trace" parameter objects and put the tracing as explicit calls to `pp` in the body of all `parameterize`

2) put the tracing in the conversion procedure (second parameter of `make-parameter`):

    > (define param (make-parameter 42 (lambda (x) (pp `(param ,x)) x)))
    (param 42)
    > (parameterize ((param (+ 1 (param)))) (pp (param)))
    (param 43)
    43

3) trace the conversion procedure:

    > (define (param-conv x) x)
    > (define param (make-parameter 42 param-conv))
    > (trace param-conv)
    > (parameterize ((param (+ 1 (param)))) (pp (param)))
    | > (param-conv 43)
    | 43
    43

**Comment by fare** [comment]
Thanks!

**Comment by feeley** [comment]
> While debugging a concurrent program with a lot of tracing, I discovered to my dismay that the dynamic binding of a parameter will sometimes leak from one thread to another during context switching. For an admittedly too long reproduction example, see:
> https://github.com/fare/gerbil-utils/tree/gambit-bug/bug
> 
> Printing the trace data seems to help trigger the leak, presumably because it lengthens the time that some fragments of code being traced are in the critical section.

The procedure `1+` in `db.scm` is not defined.
