### ISSUE TITLE
gambitscheme.org is unreachable

### ISSUE THREAD

**Issue by R1ck77** [gambit/gambit#634]
Trying to open gambitscheme.org seems to result in a ERR_CONNECTION_TIMED_OUT

I'm reporting the problem here since the URL is mentioned in the README.md and similar reports have been done in the past, I hope it's appropriate

Thank you for your attention!

**Comment by R1ck77** [comment]
Whatever you did worked: thank you very much for the prompt solution and for gambit in the first place!

**Comment by R1ck77** [comment]
Whatever you did worked: thank you very much for the prompt solution and for gambit in the first place!

**Comment by wasamasa** [comment]
Seems to be down again.

**Comment by hxegon** [comment]
down for me too
