### ISSUE TITLE
___alloc_rc segfaults on MacOS and Linux, gcc and clang

### ISSUE THREAD

**Issue by lubgr** [gambit/gambit#641]
I tested the following snippet
```
#include <gambit.h>

int main(void)
{
    void *test = ___EXT(___alloc_rc)(0);

    ___EXT(___release_rc)(test);
}
```
on MacOS Catalina, with `clang` 11.0.3 and `gcc` 10.2.0 (homebrew build) and the homebrew-installed `gambit-scheme` 4.9.3 as well as on ArchLinux, same gambit version, `clang` 10.0.1 and `gcc` 10.2.0. All (manually, successfully linked) executables result in a segmentation fault (`EXC_BAD_ACCESS`). Am I doing something wrong or is this an issue? The result doesn't change if I initialize and cleanup the runtime with `___setup` and `___cleanup`.

**Comment by feeley** [comment]
You need to call `___setup` as a prerequisite to any call to the Gambit C API.  It initializes the runtime system, including the memory management module.  One way to run your test is by compiling this Scheme code:

```
(c-declare #<<end-of-c-declare

#include <stdio.h>

void test(void) {
    void *p = ___EXT(___alloc_rc)(0);
    printf("p = %p\n", p);
    ___EXT(___release_rc)(p);
    printf("%p was released\n", p);
}

end-of-c-declare
)

(define test (c-lambda () void "test"))

(test)
```

**Comment by lubgr** [comment]
Thanks for your quick reply, I appreciate that! I got it to work properly, except two issues:

1. After `___alloc_rc` followed by a `__release_rc`, I get (no matter what size I pass to `__alloc_rc`)
    ```
    malloc: *** error for object 0x7fcc5f4079f0: pointer being freed was not allocated
    malloc: *** set a breakpoint in malloc_error_break to debug
    ```
    Any thoughts?

2. With `#include <gambit.h>` from a `.c` file, linking works, but when I invoke any of the functions with `__cplusplus` defined (i.e. compiling a `.cpp` file with `g++`), I get a linking error on undefined symbols. The mangled symbols show that the linker searches e.g. for a `___release_rc` with C++ mangling. Aren't those functions declared within `___BEGIN_C_LINKAGE`/`___END_C_LINKAGE`?

**Comment by feeley** [comment]
I'm sorry but I don't get the error message you are getting and I'm on macOS Catalina.

To get a log of all `malloc/free` requests done by the Gambit runtime system, build Gambit with:

```
% make clean
% ./configure --enable-single-host --enable-debug --enable-debug-alloc-mem
% make -j8
```

[I typically add `CC=gcc-9` at the end of the configure command to use GNU gcc.]

Then compile your program and run it, and you will get a file `gambit.log` with a trace of all the allocations and deallocations.  Check if things match up correctly.  For example, for your program with an `___alloc_rc(20000)` I get these lines

```
...
0x7fe88e407f00 (9 bytes) ALLOCATED AT "os_tty.c"@5211.1
0x7fe88e407f10 (681 bytes) ALLOCATED AT "os_tty.c"@1496.1
0x7fe88e407a40 FREED AT "os_tty.c"@1509.1
0x7fe88e407a40 (87 bytes) ALLOCATED AT "mem.c"@563.1
0x7fe88e407aa0 (199 bytes) ALLOCATED AT "mem.c"@563.1
0x7fe88e80c800 (20032 bytes) ALLOCATED AT "mem.c"@693.1       <========= malloc of 20000 + sizeof(header)
0x7fe88e80c800 FREED AT "mem.c"@732.1       <========= free
0x7fe88e405970 FREED AT "c_intf.c"@6333.1
0x7fe88e405960 FREED AT "c_intf.c"@6333.1
0x7fe88e405990 FREED AT "main.c"@274.1
0x7fe88e4059c0 FREED AT "c_intf.c"@6333.1
...
```

For the C++ linking issues, make sure you build Gambit with `./configure --enable-cplusplus` if you are going to link to C++ code.

**Comment by lubgr** [comment]
Ok, I will figure the `rcalloc` issue out then, must be an issue in my test files. Thanks for checking this on your side, and the `--enable-cpluscplus` hint!

**Comment by feeley** [comment]
No problem. I hope you have figured out the issue.
