### ISSUE TITLE
Error in quantal response equilibrium

### ISSUE THREAD

**Issue by wyz2368** [gambit/gambit#646]
I installed the gambit 16.0.1. When I run `gambit-logit e02.nfg`, I got the following error. 

0.000000Error: Dereferencing an invalidated object

Can anyone help me?

**Comment by abdelq** [comment]
Wrong Gambit:
https://github.com/gambitproject/gambit

**Comment by gambiteer** [comment]
As abdelq commented, wrong Gambit.
