### ISSUE TITLE
Gambit website fail to load

### ISSUE THREAD

**Issue by jcubic** [gambit/gambit#649]
http://www.gambitscheme.org/ keep loading and then after few seconds it give timeout error.

**Comment by FranklinChen** [comment]
It is still down.

**Comment by xlxs4** [comment]
still down

**Comment by lassik** [comment]
The server needs to be restarted and is physically unreachable at the moment. Will take a few more days.

**Comment by concastinator** [comment]
This is already more than 2 months since the site is down. @lassik, are you sure that this is simply a server restart issue? That none of the core contributers to the project seems bothered by this (no note, no explanation, nothing) reflects very badly on the project as a whole and makes one ask oneself deep questions about the future and relevance of Gambit.

**Comment by gambiteer** [comment]
I'm not going to defend it being down in the midst of a pandemic, but I will point out that while websites used to be nearly the only way to get information about a project, there is now github, gitter, etc., all of which are reasonably active (weekly, if not daily) where people can get responses to issues.

Of all the "core contributors" (of which I think I'm one), I think only Marc has access to the web server.

**Comment by lassik** [comment]
The server restart issue was solved long ago but the site isn't up yet. There's now a placeholder page at http://gambitscheme.org/

**Comment by gambiteer** [comment]
Perhaps adding links from the placeholder page to github and gitter would help temporarily.

**Comment by concastinator** [comment]
For over half a year the main website (gambitscheme.org) displays only the message "Welcome to gambitscheme.org! We are in the process of changing the web server and reorganizing the website. Please stay tuned...". I have been staying tuned since last December... I am old enough to know that this is how projects begin to die.

**Comment by feeley** [comment]
The death of Gambit has been greatly exaggerated.  There are just many things of higher priority to work on and finite ressources.

**Comment by mdbergmann** [comment]
I was stumbling over this as well.
But I can tell by watching this project for more than half year, it's quite alive.
I don't usually care about a web page. The only issue would be if there are documentation resources that are not easily accessable vit GitHub.

**Comment by feeley** [comment]
The Gambit project is definitely very active with many commits by an increasing number of contributors.  I welcome any new contributors that want to see the project grow even faster.  Concerning the web page there is a WIP to replace the wiki page with something more static and stable (contact me privately for a URL to preview the page).  Last year I had reinstalled the wiki on a new server (the old one was crashing every few months) but the new wiki was promptly attacked by hackers so I had to bring it down to avoid further damage.  I will have some time in 1-2 weeks to reevaluate the situation.

**Comment by feeley** [comment]
I found some time to reinstall the old Gambit wiki in read-only mode (to prevent spammers).  You will find it at the same place as before: https://gambitscheme.org/wiki/index.php

This is mainly to recover information that was previously available.  In the long term, new information should be put elsewhere (such as the github repository issues).  A nice looking landing page is being worked on but it will require some more time.

**Comment by gwerbin** [comment]
The page <https://gambitscheme.org/wiki/index.php> appears to be down: "502 Bad Gateway".

**Comment by feeley** [comment]
For some reason the PHP daemon was wedged because it hadn't been updated.  That's done now and the wiki is back up.  Thanks for reporting this.
