### ISSUE TITLE
Copyright (c) All Rights Reserved

### ISSUE THREAD

**Issue by jcubic** [gambit/gambit#655]
It seems that part of the files have All right reserved with copyright note. Which is revere of Open Source. Which mean that this file is proprietary. All files should have Copyright note with info that it's Open Source and license information.

Example file: https://github.com/gambit/gambit/blob/master/lib/_univlib.scm

I think that this requirement of any GNU license and I see that you have LGPL.txt file in repo.
There should be clear statement that this is dual licensed if it apply.

**Comment by feeley** [comment]
The license information is in Chapter 21 of the Gambit manual.  I copy the first paragraph here.

    The Gambit system release v4.9.3 is Copyright (c) 1994-2020 by Marc Feeley, all rights reserved.
    The Gambit system release v4.9.3 is licensed under two licenses: the Apache License, Version 2.0,
    and the GNU LESSER GENERAL PUBLIC LICENSE, Version 2.1. You have the option to choose which
    of these two licenses to abide by. The licenses are copied below.

The copyright notice and the license are two different things (https://opensource.stackexchange.com/questions/297/whats-the-difference-between-copyright-and-licensing).

**Comment by jcubic** [comment]
This don't make sense "all rights reserved" is used when thing is proprietary this is opposite of the next lines.

**Comment by lassik** [comment]
Some license notices do say "all rights reserved" for some reason. E.g. https://spdx.org/licenses/BSD-2-Clause.html

Nowadays, a convention is to use `SPDX-License-Identifier` comments at the top of each source file to indicate the license ([example from Linux](https://github.com/torvalds/linux/blob/master/kernel/pid.c#L1)).

**Comment by feeley** [comment]
I was advised many years ago to put the "all rights reserved" in copyright notices to make sure people understand the copyright notice.  It turns out that since 2000 the copyright laws are such that it is no longer necessary to have the "all rights reserved" part.  So just consider that to be an old habit of mine.  The "all rights reserved" is a no-op.
