### ISSUE TITLE
Wrong type for FIONBIO in set_socket_blocking_mode

### ISSUE THREAD

**Issue by abdelq** [gambit/gambit#666]
In [line 5608 of `os_io.c`](https://github.com/gambit/gambit/blob/master/lib/os_io.c#L5608) an `unsigned long` is passed as an argument to the `FIONBIO` ioctl.

That's fine on [Windows](https://docs.microsoft.com/en-us/windows/win32/api/winsock/nf-winsock-ioctlsocket#syntax), but it causes issues on other operating systems that are expecting an `int` (e.g. [OpenBSD](https://man.openbsd.org/ioctl.2#FIONBIO) or even GNU/Linux).
The bug is only obvious on big-endian systems as it's causing one of the tests to hang.

Looking around some codebases online, it seems like most just use `FIONBIO` on Windows and rely on `fcntl` for the rest.

---
Originally reported in https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=953728

**Comment by feeley** [comment]
Thanks for noticing this.  Can you propose a PR?
