### ISSUE TITLE
New release request

### ISSUE THREAD

**Issue by siraben** [gambit/gambit#667]
It's been over 2 years since the last release, downstream package managers such as Nixpkgs are still using the latest tag. It would be nice to have some sort of minor/major release.

**Comment by siraben** [comment]
Ping @feeley

**Comment by feeley** [comment]
Yes I agree that a release soon would be good.  It is on my todo but not yet at the top.

**Comment by bheesham** [comment]
Triage: I believe this ticket can be closed. The latest release was 4.9.4, from Jan 2 2022.
