### ISSUE TITLE
case-lambda with zero arguments that was not specified throw exception

### ISSUE THREAD

**Issue by jcubic** [gambit/gambit#669]
I was testing Web REPL at http://gambitscheme.org/try/ with simple `case-lambda` example:

```scheme
(define sum
  (case-lambda
    ((x) x)
    ((x y) (+ x y))
    ((x y z) (+ x y z))))

(sum)
```
it throws `Cannot read property 'cdr' of undefined` I think it should show same error as in `(sum 1 2 3 4 5)`

After this Web REPL is broken and you need to refresh the page.

**Comment by feeley** [comment]
This problem has been fixed in the Gambit github repo a few days ago (but gambitscheme.org/try is not up to date).  This is what I get using my local branch:

```
> (define sum
    (case-lambda
      ((x) x)
      ((x y) (+ x y))
      ((x y z) (+ x y z))))
> (sum)
*** ERROR IN console@6.1 -- Wrong number of arguments passed to procedure
(sum)
1> 
```

I will update today.
