### ISSUE TITLE
Add -fno-tree-loop-im to gcc command line when --enable-coverage

### ISSUE THREAD

**Issue by gambiteer** [gambit/gambit#671]
GCC documentation says:

`-ftree-loop-im`

Perform loop invariant motion on trees. This pass moves only invariants that are hard to handle at RTL level (function calls, operations that expand to nontrivial sequences of insns). With -funswitch-loops it also moves operands of conditions that are invariant out of the loop, so that we can use just trivial invariantness analysis in loop unswitching. The pass also includes store motion.

I don't know what this means, but right now it seems to be necessary when the compiler is `gcc` and `--enable-coverage` is an argument to the configuration script, otherwise you'll get an out-of-memory error with newer (> 4.9.0) versions of `gcc`.  See https://gcc.gnu.org/bugzilla/show_bug.cgi?id=64928#c36 and following comments.

It probably wouldn't hurt to be added unconditionally as an argument to `gcc`.  I don't think that LLVM supports it now, so there should be a configure check for it.

Brad

**Comment by gambiteer** [comment]
Maybe I'll do some benchmarking to see whether this option is benign when not `---enable-test-coverage`.

**Comment by gambiteer** [comment]
The following configuration command
```heine:~/programs/gambit/gambit/bench> gsi -v
v4.9.3-1333-gce660754 20210311010343 x86_64-pc-linux-gnu "./configure 'CC=gcc -march=native -D___CAN_IMPORT_CLIB_DYNAMICALLY -fno-tree-loop-im' '--enable-single-host' '--enable-multiple-versions' '--enable-shared'"
```
seems to make all but one of the benchmark programs run faster than if ` -fno-tree-loop-im` is omitted.  It's almost unbelievable, some are nearly twice as fast, you should check the results yourself before adding it to the configure script.

I'll add the files generated by the `summarize` script.
[fno-tree-loop-im.txt](https://github.com/gambit/gambit/files/6119938/fno-tree-loop-im.txt)
[ftree-loop-im.txt](https://github.com/gambit/gambit/files/6119939/ftree-loop-im.txt)

**Comment by gambiteer** [comment]
Here are raw `results.*` files.
[results.tar.gz](https://github.com/gambit/gambit/files/6120070/results.tar.gz)

**Comment by feeley** [comment]
On my machine with gcc-10 I only see a 1% difference, which is probably noise...

Can you give details on your machine and the version of gcc?

**Comment by gambiteer** [comment]
Well, I think this covers it:
```
heine:~/programs/gambit/gambit/bench> gsi -v
v4.9.3-1333-gce660754 20210311010343 x86_64-pc-linux-gnu "./configure 'CC=gcc -g -march=native -D___CAN_IMPORT_CLIB_DYNAMICALLY -fno-tree-loop-im' '--enable-single-host' '--enable-multiple-versions' '--enable-shared'"
heine:~/programs/gambit/gambit/bench> gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/9/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none:hsa
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 9.3.0-17ubuntu1~20.04' --with-bugurl=file:///usr/share/doc/gcc-9/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++,gm2 --prefix=/usr --with-gcc-major-version-only --program-suffix=-9 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-plugin --enable-default-pie --with-system-zlib --with-target-system-zlib=auto --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none=/build/gcc-9-HskZEa/gcc-9-9.3.0/debian/tmp-nvptx/usr,hsa --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 9.3.0 (Ubuntu 9.3.0-17ubuntu1~20.04) 
heine:~/programs/gambit/gambit/bench> cat /proc/cpuinfo | grep Xeon | tail -1
model name	: Intel(R) Xeon(R) CPU E3-1271 v3 @ 3.60GHz
heine:~/programs/gambit/gambit/bench> uname -a
Linux heine 5.4.0-66-generic #74-Ubuntu SMP Wed Jan 27 22:54:38 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```
I don't know how much of a difference the `-march=native -D___CAN_IMPORT_CLIB_DYNAMICALLY` make in the `configure` arguments.

**Comment by gambiteer** [comment]
Marc:  The short version is that when `--enable-coverage` is part of the arguments to configure, then `-fno-tree-loop-im` needs to be added to the `gcc` options if that option is recognized at configure time.
Unfortunately, I don't know to do this.

**Comment by gambiteer** [comment]
Marc: Please add `-fno-tree-loop-im` to the `gcc` options when Gambit is configured with `--enable-coverage`.  I don't know how to do this, and after two years I'd like to forget about it.  Brad

**Comment by gambiteer** [comment]
Marc: I just discovered that this bug doesn't present itself in GCC 12.3 or later (even though the GCC folks haven't yet figured out why).

So I'm going to close this issue; if the problem reappears then I'll reopen it.
