### ISSUE TITLE
Gambit IRC channel

### ISSUE THREAD

**Issue by lassik** [gambit/gambit#709]
Is the `#gambit` IRC channel still relevant, and if so, is the official channel on the Freenode or Libera.Chat network? (There has been a mass exodus of channels from the old Freenode to the newly established Libera during this month.)

**Comment by feeley** [comment]
Frankly I had forgotten `#gambit` existed so I don't expect there is much traffic there.  The Gambit Gitter is the most active Gambit chat channel.

**Comment by lassik** [comment]
OK, I'll remove the mention of the IRC channel from chat.scheme.org. The Gitter channel is mentioned there.
