### ISSUE TITLE
Use of undeclared identifier 'VERSION'

### ISSUE THREAD

**Issue by emiehling** [gambit/gambit#716]
I am attempting to install the Python extension for gambit (on Mac OS X) by following the directions [found here](http://www.gambit-project.org/gambit15/build.html#build-python).

I  am running into the following error when I run `sudo /usr/local/bin/python3 setup.py build`:

    gambit/lib/libgambit.cpp:79928:40: error: use of undeclared identifier 'VERSION'
      __pyx_t_1 = __Pyx_PyBytes_FromString(VERSION); if (unlikely(!__pyx_t_1...
                                           ^
    1 error generated.
    error: command '/usr/bin/clang' failed with exit code 1

**Comment by feeley** [comment]
You have the wrong Gambit project.  The https://github.com/gambit/gambit repository if for the Gambit Scheme project.

**Comment by emiehling** [comment]
Thanks. Can you point me to the instructions to install the Python extension in this repo?
