### ISSUE TITLE
Gambit Segmentation Fault

### ISSUE THREAD

**Issue by aseshkdatta** [gambit/gambit#717]
Hi,

The example mpirun of gambit as suggested on page 21
of the GUM paper on arXiv (2107.00030) is leading to
segmentation fault on a particular (desktop) machine.
The message is as follows.

Could you please help.

Thanks and regards.
Asesh

-----------------------------------------------------------------------------
asesh@albert:~/MyPlace/Packages/gambit_2.0$ time mpirun -n 4 gambit -f yaml_files/MDMSM_Tute.yaml 

GAMBIT 2.0.0
http://gambit.hepforge.org

GAMBIT 2.0.0
http://gambit.hepforge.org

GAMBIT 2.0.0
http://gambit.hepforge.org

GAMBIT 2.0.0
http://gambit.hepforge.org

--------------------------------------------------------------------------
mpirun noticed that process rank 3 with PID 0 on node albert exited on signal 11 (Segmentation fault).
--------------------------------------------------------------------------

real	0m5.359s
user	0m6.412s
sys	0m0.089s
asesh@albert:~/MyPlace/Packages/gambit_2.0$
-----------------------------------------------------------------------------

**Comment by feeley** [comment]
You have the wrong Gambit project.  This repository if for the Gambit Scheme project.
