### ISSUE TITLE
Old (2016) way of building Meroon doesn't still work

### ISSUE THREAD

**Issue by gambiteer** [gambit/gambit#721]
If you start with https://www.math.purdue.edu/~lucier/Meroon-example.tgz you will find a shell script `make_meroon`.  In it are the lines
```
;; If you use the next declaration, then (load "_meroon.o1") in gsi fails.
;; (declare (standard-bindings)(extended-bindings)(not safe)(block))
;; If you use the next declaration, then (load "_meroon.o1") in gsi succeeds.
(declare (not inline)(inlining-limit 0)(not inline-primitives)(not run-time-bindings)(not standard-bindings)(not extended-bindings))
```
By "work" I mean at a minimum doing `(load "_meroon.o1")` in `gsi` doesn't segfault.  In my tests with the currently uncommented second declaration everything works fine  as:
```
heine:/tmp/MeroonV3-2016Nov03> ./make_meroon 
Gambit v4.9.3-1600-geebbb9bd

> "/tmp/MeroonV3-2016Nov03/old-load.scm"
> [ Meroon V3 Paques2001+1 $Revision: 1.2 $ ]
> "/tmp/MeroonV3-2016Nov03/_meroon.o1"
> 
*** EOF again to exit
heine:/tmp/MeroonV3-2016Nov03> cd Examples/
heine:/tmp/MeroonV3-2016Nov03/Examples> gsc
Gambit v4.9.3-1600-geebbb9bd

> (load "../_meroon")
[ Meroon V3 Paques2001+1 $Revision: 1.2 $ ]
"/tmp/MeroonV3-2016Nov03/Examples/../_meroon.o1"
> (compile-file "interp.gsc")
"/tmp/MeroonV3-2016Nov03/Examples/interp.o1"
> (load "interp")
*** WARNING -- Variable "wrong" used in module "interp" is undefined
"/tmp/MeroonV3-2016Nov03/Examples/interp.o1"
> (time (start-bench))
(*** Meroon benchmark *iterations* = 10)

(Meroon V3 Paques2001+1 $Revision: 1.2 $)
Total number of classes: 43
Total number of generic functions: 97
(estimated) internal size of Meroon: 3744 pointers
(2 3 5 7 11 13 17 19 23 29 31 37)
(2 3 5 7 11 13 17 19 23 29 31 37)
(2 3 5 7 11 13 17 19 23 29 31 37)
(2 3 5 7 11 13 17 19 23 29 31 37)
(2 3 5 7 11 13 17 19 23 29 31 37)
(2 3 5 7 11 13 17 19 23 29 31 37)
(2 3 5 7 11 13 17 19 23 29 31 37)
(2 3 5 7 11 13 17 19 23 29 31 37)
(2 3 5 7 11 13 17 19 23 29 31 37)
(2 3 5 7 11 13 17 19 23 29 31 37)
(time (start-bench))
    0.573213 secs real time
    0.571169 secs cpu time (0.571169 user, 0.000000 system)
    no collections
    7222944 bytes allocated
    893 minor faults
    no major faults
done
> (compile-file "vsg.gsc")
"/tmp/MeroonV3-2016Nov03/Examples/vsg.o1"
> (load "vsg")
*** WARNING -- Variable "naive-match" used in module "vsg" is undefined
*** WARNING -- Variable "suite-test" used in module "vsg" is undefined
"/tmp/MeroonV3-2016Nov03/Examples/vsg.o1"
> (compile-file "vsg-bench.gsc")
"/tmp/MeroonV3-2016Nov03/Examples/vsg-bench.o1"
> (load "vsg-bench")
"/tmp/MeroonV3-2016Nov03/Examples/vsg-bench.o1"
> (time (start-bench))

(Meroon V3 Paques2001+1 $Revision: 1.2 $)
Total number of classes: 55
Total number of generic functions: 114
(estimated) internal size of Meroon: 4716 pointers
(0 terms of cost 0)
(5 terms of cost 1)
(17 terms of cost 2)
(89 terms of cost 3)
(665 terms of cost 4)
(4805 terms of cost 5)
(0 terms of cost 0)
(5 terms of cost 1)
(17 terms of cost 2)
(89 terms of cost 3)
(665 terms of cost 4)
(4805 terms of cost 5)
(time (start-bench))
    1.034765 secs real time
    1.034552 secs cpu time (1.030573 user, 0.003979 system)
    6 collections accounting for 0.028339 secs real time (0.028302 user, 0.000009 system)
    39725512 bytes allocated
    3110 minor faults
    no major faults
done
> (time (start-bench))

(Meroon V3 Paques2001+1 $Revision: 1.2 $)
Total number of classes: 55
Total number of generic functions: 114
(estimated) internal size of Meroon: 4716 pointers
(0 terms of cost 0)
(5 terms of cost 1)
(17 terms of cost 2)
(89 terms of cost 3)
(665 terms of cost 4)
(4805 terms of cost 5)
(0 terms of cost 0)
(5 terms of cost 1)
(17 terms of cost 2)
(89 terms of cost 3)
(665 terms of cost 4)
(4805 terms of cost 5)
(time (start-bench))
    0.032404 secs real time
    0.032408 secs cpu time (0.032408 user, 0.000000 system)
    no collections
    31776 bytes allocated
    no minor faults
    no major faults
done
> 
```
You can examine the script `make_meroon` to see the steps it goes through.
Now the declaration that currently fails used to work.  I don't know which of the specific differences in declarations causes the difference.
I can accept the very real possibility that recent (< 5 years) changes to the compiler exposed some errors in Meroon, but I could really use a bit of help here.

**Comment by feeley** [comment]
The crash happens when evaluating this toplevel form:

    (meroon-define Class-next (Mono-Field-create-careful-reader Class-class 'next))

The procedure `(Mono-Field-create-careful-reader class fieldname)` calls `(retrieve-named-field class fieldname)` which can't find the `next` field so it calls `(report-bad-coercion-to-field class name)` which is not yet defined.

With the declare that crashes, the fields of the class are:

    (name number fields depth super-number subclass-numbers)

With the declare that doesn't crash, the fields of the class are:

    (name number fields depth super-number subclass-numbers next allocator immutable? views suprel)

The next debugging step is to determine why this is the case with those declarations.

**Comment by feeley** [comment]
The problem comes from the definition of `iota` in `_meroon.scm`:

```
;;; Returns the list of numbers [start start+1 .... end [

(define (iota start end)
  (if (fx< start end)
      (cons start (iota (fx+ 1 start) end))
      '() ) )
```

This conflicts with the predefined `iota` whose first argument is the count, not the starting point of the range. However a `(declare (standard-bindings))` tells the compiler that it can assume the `iota` global variable always contains the predefined `iota`, so at expansion time the call to `iota` is replaced with a call to `##iota` because there is a `(declare (not safe))`.  So the program's behaviour changes.

I suggest you change the calls `(iota start end)` to `(range start end)` or `(interval start end)`.  Even better would be to use the module system to more clearly indicate the dependencies between modules and being selective with what is imported.  A quick fix is adding `(declare (not standard-bindings iota))`.

**Comment by feeley** [comment]
I have added a verification in the compiler that checks for definitions of global variables that are standardly bound and emits a warning if `-warnings` is passed on the command line.  See commit 539a680a951b6b88e5d57ae9e8872e7d42c76fba

When compiling `_meroon.scm` this will generate these warnings:

```
*** WARNING IN "/Users/feeley/meroon/MeroonV3-2016Nov03/_meroon.scm"@825.1 -- Definition of standardly bound global variable reverse!
*** WARNING IN "/Users/feeley/meroon/MeroonV3-2016Nov03/_meroon.scm"@890.1 -- Definition of standardly bound global variable identity
*** WARNING IN "/Users/feeley/meroon/MeroonV3-2016Nov03/_meroon.scm"@894.1 -- Definition of standardly bound global variable iota
*** WARNING IN "/Users/feeley/meroon/MeroonV3-2016Nov03/_meroon.scm"@963.1 -- Definition of standardly bound global variable last-pair
*** WARNING IN "/Users/feeley/meroon/MeroonV3-2016Nov03/_meroon.scm"@973.1 -- Definition of standardly bound global variable call/cc
```

**Comment by gambiteer** [comment]
That's grand, thanks.  This might prove very useful as more standard procedures are added to the library.

**Comment by gambiteer** [comment]
You get these warnings when building Gambit:
```
*** WARNING IN "/home/lucier/programs/gambit/gambit/gsc/_gsclib.scm"@735.1 -- Definition of standardly bound global variable ##c-code
*** WARNING IN "/home/lucier/programs/gambit/gambit/gsc/_utils.scm"@665.1 -- Definition of standardly bound global variable take
*** WARNING IN "/home/lucier/programs/gambit/gambit/gsc/_utils.scm"@671.1 -- Definition of standardly bound global variable drop
*** WARNING IN "/home/lucier/programs/gambit/gambit/gsc/_utils.scm"@684.1 -- Definition of standardly bound global variable last-pair
```

**Comment by gambiteer** [comment]
Can you convince me why compiling this is not at least worth a warning, if not an error?
```
(define (crapola x)
  32)

(define (crapola y)
  42)
```

**Comment by feeley** [comment]
Is this convincing?

```
$ cat crapola.scm
(define (crapola x)
  32)

(pp (crapola 1))

(define (crapola y)
  42)

(pp (crapola 2))
$ gsc -warnings -exe crapola.scm
*** WARNING IN "/Users/feeley/crapola.scm"@1.1 -- More than one 'define' of global variable crapola
*** WARNING IN "/Users/feeley/crapola.scm"@6.1 -- More than one 'define' of global variable crapola
$ ./crapola
32
42
```

**Comment by gambiteer** [comment]
OK, so the interpreter and the compiler gave different meanings to some programs, and you chose to change the compiler meaning.
Racket made the opposite choice, or at least chose not to change the compiler, and has a catchy phrase something like "The REPL is impossible." to go along with it.
If you have
```
(define (foo x) 42)
(define-macro (bar) (foo 2))
(bar)
```
then this works in the interpreter and not the compiler.  I'm not saying this should work in the compiler, but it does seem strange to give the compiler interpreter semantics in the previous case.

**Comment by feeley** [comment]
The example you give *does not* work in the interpreter.  It happens to work in the REPL if you enter the expressions one at a time because the expansion environment is the interactive environment.
