### ISSUE TITLE
Build failure on Fedora Linux

### ISSUE THREAD

**Issue by vonbrand** [gambit/gambit#725]
Fedora 35, up to date on x86_64. This has been happened for some time now.

./configure --enable-single-host --enable-dynamic-clib --enable-march=native --prefix=$HOME
make

Crashes with:

../gsc-boot -:~~bin=../bin,~~lib=../lib,~~include=../include -f -c  -prelude "(define-cond-expand-feature|enable-type-checking|)(define-cond-expand-feature|disable-auto-forcing|)(define-cond-expand-feature|enable-sharp-dot|)(define-cond-expand-feature|enable-bignum|)(define-cond-expand-feature|enable-ratnum|)(define-cond-expand-feature|enable-cpxnum|)(define-cond-expand-feature|enable-s8vector|)(define-cond-expand-feature|enable-u16vector|)(define-cond-expand-feature|enable-s16vector|)(define-cond-expand-feature|enable-u32vector|)(define-cond-expand-feature|enable-s32vector|)(define-cond-expand-feature|enable-u64vector|)(define-cond-expand-feature|enable-s64vector|)(define-cond-expand-feature|enable-f32vector|)(define-cond-expand-feature|disable-smp|)(##include\"../lib/header.scm\")" _kernel.scm
*** ERROR IN c#macro-expand -- define-prim can't inline ##fxfirst-set-bit

**Comment by feeley** [comment]
This is almost certainly a bootstrapping problem that is caused by using a gsc-boot that is not "new enough".  The best way to solve this problem is to start from scratch with a "git clone ..." as explained on the main page of the repository.  If that does not work just reopen the issue.
