### ISSUE TITLE
Online documentation not accessible

### ISSUE THREAD

**Issue by fuxoft** [gambit/gambit#729]
The page https://staging.gambitscheme.org/4.9.3/ shows two links to current documentation: https://staging.gambitscheme.org/4.9.3/manual/ and https://staging.gambitscheme.org/4.9.3/gambit.pdf - Both of these lead to 404 Not Found error page.

The page https://staging.gambitscheme.org/dev/ shows the following link to documentation: https://staging.gambitscheme.org/dev/manual/ - This liks also leads to 404 Not Found error.

**Comment by belmarca** [comment]
Hi @fuxoft , this has been fixed in the main website, from which you can get the latest manual: https://gambitscheme.org/latest/manual. The links have also been fixed.
