### ISSUE TITLE
Gambit mailingt list link broken on gambitscheme.org

### ISSUE THREAD

**Issue by amirouche** [gambit/gambit#750]
On the page https://gambitscheme.org/wiki/index.php?title=How_to_contribute clicking on `Gambit Mailing list` leads to https://webmail.iro.umontreal.ca/mailman/listinfo/gambit-list that is a 404.

**Comment by amirouche** [comment]
The wiki is read-only.

**Comment by bheesham** [comment]
The mailing list links on the [How to contribute](https://gambitscheme.org/wiki/index.php?title=How_to_contribute) page have been updated.

**Comment by gambiteer** [comment]
So, can this be closed now?

**Comment by bheesham** [comment]
Yes, I believe so.

**Comment by bheesham** [comment]
Thank you!
