### ISSUE TITLE
##vector calls ##list->vector

### ISSUE THREAD

**Issue by gambiteer** [gambit/gambit#752]
I was looking into why `(eq? (vector) (vector))` => `#t` in the compiler and `#f` in the interpreter, so I looked at the code generated by the compiler for `##vector` in `_std.c`, which is
```
#undef ___PH_PROC
#define ___PH_PROC ___H__23__23_vector
#undef ___PH_LBL0
#define ___PH_LBL0 1562
#undef ___PD_ALL
#define ___PD_ALL ___D_FP ___D_R1
#undef ___PR_ALL
#define ___PR_ALL ___R_FP ___R_R1
#undef ___PW_ALL
#define ___PW_ALL ___W_R1
___BEGIN_P_COD
___BEGIN_P_HLBL
___DEF_P_HLBL_INTRO
___DEF_P_HLBL(___L0__23__23_vector)
___DEF_P_HLBL(___L1__23__23_vector)
___END_P_HLBL
___BEGIN_P_SW
___DEF_SLBL(0,___L0__23__23_vector)
   ___IF_NARGS_EQ(0,___SET_R1(___NUL))
   ___GET_REST(0,0,0,0)
___DEF_GLBL(___L__23__23_vector)
   ___POLL(1)
___DEF_SLBL(1,___L1__23__23_vector)
   ___JUMPPRM(___SET_NARGS(1),___PRM__23__23_list_2d__3e_vector)
___END_P_SW
___END_P_COD
```
This looks strange, because `vector` builds the vector from the args with really tweaked, inline code.  Am I missing something?

**Comment by feeley** [comment]
I can think of a few things that could be viewed as strange in the implementation of `vector` and `##vector`.  Can you explain in greater detail the thing that you find strange and that should be fixed?  Note that the code you show above is used when there's a (non-inlined) procedure call to `##vector`, so (at least in some cases) it is necessary to call (something like) `##list->vector`.

**Comment by feeley** [comment]
@gambiteer Can you explain what you find strange?

**Comment by gambiteer** [comment]
I guess I would have expected some unrolling of the argument list with a `case-lambda`:
```
(define ##vector
  (case-lambda
   ((x) (##vector x))
   ((x y) (##vector x y))
   ...
   (args (list->vector args))))
```

**Comment by gambiteer** [comment]
Let’s drop this. It’s not important.
