### ISSUE TITLE
Compiling R7RS

### ISSUE THREAD

**Issue by Sokleidas** [gambit/gambit#757]
Consider the following simple program (R7RS):
```
;; test-r7rs.scm
(define number->list
  (λ (n)
    (let loop ((num n) (acc '()))
      (if (< num 10)
          (cons num acc)
          (let-values (((q r) (truncate/ num 10)))
            (loop q (cons r acc)))))))

(begin
  (display (number->list 123456789))
  (display "\n"))
```
```
$ gsc
Gambit v4.9.4-49-g44d99795

> (load "test-r7rs.scm")
(1 2 3 4 5 6 7 8 9)
".../test-r7rs.scm"
> (exit) 
```
However:
```
$ gsc -:r7rs -debug -exe test-r7rs.scm
$ ./test-r7rs
*** ERROR IN number->list, "test-r7rs.scm"@8.18 -- Operator is not a PROCEDURE
(#!unbound #!unbound)
```
I’m aware of some [discussion](https://mailman.iro.umontreal.ca/pipermail/gambit-list/2019-November/009251.html) on the gambit mailing list, but what is said there doesn’t fix my issue. I guess I miss something. Thank you so much for any help.
Best wishes from Vienna,
Sokleidas

**Comment by feeley** [comment]
The compiler has a partial implementation of the R7RS special forms related to multiple-values.  We are working on a new macro system that will solve this issue.

**Comment by Sokleidas** [comment]
I see, thank you so much for your answer.
