### ISSUE TITLE
Gambit must have a safer version of shell-command

### ISSUE THREAD

**Issue by felipelalli** [gambit/gambit#758]
The fn `shell-command` is a very useful feature to integrate other languages, external libraries, services etc. via CLI commands without dealing with Network, RPC interface or C-interface. However, it's implemented in a very **DANGEROUS** and **UNSAFE** manner. This fn is eqv in Python as `os.system(command)` that is today **deprecated** and **discouraged**. This is dangerous because can allow a malicious user input to escape the shell command and execute arbitrary code, specially if this code runs in a not-jailed server env.

The correct manner to implement this or a similar safer function is something similar `subprocess` in Python:

```
import subprocess
subprocess.run(["ls", "-l"])
```

where you can pass the shell command args as arguments in the function to prevent any undesirable shell injection and possible unauthorized system control.

**Comment by feeley** [comment]
The `shell-command` procedure is not the only way to execute subprocesses but it is the simplest interface (like Python's `os.system` but with the ability to capture the output if a second parameter is set to true).  A subprocess can be created with the `open-process` procedure, or one of the related ones such as `call-with-input-process`.  For example:

```
$ cat test.scm
(pp (shell-command "ls -l"))

(pp (shell-command "ls -l" #t))

(pp (call-with-input-process
     (list path: "ls" arguments: (list "-l"))
     (lambda (port) (read-line port #f))))
$ gsi test.scm
total 8
-rw-r--r--  1 feeley  staff    0 15 Jul 08:15 bar
-rw-r--r--  1 feeley  staff    0 15 Jul 08:15 foo
-rw-r--r--  1 feeley  staff  181 15 Jul 13:11 test.scm
0
(0
 .
 "total 8\n-rw-r--r--  1 feeley  staff    0 15 Jul 08:15 bar\n-rw-r--r--  1 feeley  staff    0 15 Jul 08:15 foo\n-rw-r--r--  1 feeley  staff  181 15 Jul 13:11 test.scm\n")
"total 8\n-rw-r--r--  1 feeley  staff    0 15 Jul 08:15 bar\n-rw-r--r--  1 feeley  staff    0 15 Jul 08:15 foo\n-rw-r--r--  1 feeley  staff  181 15 Jul 13:11 test.scm\n"
```

Removing or deprecating `shell-command` is not a complete solution to the string escaping problem as a programmer can still cause problems with:

```
(call-with-input-process '(path: "sh" arguments: ("-c" "...command...")) read-line)
```

An interesting addition to Gambit would be to add a "sandbox" mode that would disable all dangerous operations such as this (including `delete-file` and even `open-output-file`).  But for general usefulness it is important to keep these possibly dangerous operations.

I'll close this issue but feel free to make suggestions for a sandbox mode.

**Comment by felipelalli** [comment]
Thank you @feeley . I didn't realize it was possible to do something like that. Maybe a mention in the documentation with this example wouldn't be interesting?

**Comment by feeley** [comment]
@felipelalli The Gambit manual does give these examples:

```
> (with-input-from-process "date" read-line)
"Sun Jun 14 15:06:41 EDT 2009"
> (define p (open-process (list path: "ls"
                                arguments: '("../examples"))))
> (read-line p)
"README"
> (read-line p)
"Xlib-simple"
> (close-port p)
> (define p (open-process "/usr/bin/dc"))
> (display "2 100 ^ p\n" p)
> (force-output p)
> (read-line p)
"1267650600228229401496703205376"
```

For `shell-command` these examples are given:

```
> (shell-command "ls -sk f*.scm")
4 fact.scm   4 fib.scm
0
> (shell-command "ls -sk f*.scm" #t)
(0 . "4 fact.scm   4 fib.scm\n")
> (shell-command "echo x\\\\\\\\y $HOME" #t)
(0 . "x\\y /Users/feeley\n")
```

Is this insufficient?

**Comment by felipelalli** [comment]
I'm saying in `shell-command` something like "See also `with-input-from-process`".
