### ISSUE TITLE
Test failure on Intel Mac with gcc-11.2.0

### ISSUE THREAD

**Issue by gambiteer** [gambit/gambit#796]
`make ut` shows the failure
```
------------ TEST 11 (run unit tests)
/Library/Developer/CommandLineTools/usr/bin/make ut
DYLD_LIBRARY_PATH=../lib:../gsi:../gsc: ../gsi/gsi -:tl,~~bin=../bin,~~lib=../lib,~~include=../include -f ./run-unit-tests.scm
[265|  0]  92% ██████████████▋  7.8s 13-modules/prim_filesystem.scmdyld[24816]: missing symbol called

*** FAILED 13-modules/prim_filesystem.scm WITH EXIT CODE HI=0 LO=6
[287|  1] 100% ████████████████ 8.7s
FAILED 1 UNIT TESTS OUT OF 288 (.3%)
make[2]: *** [ut] Error 1
make[1]: *** [test11] Error 2
make: *** [check] Error 2
```
How do I isolate what the precise error is here?

BTW, with the new compiler options cc1 compiling srfi/231 took 3:30 and 6GB of RAM with
```
/usr/local/gcc-11.2.0/bin/gcc -v
Using built-in specs.
COLLECT_GCC=/usr/local/gcc-11.2.0/bin/gcc
COLLECT_LTO_WRAPPER=/usr/local/gcc-11.2.0/libexec/gcc/x86_64-apple-darwin20.6.0/11.2.0/lto-wrapper
Target: x86_64-apple-darwin20.6.0
Configured with: ../../gcc-11.2.0/configure --disable-multilib --with-sysroot=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk --without-build-config --enable-languages=c --prefix=/usr/local/gcc-11.2.0/
Thread model: posix
Supported LTO compression algorithms: zlib
gcc version 11.2.0 (GCC) 
```
I didn't time the whole build, but it was significant.

**Comment by gambiteer** [comment]
About new build times, with an up-to-date git repository and the build script
```
make clean && \
rm -rf boot gsc-boot && \
git pull && \
make -j12  && \
make -j12 doc && \
make  check
```
on a 2018 Mac Mini with 6-core/12-thread i7, it takes
```
2473.845u 175.559s 13:53.22 317.9%	0+0k 0+0io 56053pf+0w
```
to build.
I've figured out how to run that test by itself, but it's not any more illuminating:
```
env DYLD_LIBRARY_PATH=../lib:../gsi:../gsc: ../gsi/gsi -:tl,~~bin=../bin,~~lib=../lib,~~include=../include unit-tests/13-modules/prim_filesystem.scm
dyld[9887]: missing symbol called
Abort
```

**Comment by gambiteer** [comment]
With the same checkout, on a Macbook Pro with M1 Max and the command
```
rm -rf boot gsc-boot && \
git pull && \
make -j10 && \
make -j8 doc && \
make  check
```
it takes
```
1113.557u 198.126s 7:30.35 291.2%	0+0k 0+0io 10541pf+0w
```
to build.
Cutting the build time roughly in half makes the build time seem tolerable.

**Comment by feeley** [comment]
On the M1 Max are you using gcc-11.2.0?  I assume not.

**Comment by gambiteer** [comment]
You're right, that was with `gcc-12`, but with `gcc-11` it's about the same:
```
1116.803u 228.979s 7:36.72 294.6%	0+0k 0+0io 5140pf+0w

```
that's with
```
v4.9.4-137-g646ad348 20221111190520 arm-apple-darwin21.6.0 "./configure 'CC=gcc-11' '--enable-single-host' '--enable-march=native' '--enable-multiple-versions' '--enable-shared' '--enable-dynamic-clib'"

```

**Comment by feeley** [comment]
So with gcc-11.2.0 + x86-64 + macOS + `-O2 -fno-gcse` the issue happens, but with gcc-11.2.0 + x86-64 + macOS + `-O1` it works... right?  Do you remember that the gcc folks said there was a bug with gcc-11 + x86-64 + macOS?

**Comment by gambiteer** [comment]
> So with gcc-11.2.0 + x86-64 + macOS + `-O2 -fno-gcse` the issue happens, but with gcc-11.2.0 + x86-64 + macOS + `-O1` it works... right?

Yes, with `-O2 -fno-gcse` there is a long build time, with `-O1` there is not.

> Do you remember that the gcc folks said there was a bug with gcc-11 + x86-64 + macOS?

No, not really.

Maybe I should try the comparison on my Linux box.

**Comment by gambiteer** [comment]
Here's the timing with gcc-11.2.0 + x86-64 + macOS + `-O1`:
```
1478.718u 121.224s 6:35.97 404.0%	0+0k 0+0io 51173pf+0w
```
the configure command:
```
v4.9.4-137-g646ad348 20221111190520 x86_64-apple-darwin21.6.0 "./configure 'CC=/usr/local/gcc-11.2.0/bin/gcc' '--enable-march=native' '--enable-dynamic-clib' '--enable-single-host' '--enable-multiple-versions' '--enable-shared' '--enable-c-opt=-O1'"
```

**Comment by gambiteer** [comment]
Heres the time of the latest checkout on a Linux box that's slightly slower than my Mac Mini, so gcc-11.3.0 + x86-64 + macOS + `-O2 -fno-gcse`:
```
2504.300u 78.587s 16:22.39 262.9%	0+0k 248024+1925456io 1441pf+0w
```
The configure command is
```
./configure 'LIBS=-lm' '--enable-march=native' '--enable-dynamic-clib' '--enable-single-host' '--enable-multiple-versions' '--enable-shared'
```
So it seems the problem is gcc 11 or 12 on x86-64 with `-O2 -fno-gcse`.
Or at least it doesn't show up on Mac M1 Max.

**Comment by gambiteer** [comment]
Yeah, `-O1` is a lot faster even on the Linux box.  With
```
    36	14:59	./configure 'LIBS=-lm' '--enable-march=native' '--enable-dynamic-clib' '--enable-single-host' '--enable-multiple-versions' '--enable-shared' --enable-c-opt=-O1
    37	15:00	time update-gambit-git
```
the time is
```
1504.625u 50.451s 7:15.02 357.4%	0+0k 0+1923688io 386pf+0w
```

**Comment by feeley** [comment]
I'm experimenting with using `-O1 -fexpensive-optimizations ...` instead of `-O2 -fno-...`.  On my machine it seems to be twice as fast to compile and as far as I can tell it avoids the merging of all the computed gotos.  I've pushed a commit for this to see how it does on Forensics.

**Comment by gambiteer** [comment]
This appears to be the same problem as https://github.com/gambit/gambit/issues/794, so I'm going to close this ticket.
