### ISSUE TITLE
SRFI/14 does not support char-set outside latin1 encoding

### ISSUE THREAD

**Issue by FredericHamel** [gambit/gambit#799]
Implement a char-set structure that allow sets outside latin1, which is required by SRFI/115 to represent the Hangul char-set.

- The char-set structure should to be compact.
- Operations on char-set should be efficient (ex. char-set-union, char-set-complement, …).

**Comment by feeley** [comment]
I have been working on an implementation of SRFI-14 that supports all Unicode.  That work is currently on pause but I expect to return to it within a 1-2 month period.

**Comment by feeley** [comment]
Fixed by commits 5ef6d4e05cad88bde25e2527f3d58380e864d970 and 94be9216ac580768a5d0a96acc911072d3ef4e45.
