### ISSUE TITLE
UTF-8 validation varies by port type

### ISSUE THREAD

**Issue by jeffhhk** [gambit/gambit#805]
Here I get an error:

    echo "6WzpbWVudAo=" | base64 --decode > repro.txt
    hd repro.txt 
        00000000  e9 6c e9 6d 65 6e 74 0a                           |.l.ment.|
    gsi -e '(define p (open-input-file "repro.txt")) (display (read-line p))'
        *** ERROR IN ##read-line -- Can't convert from C UTF-8-string
        (read-char '#<input-port #2 "/home/jeff/srchome/pmi/data/r6rs-email/repro.txt">)

But the same error does not seem to occur if the port is created with open-input-bytevector instead:

    (read-line (open-input-bytevector #u8(#xe9 #x6c #xe9 #x6d #x65 #x6e #x74 #x0a)))

If I type the codepoint e9 on the command line, it gets encoded with a second character:

    echo "é" | hd
        00000000  c3 a9 0a                                          |...|

as this page indicates for the character's utf-8 encoding:

    https://www.fileformat.info/info/unicode/char/e9/index.htm

**Comment by feeley** [comment]
By default ports opened from files use the UTF-8 character encoding.  The sequence of bytes `e9 6c e9 6d 65 6e 74 0a` is not a valid UTF-8 encoding.  It is however the ISO-8859-1 encoding of the text `élément\n`.  There are several ways to specify the use of the ISO-8859-1 character encoding:

```
$ gsi -e '(define p (open-input-file (list path: "rt" char-encoding: (quote ISO-8859-1)))) (println (read-line p))' 
élément
```

or this:

```
$ gsi -:help 2>&1 | tail -12
  io-settings=[IO...]        set general IO settings, shorthand: i[IO...]
  file-settings=[IO...]      set general file IO settings, shorthand: f[IO...]
  stdio-settings=[IO...]     set general stdio IO settings, shorthand: -[IO...]
  0=[IO...]                  set stdin IO settings (1 and 2 for stdout/stderr)
  terminal-settings=[IO...]  set terminal IO settings, shorthand: t[IO...]
where IO is one of
  A|1|2|4|6|8|U   character encoding (ASCII|ISO-8859-1|UCS-2/4|UTF-16/8|UTF)
  L               use LC_ALL, LC_CTYPE, and LANG env vars to set char encoding
  l|c|cl          end-of-line encoding (LF|CR|CR-LF)
  u|n|f           buffering (unbuffered|newline buffered|fully buffered)
  r|R             enable character encoding errors (on|off)
  e|E             [for terminals only] enable line-editing (on|off)
$ gsi -:file-settings=1 -e '(define p (open-input-file "repro.txt")) (println (read-line p))' 
élément
```

or this:

```
$ export LC_ALL=en_us.latin1
$ export GAMBOPT=file-settings=L
$ gsi -e '(define p (open-input-file "repro.txt")) (println (read-line p))'
élément
```
