### ISSUE TITLE
How to bind foundationdb client C library?

### ISSUE THREAD

**Issue by amirouche** [gambit/gambit#808]
I created bindings for CPython with asyncio support, Guile, and Chez, but I struggle to get started with Gambit.

There is an official C library client that other language should rely on because upstream offers no guarantees regarding the network protocol between the client, and the database server.

The C client API has two modes of operations, blocking, and non-blocking, both approach rely on a POSIX thread running the heavy-duty part of the interaction with the server, quoting the official documentation:

> The FoundationDB client library performs most tasks on a singleton thread (which usually will be a different thread than your application runs on). These functions are used to configure, start and stop the FoundationDB event loop on this thread.

Here is a snippet from Chez bindings demonstrating its use:

```scheme
    (define fdb-run-network
      ;; XXX: Here __collect_safe is required, otherwise the network
      ;; thread will lock the other threads during garbage collection.
      (let ((func (foreign-procedure __collect_safe "fdb_run_network" () int)))
        (lambda ()
          (check (func)))))

    (define %network-thread #f)

    (define (fdb-init!)
      (fdb-select-api-version 630)
      (fdb-setup-network!)
      (fork-thread (lambda () (fdb-run-network))))
```

When the client API is used in blocking mode, everything happens in user thread, here is an example:

```scheme
    (define (fdb-ref tx key)
      ;; Issue the request to fetch the key associated with KEY
      (let ((future (fdb-transaction-get (transaction-pointer tx)
                                         key
                                         #f)))
        ;; Wait for completion
        (fdb-future-block-until-ready* future)
        (let ((error (fdb-future-get-error future)))
          (if (fxzero? error)
              (let ((value (fdb-future-get-value future)))
                (fdb-future-destroy future)
                value)
               (begin
                 (fdb-future-destroy future)
                 (fdb-error error))))))
```

My understanding is that kind of code in Gambit with block all gambit threads, that is not what I want.

When using non-blocking code, a callback is registred against `future`, then when the future is ready, the **network thread** will execute the callback, here is the python code that does that:

```python
async def get(tx, key):
    assert isinstance(tx, Transaction)
    assert isinstance(key, bytes)
    # request the value associated with KEY
    fdb_future = lib.fdb_transaction_get(
        tx.pointer, key, len(key), tx.snapshot
    )
    # Create a python future, to notify this thread, the user thread,
    # that the request was completed by the network thread
    aio_future = _loop.create_future()
    handle = ffi.new_handle(aio_future)
    # Against `fdb_future`  register the python callback `_on_transaction_get`
    lib.fdb_future_set_callback(fdb_future, _on_transaction_get, handle)
    # wait that the python future is ready...
    out = await aio_future
    return out

# That is the callback running in the network thread, 
# when the above fdb future is complete...

@ffi.callback("void(FDBFuture *, void *)")
def _on_transaction_get(fdb_future, aio_future):
    aio_future = ffi.from_handle(aio_future)
    present = ffi.new("fdb_bool_t *")
    value = ffi.new("uint8_t **")
    value_length = ffi.new("int *")
    error = lib.fdb_future_get_value(fdb_future, present, value, value_length)
    if error == 0:
        if present[0] == 0:
            _loop.call_soon_threadsafe(aio_future.set_result, None)
            lib.fdb_future_destroy(fdb_future)
        else:
            out = bytes(ffi.buffer(value[0], value_length[0]))
            # Mind the call_soon_threadsafe
            _loop.call_soon_threadsafe(aio_future.set_result, out)
            lib.fdb_future_destroy(fdb_future)
    else:
        # Mind the call_soon_threadsafe
        _loop.call_soon_threadsafe(aio_future.set_exception, FoundException(error))
        lib.fdb_future_destroy(fdb_future)
```

ref: https://docs.python.org/3/library/asyncio-eventloop.html#asyncio.loop.call_soon_threadsafe

Note: CPython will release its Global Interpreter Lock on C FFI calls, and will not block GC for some reason.

I am looking for a way to implement FoundationDB client re-using the official C library. Please advise.

**Comment by belmarca** [comment]
Hi Amirouche,

I do not understand what is your goal. What is the relationship between CPython and FoundationDB? If you are trying to interface Gambit with CPython, take a look at https://github.com/gambit/python. If you are trying to interface with a C library, how is the C FFI not suitable?

**Comment by amirouche** [comment]
Reading through the documentation, and the configure usage helps. If I understand correctly how SMP works, there is nothing special to do.

I will re-open if necessary (possibly much later this year)

:+1:
