### ISSUE TITLE
SRFI 64 broken

### ISSUE THREAD

**Issue by falsifian** [gambit/gambit#811]
I run the command `gsi -:r7rs f.scm` with the following in `f.scm`:
```
(import (scheme base)
        (srfi 64))

(test-begin "tests" 1)
(test-eqv 0 0)
(test-end "tests")
```
The output I see is `*** ERROR IN "f.scm"@4.2 -- Unbound variable: _test#test-begin`.

This is gambit-4.9.4 on OpenBSD-current. The same program works fine with Chibi scheme (using `(srfi 64)` from snow-fort.org).

**Comment by falsifian** [comment]
Is this extra `(import (rename only (_test...)` line in the SRFI 64 test still needed? https://github.com/gambit/gambit/blob/master/lib/srfi/64/test/test.scm#L12

(@gambiteer pointed that line out on Gitter a couple of weeks ago as the likely reason the SRFI 64 test was passing even though SRFI 64 was broken.)

**Comment by gambiteer** [comment]
Everything is good now, Marc explained on gutter January 9, beginning “The issue is now fixed.” That line is needed in the test.
