### ISSUE TITLE
syntax question regarding the cc-options: argument to compile-file

### ISSUE THREAD

**Issue by DavidCase** [gambit/gambit#817]
From the documentation I got the impression that all the options should be in a single string. But when I tried appending two options I got an error. I tried again, this time putting a space between the two options and got no error but I have no idea if the compiler used both options or just the first one. Does anyone know the proper syntax for this? An example would be most helpful.

**Comment by gambiteer** [comment]
Can you show us what command line you gave and the error you got?  The documentation does give some examples, so I can't tell what the problem is.

**Comment by DavidCase** [comment]
I'm running Gambit in Aquamacs, not from a command line. Here's a summary of the 3 methods I've tried. As you can see, method 1 generates and error but neither method 2 or 3 do. But I still have no way of knowing whether BOTH options were applied by the compiler. So which syntax is correct, 2 or 3?

;; ---------------------------------------------------------------------
;;  method 1 - string appending the 2 options with no space between
;; ---------------------------------------------------------------------

> (compile-file
   source
   output: (make-path object-dir "")
   cc-options: (string-append "-O1" "-D___SINGLE_HOST" ))

> beginning compilation of /Volumes/Dave's Ego/Programming/Gambit/MandelRender/
compiling - [method]/cartesian.scm
error: invalid integral value '1-D___SINGLE_HOST' in '-O1-D___SINGLE_HOST'
error: invalid integral value '1-D___SINGLE_HOST' in '-O1-D___SINGLE_HOST'
*** ERROR IN for-each -- target compilation or link failed while compiling "/Volumes/Dave's Ego/Programming/Gambit/MandelRender/[method]/cartesian.scm"

;; ---------------------------------------------------------------------
;; method 2 - string appending the 2 options with a space in between
;; ---------------------------------------------------------------------

> (compile-file
   source
   output: (make-path object-dir "")
   cc-options: (string-append "-O1" " " "-D___SINGLE_HOST" ))

> beginning compilation of /Volumes/Dave's Ego/Programming/Gambit/MandelRender/
compiling - [method]/cartesian.scm
compilation complete
"/Volumes/Dave's Ego/Programming/Gambit/MandelRender/[source]/compile.scm"

;; ---------------------------------------------------------------------
;; method 3 - putting the 2 options in separately
;; ---------------------------------------------------------------------

> (compile-file
   source
   output: (make-path object-dir "")
   cc-options: "-O1" "-D___SINGLE_HOST" )

> beginning compilation of /Volumes/Dave's Ego/Programming/Gambit/MandelRender/
compiling - [method]/cartesian.scm
compilation complete
"/Volumes/Dave's Ego/Programming/Gambit/MandelRender/[source]/compile.scm"

**Comment by gambiteer** [comment]
2.

**Comment by feeley** [comment]
The `cc-options:` parameter is either a string or a list of strings. If you want to pass several options you should pass a list. From memory this is for portability because of escaping issues that are different on unix and Windows.

**Comment by feeley** [comment]
And yes option 2 is correct if you want to pass a single string.  If you add the option `-D___GAMBIT_H` at the end of your options you should see the compilation fail, so that can be a way to test that the option makes its way to the C compiler command-line.

**Comment by DavidCase** [comment]
Thank to you all. Just to make sure that I've got the gist of it, I can pass either 
(1) cc-options: "-O1 -D___SINGLE_HOST"   or 
(2) cc-options: '("-O1" "-D___SINGLE_HOST")  ,
but (2) is preferable due to portability issues. Correct?

While I'm at it, are there any other compiler options that improve speed performance? I need all I can get. So far the
"-D___SINGLE_HOST" option has had the most effect.

**Comment by DavidCase** [comment]
I'm just now doing some testing. The list of strings option did not work -
> (compile-file
          source
          output: (make-path object-dir "")
         cc-options: '("-O1" "-D___SINGLE_HOST" "-D___GAMBIT_H"))

> beginning compilation of /Volumes/Dave's Ego/Programming/Gambit/MandelRender/
   compiling - [method]/cartesian.scm
   *** ERROR IN for-each -- string expected for cc-options: parameter
   
Next test -

> (compile-file
  	     source
  	     output: (make-path object-dir "")
  	     cc-options: "-O1" "-D___SINGLE_HOST" "-D___GAMBIT_H")

> beginning compilation of /Volumes/Dave's Ego/Programming/Gambit/MandelRender/
compiling - [method]/cartesian.scm
compilation complete
"/Volumes/Dave's Ego/Programming/Gambit/MandelRender/[source]/compile.scm"

No errors, but there should have been one if the compiler got all the options.

Last test -

> (compile-file
  	     source
  	     output: (make-path object-dir "")
  	     cc-options: "-O1 -D___SINGLE_HOST -D___GAMBIT_H")>


> beginning compilation of /Volumes/Dave's Ego/Programming/Gambit/MandelRender/
compiling - [method]/cartesian.scm
../[method]/cartesian.c:52:1: error: expected function body after function declarator
___NEED_SYM(___S_cartesian)
^
1 error generated.
*** ERROR IN for-each -- target compilation or link failed while compiling "/Volumes/Dave's Ego/Programming/Gambit/MandelRender/[method]/cartesian.scm"

It would seem that a string of options with a space between options is the way to go.

**Comment by feeley** [comment]
Here is my test which shows that it is possible to use a list of options:

```
$ cat fib.scm
(define (fib n)
  (if (< n 2)
      n
      (+ (fib (- n 1))
         (fib (- n 2)))))
   
(println (time (fib 40)))
$ gsc
Gambit v4.9.4-175-g7c288417

> (load (compile-file "fib.scm"))
(time (fib 40))
    2.099329 secs real time
    2.093573 secs cpu time (2.087570 user, 0.006003 system)
    no collections
    64 bytes allocated
    1 minor fault
    no major faults
    5038387036 cpu cycles
102334155
"/Users/feeley/fib.o1"
> (load (compile-file "fib.scm" cc-options: "-D___INLINE_JUMPS"))
(time (fib 40))
    1.946818 secs real time
    1.940807 secs cpu time (1.935027 user, 0.005780 system)
    no collections
    64 bytes allocated
    1 minor fault
    no major faults
    4672365976 cpu cycles
102334155
"/Users/feeley/fib.o2"
> (load (compile-file "fib.scm" cc-options: "-D___DONT_USE_builtin_expect"))
(time (fib 40))
    1.902134 secs real time
    1.898275 secs cpu time (1.893220 user, 0.005055 system)
    no collections
    64 bytes allocated
    1 minor fault
    no major faults
    4565050116 cpu cycles
102334155
"/Users/feeley/fib.o3"
> (load (compile-file "fib.scm" cc-options: '("-D___DONT_USE_builtin_expect" "-D___INLINE_JUMPS")))
(time (fib 40))
    2.192955 secs real time
    2.105634 secs cpu time (2.094867 user, 0.010767 system)
    no collections
    64 bytes allocated
    no minor faults
    no major faults
    5093124872 cpu cycles
102334155
"/Users/feeley/fib.o4"
```

This also shows that the selection of the fastest combination of options is a black art.

By the way, if you have configured and built Gambit with `--enable-single-host` then you don't need to add `cc-options: "-D___SINGLE_HOST"`.

**Comment by DavidCase** [comment]
Yes, it works on your system. It didn't work on mine, running 4.9.3. Don't see why it would matter, but I noticed we are using different orderings for the arguments to <compile-file>. 

I've already noticed the 'black art' thing, some compiler options seem to work at cross purposes to each other. I haven't tried 4.9.4 yet since there is no MacOS installer for it and I don't know anything about using Terminal to build it that way.

**Comment by feeley** [comment]
Unfortunately we haven't maintained the building of installers since v4.9.3. However, you can get a fully built system through the following link:

https://github.com/gambit/gambit/suites/10331914393/artifacts/508741354

It should lead to a file that you can uncompress (with the command `tar zxf ...` if I recall correctly). The files `gsi` and `gsc` will be in the directory that is created.

**Comment by DavidCase** [comment]
Thanks, I've got in my Downloads. And thanks for all of your help!
