### ISSUE TITLE
No compile-time evaluation of fxarithmetic-shift-left with (declare (not safe))

### ISSUE THREAD

**Issue by gambiteer** [gambit/gambit#819]
I'm writing some code that assumes, e.g., that
```
               ('#<procedure #18 ##fxarithmetic-shift-left> 31 10)
```
is evaluated at compile time.

I'm willing to imitate the treatment of some other primitive that's evaluated at compile time by the compiler, but point me somewhere to look.

Brad

**Comment by feeley** [comment]
The code should go in `gsc/_prims.scm`. Here is how constant folding of `square`, `fxsquare`, etc is defined:

```
(def-simp "square"           (constant-folder-gen square     num?))
(def-simp "fxwrapsquare"     (constant-folder-fix square     fix32?))
(def-simp "fxsquare"         (constant-folder-fix square     fix32?))
(def-simp "fxsquare?"        (constant-folder-fix square     fix32?))
(def-simp "flsquare"         (constant-folder-flo square     flo?))
```

The first parameter of `constant-folder-gen/-fix/-flo` is a procedure that does the operation when given Scheme values. The second parameter is the `type-pattern` (to detect the cases that can be constant folded). So to do constant folding of the `arithmetic-shift` related primitives this code should be added to `gsc/_prims.scm` where other `def-simp` are located:

```
(let ()
  (define (nonneg-fix32? x) (and (fix32? x) (>= x 0)))
  (define (shift-left n shift) (arithmetic-shift n shift))
  (define (shift-left? n shift) (and (>= shift 0) (shift-left n shift)))
  (define (shift-right n shift) (arithmetic-shift n (- shift)))
  (define (shift-right? n shift) (and (>= shift 0) (shift-right n shift)))
  (def-simp "arithmetic-shift"          (constant-folder-gen shift-left int?))
  (def-simp "fxarithmetic-shift"        (constant-folder-fix shift-left fix32?))
  (def-simp "fxarithmetic-shift?"       (constant-folder-fix shift-left fix32?))
  (def-simp "fxarithmetic-shift-left"   (constant-folder-fix shift-left (list fix32? nonneg-fix32?)))
  (def-simp "fxarithmetic-shift-left?"  (constant-folder-fix shift-left? fix32?))
  (def-simp "fxarithmetic-shift-right"  (constant-folder-fix shift-right (list fix32? nonneg-fix32?)))
  (def-simp "fxarithmetic-shift-right?" (constant-folder-fix shift-right? fix32?)))
```

It would be interesting to add constant folding of any other primitive that is missing.

By the way, for your code to be portable (to 32 and 64 bit machines) you should use `(arithmetic-shift const1 const2)` when you don't know if the result is a fixnum for 32 bit machine.

Also, I am working on a generalized type inference for Gambit that will subsume the current constant folding approach. It will allow constant folding when some of the parameters are not constants, for example `(* n 0)` => `0` whether `n` is a constant or not.

**Comment by gambiteer** [comment]
> By the way, for your code to be portable (to 32 and 64 bit machines) you should use `(arithmetic-shift const1 const2)` when you don't know if the result is a fixnum for 32 bit machine.

I do know that in this case (maximum is 23 bits).

**Comment by gambiteer** [comment]
I followed this suggestion here: https://github.com/gambit/gambit/commit/266c81f38c071eb3bb4fdd922f99cbfa7a5b2e28
