### ISSUE TITLE
u16vector-set! returns the vector when compiled!

### ISSUE THREAD

**Issue by gambiteer** [gambit/gambit#820]
Here's a file `u16-test.scm`:
```
(declare (standard-bindings)
  (extended-bindings)
  (block)
  (not safe))

(define (A_ a v i j)
  (u16vector-set! a (+ (* i 5) j) v))
```
Here's a transcript:
```
heine:~/lang/scheme/srfi-231/srfi-231-temp> gsc
Gambit v4.9.4-174-g82131559

> (load "u16-test.scm")                    ;;; <<< load the .scm source file
"/home/lucier/lang/scheme/srfi-231/srfi-231-temp/u16-test.scm"
> (pp A_)
(lambda (a v i j) (u16vector-set! a (+ (* i 5) j) v))
> (define a (make-u16vector 25 5))
> a     
#u16(5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5)
> (A_ a 3 4 2)              ;;; <<<<<<<<<<<<<<<< returns (void), which is good
> a
#u16(5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 3 5 5)
> (compile-file "u16-test")             ;;; <<<< compile the file
"/home/lucier/lang/scheme/srfi-231/srfi-231-temp/u16-test.o1"
> (load "u16-test")                        ;;; load the compiled file
"/home/lucier/lang/scheme/srfi-231/srfi-231-temp/u16-test.o1"
> (A_ a 3 2 2)
#u16(5 5 5 5 5 5 5 5 5 5 5 5 3 5 5 5 5 5 5 5 5 5 3 5 5) ;;; <<< What the hell?!? it returns the u16vector!
```
What's going on, Marc?

This is screwing up my array package.

**Comment by feeley** [comment]
It is not a bug, it's a feature! In Scheme the result of `vector-set!` (and related procedures) is undefined.  If you want a specific result, like void, then you should write `(begin (vector-set! v i x) (void))`.

**Comment by gambiteer** [comment]
Marc:  Let's not talk BS here.  Everybody expects consistency between the interpreter and the compiler, and everybody expects `<whatever>-set!` to return `(void)`.  People actually write code that they rely on Gambit to compile in a certain way.

How the hell did the compiler do this, anyway?

**Comment by gambiteer** [comment]
Let's leave it open as an "issue" even if you don't think it's a "bug".

**Comment by gambiteer** [comment]
The case where I found it first, the vector had a million elements, scrolling down the repl.  Took me a while to figure out what was going on.

**Comment by feeley** [comment]
This is a hard thing to change because `(vector-set! v i x)` is specialized to `(##vector-set! v i x)` and `##vector-set!` returns `v` (because it is useful in some contexts and the spec says the return value is undefined).  The runtime system uses this feature in certain places, so it is not a trivial fix.

**Comment by gambiteer** [comment]
OK, why does the interpreter return `(void)`?

**Comment by feeley** [comment]
Because the interpreter is calling the procedure `vector-set!` and the compiler is inlining it.  The procedure is defined like this:

```
              `(define-procedure (,vect-set!
                                  (,name (and ,name mutable))
                                  (k (index-range
                                      0
                                      (,prim-vect-length ,name)))
                                  (,elem-name ,elem-type))
                 (,prim-vect-set! ,name k ,elem-name)
                 (void))
```

**Comment by gambiteer** [comment]
Thanks.

If I get rid of all declarations except `standard-bindings` I get
```
heine:~/lang/scheme/srfi-231/srfi-231-temp> gsc -keep-temp -expansion u16-test.scm
Expansion:

(define A_
  (lambda (a v i j)
    (let ((temp.7 (let ((temp.3 (if ('#<procedure #2 ##fixnum?> i) (let ((temp.2 ('#<procedure #3 ##fx*?> i 5))) (if temp.2 temp.2 ('#<procedure #4 *> i 5))) ('#<procedure #4 *> i 5))))
                    (if (and ('#<procedure #2 ##fixnum?> j) ('#<procedure #2 ##fixnum?> temp.3))
                        (let ((temp.5 ('#<procedure #5 ##fx+?> temp.3 j))) (if temp.5 temp.5 ('#<procedure #6 +> temp.3 j)))
                        (if (and ('#<procedure #7 ##flonum?> j) ('#<procedure #7 ##flonum?> temp.3)) ('#<procedure #8 ##fl+> temp.3 j) ('#<procedure #6 +> temp.3 j))))))
      (if (and ('#<procedure #9 ##u16vector?> a)
               (and ('#<procedure #10 ##mutable?> a)
                    (and (and ('#<procedure #2 ##fixnum?> temp.7) (and ('#<procedure #11 ##fx<=> 0 temp.7) ('#<procedure #12 ##fx<> temp.7 ('#<procedure #13 ##u16vector-length> a))))
                         (and ('#<procedure #2 ##fixnum?> v) (and ('#<procedure #11 ##fx<=> 0 v) ('#<procedure #11 ##fx<=> v 65535))))))
          (begin ('#<procedure #14 ##u16vector-set!> a temp.7 v) #!void)
          ('#<procedure #15 u16vector-set!> a temp.7 v)))))
```
and `#!void` is returned by `u16vector-set!`; if I add `(not safe)` then I get
```
heine:~/lang/scheme/srfi-231/srfi-231-temp> gsc -keep-temp -expansion u16-test.scm
Expansion:

(define A_
  (lambda (a v i j)
    ('#<procedure #2 ##u16vector-set!>
     a
     (let ((temp.3 (if ('#<procedure #3 ##fixnum?> i) (let ((temp.2 ('#<procedure #4 ##fx*?> i 5))) (if temp.2 temp.2 ('#<procedure #5 ##*> i 5))) ('#<procedure #5 ##*> i 5))))
       (if (and ('#<procedure #3 ##fixnum?> j) ('#<procedure #3 ##fixnum?> temp.3))
           (let ((temp.5 ('#<procedure #6 ##fx+?> temp.3 j))) (if temp.5 temp.5 ('#<procedure #7 ##+> temp.3 j)))
           (if (and ('#<procedure #8 ##flonum?> j) ('#<procedure #8 ##flonum?> temp.3)) ('#<procedure #9 ##fl+> temp.3 j) ('#<procedure #7 ##+> temp.3 j))))
     v)))
```
and `u6vector-set!` does not return `#!void`.

To state things flatly, I don't think a `(not safe)` declaration should change the return value of valid code.

I thought of doing a coarse experiment, to see what would break with the C backend if I changed the `___*VECTORSET` macros in `gambit.h.in` to return `___VOID`.  Perhaps you can answer a question.  I see:
```
#define ___VECTORREF(v,i)*(___WORD*)(((___WORD)___BODY_AS(v,___tSUBTYPED))+((i)<<(___LWS-___TB)))
#define ___VECTORSET(v,i,val)*(___WORD*)(((___WORD)___BODY_AS(v,___tSUBTYPED))+((i)<<(___LWS-___TB)))=val;
```
so `___VECTORREF` is an expression, `___VECTORSET` is a statement (correct me at any point if I say something wrong).

To do my experiment, would it be enough to redefine
```
#define ___VECTORSET(v,i,val)*(___WORD*)(((___WORD)___BODY_AS(v,___tSUBTYPED))+((i)<<(___LWS-___TB)))=val, ___VOID;
```
and do the same for the other `___*VECTORSET` macros?

**Comment by gambiteer** [comment]
I see that wouldn't work, the C code generated for `(not safe)` is
```
   ___U16VECTORSET(___STK(0),___R2,___R1) ___SET_R1(___STK(0))
```
with just `(standard-bindings)`, it's
```
   ___U16VECTORSET(___STK(0),___R2,___R1)
   ___SET_R1(___VOID)
```
So the compiler must be doing something special.

**Comment by feeley** [comment]
The behaviour of `##vector-set!` of returning its first argument is shared by other primitives including `##vector-shrink!`, `##string-set!`, `##set-cdr!`, `##set-box!`, `##bignum.mdigit-set!`, `##symbol-hash-set!`, `##closure-set!`, `##structure-set!`, `##subtype-set!`, and probably many others.  This feature is useful for things like:

```
> (##subtype-set! (u8vector 0 1 250 255) 20) ;; convert a u8vector to s8vector
#s8(0 1 -6 -1)
> (##vector-set! (##vector-set! (##vector-set! (vector 0 0 0 0) 1 11) 2 22) 3 33)
#(0 11 22 33)
> (##vector-shrink! (vector 1 2 3 4) 2)
#(1 2)
```

I guess what could be done is removing the specialization `vector-set!` -> `##vector-set!` in `gsc/_prims.scm`:

```
(def-spec "vector-set!"        (spec-u "##vector-set!"))
```

and similarly for the others.  Then it would be `make-ref-set!-cas!-inc!-expander` in `make-vector-expanders` in `gsc/_prims.scm` that would expand `(vector-set! a b c)` to `(begin (##vector-set! a b c) (##void))` when in the scope of `(declare (not safe))`.

However I don't like this because the specialization `vector-set!` -> `##vector-set!` can also (and should) be achieved by a `(include "~~lib/gambit/prim/vector#.scm")`, which gives finer control than `(declare (standard-bindings))`.

So perhaps the right approach is to introduce new primitives for this feature, such as `##vector-set!-vector` that returns the vector being set. Although I haven't found a need for it I can imagine also having `##vector-set!-value` that returns the value being set.  A plain `##vector-set!` would return void.

**Comment by gambiteer** [comment]
I thought I'd try to massage the SRFI 231 code for now to "fix" this by going through the code and adding `(void)` wherever the "result" of `<whatever>-set!` is returned, but there is this series of macros:
```
    ;;; we write the following three macros to specialize the setters and getters in the
    ;;; non-safe case to reduce one more function call.

    (define-macro (expand-storage-class original-suffix replacement-suffix expr)

      (define (symbol-append . args)
        (string->symbol (apply string-append (map (lambda (x) (if (symbol? x) (symbol->string x) x)) args))))

      (define (replace old-symbol new-symbol expr)
        (let loop ((expr expr))
          (cond ((pair? expr)           ;; we don't use map because of dotted argument list in general setter
                 (cons (loop (car expr))
                       (loop (cdr expr))))
                ((eq? expr old-symbol)
                 new-symbol)
                (else
                 expr))))

      `(cond ,@(map (lambda (name prefix)
                      `((eq? storage-class ,(symbol-append name '-storage-class))
                        ,(replace (symbol-append 'storage-class original-suffix)
                                  (symbol-append prefix         replacement-suffix)
                                  expr)))
                    '(generic s8       u8       s16       u16       s32       u32       s64       u64       f32       f64       char)
                    '(vector  s8vector u8vector s16vector u16vector s32vector u32vector s64vector u64vector f32vector f64vector string))
             (else
              ;; There are conversion routines required for getters and setters of other standard storage classes.
              ,expr)))

    (define-macro (expand-getters expr)
      `(expand-storage-class -getter -ref ,expr))

    (define-macro (expand-setters expr)
      `(expand-storage-class -setter -set! ,expr))
```
It just replaces the name with a more specific name, but I'd have to somehow, if it was a `-set!`, rather than a `-ref`, add a `(void)` at the end of the expression, too.

Which is possible, but this is getting pretty baroque.

Brad

**Comment by feeley** [comment]
I did an analysis of the runtime system to see what are the side-effectful primitives whose result is not discarded (which does not imply that the result is actually used).  I get this list for each module:

```
_io.scm
  ##unchecked-structure-set!
  ##vector-set!
  ##closure-set!
  ##set-car!
  ##set-cdr!
  ##set-box!

_num.scm
  ##bignum.mdigit-set!
  ##bignum.adigit-shrink!
  ##bignum.adigit-copy!
  ##bignum.adigit-cat!
  ##bignum.adigit-bitwise-and!
  ##bignum.adigit-bitwise-andc1!
  ##bignum.adigit-bitwise-andc2!
  ##bignum.adigit-bitwise-eqv!
  ##bignum.adigit-bitwise-ior!
  ##bignum.adigit-bitwise-nand!
  ##bignum.adigit-bitwise-nor!
  ##bignum.adigit-bitwise-not!
  ##bignum.adigit-bitwise-orc1!
  ##bignum.adigit-bitwise-orc2!
  ##bignum.adigit-bitwise-xor!
  ##bignum.fdigit-set!
  ##f64vector-set!

_std.scm
  ##symbol-name-set!
  ##symbol-hash-set!
  ##keyword-name-set!
  ##keyword-hash-set!
  ##set-car!
  ##set-cdr!
  ##vector-set!
  ##vector-shrink!
  ##u8vector-set!
  ##u8vector-shrink!
  ##s8vector-set!
  ##s8vector-shrink!
  ##u16vector-set!
  ##u16vector-shrink!
  ##s16vector-set!
  ##s16vector-shrink!
  ##u32vector-set!
  ##u32vector-shrink!
  ##s32vector-set!
  ##s32vector-shrink!
  ##u64vector-set!
  ##u64vector-shrink!
  ##s64vector-set!
  ##s64vector-shrink!
  ##f32vector-set!
  ##f32vector-shrink!
  ##f64vector-set!
  ##f64vector-shrink!
  ##values-set!
  ##string-set!
  ##string-shrink!
  ##promise-state-set!

_repl.scm
  ##vector-set!
  ##set-cdr!

_eval.scm
  ##vector-set!

_nonstd.scm
  ##will-testator-set!
  ##will-action-set!
  ##set-box!
  ##set-car!

_kernel.scm
  ##set-car!
  ##closure-set!
  ##continuation-frame-set!
  ##continuation-denv-set!
  ##global-var-set!
  ##global-var-primitive-set!
  ##structure-type-set!
  ##unchecked-structure-set!

_thread.scm
  ##unchecked-structure-set!
  ##primitive-lock!
  ##primitive-unlock!

_system.scm
  ##subtype-set!
  ##u8vector-set!
  ##s8vector-set!
  ##u16vector-set!
  ##s16vector-set!
  ##u32vector-set!
  ##s32vector-set!
  ##u64vector-set!
  ##f64vector-set!
  ##f32vector-set!
  ##s64vector-set!
  ##u8vector-set!
  ##vector-set!
  ##unchecked-structure-set!

_module.scm
  ##global-var-set!
```

So it seems like it would be manageable (but still a lot of work) to refactor the runtime system to avoid relying on the result of the side-effectful primitives, in other words rewrite `(vector-set! a b c)` to `(begin (vector-set! a b c) (void))` or `(begin (vector-set! a b c) a)` depending on the situation.  Once that refactoring is done the side-effectful primitives could then be redefined to always return void.

**Comment by feeley** [comment]
Given that this issue is in the context of implementing SRFI 231 and you want the code to be portable to other Scheme systems, it is wise to make the changes to the SRFI 231 implementations to avoid the same issue with another Scheme (or an older version of Gambit).

**Comment by gambiteer** [comment]
Thanks for the analysis and the advice.

I'm learning lots about the loose specification of Scheme (although I have the impression that R6RS nails down more things).

See https://github.com/ashinn/chibi-scheme/issues/899#issuecomment-1483915107 and the comments that follow, too; I'm just learning about continuations.

I remember about 20+ years ago, each time Gambit was rebuilt, it reversed the order of evaluation of arguments.  I wonder whether that is still the case.

**Comment by gambiteer** [comment]
I just realized that `(void)` is not part of any Scheme standard, I don't think.  Here's a table: https://docs.scheme.org/surveys/void-value/ that may not be current.

I suppose I could suggest people `(define (void) (if #f #f))`.  That won't work in Racket, which doesn't allow one-armed `if`s, but Racket already has `(void)`.  Chibi doesn't have it, though.
