### ISSUE TITLE
string-tokenize crashes with UTF-8 chars

### ISSUE THREAD

**Issue by rgherdt** [gambit/gambit#822]
There is a problem in srfi-14's `si=0?` procedure leading to a crash when dealing with UTF-8 chars:

```
> (import (srfi 13))
> (string-tokenize "a→ c")
*** ERROR IN srfi/14#si=0? -- (Argument 2, k) Out of range
(string-ref
 "\x0;\x0;\x0;\x0;\x0;\x0;\x0;\x0;\x0;\x0;\x0;\x0;\x0;\x0;\x0;\x0;\x0;\x0;\x0;\x0;\x0;\x0;\x0;\x0;\x0;\x0;\x0;\x0;\x0;\x0;\x0;\x0;\x0;\x1;\x1;\... #2
 8594)
1> 
```

Tested on Gambit v4.9.4 and Gambit v4.9.4-180-g266c81f3.

**Comment by feeley** [comment]
Fixed by commits 5ef6d4e05cad88bde25e2527f3d58380e864d970 and 94be9216ac580768a5d0a96acc911072d3ef4e45.
