### ISSUE TITLE
Support import with prefix

### ISSUE THREAD

**Issue by lassik** [gambit/gambit#826]
Is the following syntax unsupported:

```
> (import (prefix (gambit) g:))
*** ERROR IN (stdin)@1.9 -- Ill-formed import set`
```

Per R7RS, this is supposed to prepend `g:` to all the imported tokens.

For example `g:open-process`, `g:create-directory`, etc.

**Comment by feeley** [comment]
The issue is that `g:` is a keyword... try `|g:|`.
