### ISSUE TITLE
Build error in module srfi/42, Arch Linux

### ISSUE THREAD

**Issue by stefanhusmann** [gambit/gambit#839]
Under Arch Linux building the git sources currently fails. The last commit that was working for me was 
4.9.4.r180.g266c81f3.

GCC 13.1.1 [buildlog2.txt](https://github.com/gambit/gambit/files/12073559/buildlog2.txt)

Clang 15.0.7 gives a completely different error. 
[buildlog3.txt](https://github.com/gambit/gambit/files/12073584/buildlog3.txt)

**Comment by gambiteer** [comment]
I find `buildlog2.txt` confusing.
What's the `configure` command you used?
What series of build commands did you give to build gambit?

**Comment by stefanhusmann** [comment]
I run configure twice. This is my build function:  
``` bash
build() {
  cd gambit-scheme
  export CFLAGS=`echo " $CFLAGS " | sed -e "s/-O1 / /g" -e "s/ -O2 / /g" -e "s/ -O3 / /g"`
  export CXXFLAGS=`echo " $CXXFLAGS " | sed -e "s/-O1 / /g" -e "s/ -O2 / /g" -e "s/ -O3 / /g"`
  ./configure
  make
  ./configure --prefix=/usr \
      --docdir=/usr/share/gambit-c \
      --infodir=/usr/share/info \
      --libdir=/usr/lib/gambit-c \
      --disable-shared \
      --enable-compiler-name=gambitc \
      --enable-interpreter-name=gambiti \
      --enable-single-host \
      --enable-c-opt 
  make
  make doc 
}
```

**Comment by gambiteer** [comment]
I could not reproduce the problem on my Ubuntu 22.04 box with `gcc version 11.3.0 (Ubuntu 11.3.0-1ubuntu1~22.04.1)`. for which the second `make` ran to completion.  I don't know how to proceed.

**Comment by feeley** [comment]
This is not directly related to the issue, but the `--enable-c-opt` is not recommended anymore.  Here is what `INSTALL.txt` says about it:

```
The --enable-c-opt option can be used to enable a higher C
optimization level (-O2 instead of -O1) as follows:

  % ./configure --enable-single-host --enable-c-opt

However this is no longer recommended with recent versions of GCC
because -O1 often generates better code from the C code generated by
the Gambit compiler.

By using the --enable-c-opt option and GCC 4.2.1 (a rather old version
at this point) the speed of the Gambit interpreter improves by roughly
10%.  Note that some C compilers generate incorrect code when
compiling Gambit with --enable-c-opt, notably GCC 4.6.0 .  So the
--enable-c-opt option should be used with great care.
```

Also, the use of `-O2` slows down the gcc compiler considerably, in particular when Gambit is configured with `--enable-single-host`. So given that when using `--enable-c-opt` the run time performance is often worse and the compile time is often longer it should not be used unless for a very specific application it makes sense (for example when using an old gcc compiler).

Moreover, the `--enable-march=native` option is recommended for best performance:

```
The --enable-march=native option will use C compiler options to
optimize the system for best execution speed on the machine
architecture that is used for the build.  This may restrict the
execution to that specific machine architecture.
```

**Comment by feeley** [comment]
I haven't tried it (I don't have access to an Arch installation), but I think removing `--enable-c-opt` will solve the issue. The error messages look like gcc was having a hard time optimizing the code at `-O2` because the C functions are large (due to the `--enable-single-host`).

**Comment by feeley** [comment]
By the way there is no reason to configure twice. This was useful many years ago, when Gambit's bootstrap was explicit. But now a `make` automatically does a bootstrap.

**Comment by stefanhusmann** [comment]
Removing --enable-c-opt indeed did the trick. Thanks.

**Comment by feeley** [comment]
@stefanhusmann Gambit v4.9.5 has just been release. I figure you may be interested to know this if you are packaging Gambit.
