### ISSUE TITLE
Constant-folding of arithmetic-shift failure in MINGW32

### ISSUE THREAD

**Issue by gambiteer** [gambit/gambit#840]
Marc:
This failure looks interesting, and maybe real.  From https://github.com/gambit/gambit/actions/runs/5637051577/job/15269740316
```
../gsc/gsc.exe -:~~bin=../bin,~~lib=../lib,~~include=../include -f -target js  -prelude "(define-cond-expand-feature|enable-type-checking|)(define-cond-expand-feature|disable-auto-forcing|)(define-cond-expand-feature|enable-sharp-dot|)(define-cond-expand-feature|enable-bignum|)(define-cond-expand-feature|enable-ratnum|)(define-cond-expand-feature|enable-cpxnum|)(define-cond-expand-feature|enable-s8vector|)(define-cond-expand-feature|enable-u16vector|)(define-cond-expand-feature|enable-s16vector|)(define-cond-expand-feature|enable-u32vector|)(define-cond-expand-feature|enable-s32vector|)(define-cond-expand-feature|enable-u64vector|)(define-cond-expand-feature|enable-s64vector|)(define-cond-expand-feature|enable-f32vector|)(define-cond-expand-feature|disable-smp|)(##include\"../lib/header.scm\")" -label-namespace "" -c -o _gambit.js ../lib/_univlib.scm
*** ERROR IN _t-univ-4# -- (Argument 1) Finite REAL expected
(floor +23170.475027499975i)
```
It appears to be caused by this line:
```
[Bradleys-Mac-mini:~/programs/gambit/gsc] lucier% grep -n '(floor ' _t-univ-4.scm
189:    (let ((max-sqrt (inexact->exact (floor (sqrt univ-fixnum-max)))))
```

**Comment by gambiteer** [comment]
Argghh.  I introduced this problem with https://github.com/gambit/gambit/commit/266c81f38c071eb3bb4fdd922f99cbfa7a5b2e28.

**Comment by gambiteer** [comment]
Marc:  This change fixes the issue, but I'm not entirely sure why:
```
heine:~/programs/gambit/gambit> git diff
diff --git a/gsc/_prims.scm b/gsc/_prims.scm
index bcfe43d7..c356315c 100644
--- a/gsc/_prims.scm
+++ b/gsc/_prims.scm
@@ -4,7 +4,7 @@
 
 ;;; Copyright (c) 1994-2022 by Marc Feeley, All Rights Reserved.
 
-(include "fixnum.scm")
+(include "generic.scm")
 
 ;;;----------------------------------------------------------------------------
 ;;
```
It looks like `arithmetic-shift` is specialized to `fxarithmetic-shift`, `unsafe` is declared, and now that `fxarithmetic-shift` is evaluated at compile time, you get the incorrect code expansion for
```
(define univ-fixnum-max+1
  (arithmetic-shift 1 (- univ-word-bits (+ 1 univ-tag-bits))))
```

**Comment by gambiteer** [comment]
I can reproduce the problem on x86 Ubuntu 22.04 building a 32-bit Gambit with `./configure CC='gcc -m32' --enable-single-host`.

I think my analysis above is not entirely correct, but I think that's the right fix.

**Comment by feeley** [comment]
It may cause less code bloat of the `_prims` module to do:

```
(let ()
  (declare (generic))
  (define (nonneg-fix32? x) (and (fix32? x) (>= x 0)))
  (define (shift-left n shift) (arithmetic-shift n shift))
  (define (shift-left? n shift) (and (>= shift 0) (shift-left n shift)))
  (define (shift-right n shift) (arithmetic-shift n (- shift)))
  (define (shift-right? n shift) (and (>= shift 0) (shift-right n shift)))
  (def-simp "arithmetic-shift"          (constant-folder-gen shift-left int?))
  (def-simp "fxarithmetic-shift"        (constant-folder-fix shift-left fix32?))
  (def-simp "fxarithmetic-shift?"       (constant-folder-fix shift-left fix32?))
  (def-simp "fxarithmetic-shift-left"   (constant-folder-fix shift-left (list fix32? nonneg-fix32?)))
  (def-simp "fxarithmetic-shift-left?"  (constant-folder-fix shift-left? fix32?))
  (def-simp "fxarithmetic-shift-right"  (constant-folder-fix shift-right (list fix32? nonneg-fix32?)))
  (def-simp "fxarithmetic-shift-right?" (constant-folder-fix shift-right? fix32?)))
```

**Comment by gambiteer** [comment]
That may be, but we're definitely doing something wrong with compile-time evaluation of `arithmetic-shift`.
Here's a short program:
```
heine:~/programs/gambit/gambit> cat shift.scm
(declare (standard-bindings))

(define a (arithmetic-shift 1 29))
```
and here's the compilation expansion with a 32-bit x86 binary:
```
heine:~/programs/gambit/gambit> gsc/gsc -:~~bin=bin,~~lib=lib,~~include=include -warnings -expansion shift.scm
Expansion:

(define a -536870912)
```
And now I have no hypothesis.

**Comment by feeley** [comment]
Is that with my fix or not? Clearly with the `(include "fixnum.scm")` the `(define (shift-left n shift) (arithmetic-shift n shift))` will be problematic because it will be compiled as `(define (shift-left n shift) (fxarithmetic-shift n shift))`, which will give an incorrect result when there is a 32-bit fixnum overflow.

**Comment by gambiteer** [comment]
I didn't understand the point you were trying to make (to make the `(declare (generic))` local rather than global).

Your change fixes the problem.  My issue is, why the problem exists at all.  If I compile
```
(declare (standard-bindings))

(define a (arithmetic-shift 1 29))

(define b (fxarithmetic-shift 1 29))

(define c (fxarithmetic-shift 1 28))

```
I see, with your fix,
```
heine:~/programs/gambit/gambit> gsc/gsc -:~~bin=bin,~~lib=lib,~~include=include -warnings -expansion shift.scm
Expansion:

(define a 536870912)

(define b (let ((temp.2 ('#<procedure #2 ##fxarithmetic-shift?> 1 29))) (if temp.2 temp.2 ('#<procedure #3 fxarithmetic-shift> 1 29))))

(define c 268435456)
```
I don't understand why it screws up in `_prims.scm`. 

I compiled `shift.scm` with `(declare (fixnum))` at the top of the file, too, and got
```
heine:~/programs/gambit/gambit> gsc/gsc -:~~bin=bin,~~lib=lib,~~include=include -warnings -expansion shift.scm
Expansion:

(define a (let ((temp.2 ('#<procedure #2 ##fxarithmetic-shift?> 1 29))) (if temp.2 temp.2 ('#<procedure #3 fxarithmetic-shift> 1 29))))

(define b (let ((temp.5 ('#<procedure #2 ##fxarithmetic-shift?> 1 29))) (if temp.5 temp.5 ('#<procedure #3 fxarithmetic-shift> 1 29))))

(define c 268435456)
```
so again, no problem.  I don't know why it's a problem in `_prims.scm`.
If you want me to make that small addition to `_prims.scm` and forget about it, I'll do it.

**Comment by feeley** [comment]
The problem is the combination `(declare (fixnum) (not safe))` in the module `_prims.scm`, which means `(define (shift-left n shift) (arithmetic-shift n shift))` will generate a negative fixnum (because the final check is `(fix32? result)` and the most negative fixnum on a 32 bit build of Gambit will satisfy that test.

So adding `(declare (generic))` is the correct solution here.

Nice catch BTW!

**Comment by gambiteer** [comment]
Yeah, well, it took me forever to see that the `(not safe)` is declared in `lib/header.scm`, which isn't included in the files directly but only by a command-line option to `gsc-boot`.
You really should remove the final continuous integration check of "Report Results to gitter"  now that that part of gitter's  API doesn't work.  I would have caught this problem earlier if I hadn't become inured to the failures of all the git checkins.
