### ISSUE TITLE
SRFI/231 has missing type checks

### ISSUE THREAD

**Issue by feeley** [gambit/gambit#841]
This should raise a type check exception rather than a segfault:

```
> (import (srfi 231))
> (define a (make-specialized-array (make-interval (vector 5)) f64-storage-class)) 
> (array-set! a 12.3 2.5)
Segmentation fault: 11
```

**Comment by gambiteer** [comment]
In SRFI 231, type checks are a run-time option, not a compile-time option:
```
>  (import (srfi 231))
> (specialized-array-default-safe? #t)
> (define a (make-specialized-array (make-interval (vector 5)) f64-storage-class)) 
> (array-set! a 12.3 2.5)
*** ERROR IN (stdin)@4.1 -- array-setter: multi-index component is not an exact integer:  2.5
1> 
```
The default is that specialized arrays are mutable and not safe.
I'm not sure that was the correct default, but that's what it is.

**Comment by feeley** [comment]
Hmmm. That is an unexpected way to enable type checks. I would have created 2 variants of the SRFI: `(srfi 231)` and `(srfi 231 unsafe)` so that 1) by default you get the type checks, and 2) there is not need to check a type checking flag at run time (which impacts performance of both the safe and unsafe variants).

**Comment by gambiteer** [comment]
An array's getter and setter are closures constructed when the array is created; it's at array-creation time that a choice is made between closures that have checks and closures that don't, depending on the parameter `specialized-array-default-safe?`.
Your comment about having checks on by default is pertinent; I've now come to regret having a default that allows a crash with a programming error.
