### ISSUE TITLE
Undefined symbol ___clrsbdi2

### ISSUE THREAD

**Issue by jdf-id-au** [gambit/gambit#847]
In a similar vein to [this OpenSSL linking problem](https://github.com/gambit/gambit/issues/487), I'm getting a linker error while trying to [resuscitate gambit-objc](https://github.com/maitria/gambit-objc/issues/3), on:

- gambit 4.9.5 (via homebrew)
- macOS Ventura 13.4.1 (c)
- intel cpu

```
Undefined symbols for architecture x86_64:
  "___clrsbdi2", referenced from:
      ____H___num in libgambit.a(_num.o)
      ____H___system in libgambit.a(_system.o)
```

I can't find any direct reference to anything containing the string `clrs` in [`_num.c`](https://github.com/gambit/gambit/blob/master/lib/_num.c) or [`_system.c`](https://github.com/gambit/gambit/blob/master/lib/_system.c), and I assume it has something to do with [this LLVM issue](https://reviews.llvm.org/D50168) but don't have the experience to unpick it.

Do experienced eyes see an obvious solution?

**Comment by feeley** [comment]
It looks like the linker is not finding the GNU library which should contain that symbol that is part of the implementation of the `__builtin_clrsb` GCC builtin.

If this is the only issue, a solution is to configure Gambit to avoid using that GCC builtin using `./configure ... CC="gcc-13 -D___DONT_USE_builtin_clrsb"`. Gambit's header file `include/gambit.h` has many hooks like this to disable features and optimizations that may cause issues on some systems.

Please close this issue if that is an adequate solution.

**Comment by jdf-id-au** [comment]
Ah thank you. Actually switching to real `gcc-13` (rather than the clang 14.0.3 alias) was enough to resolve the problem.
