### ISSUE TITLE
Please review conversion of wiki from mediawiki to github flavored markdown

### ISSUE THREAD

**Issue by jeffhhk** [gambit/gambit#863]
Hi Marc,

Wiki repositories and regular github repositories have a couple of important differences.  First, as far as I'm aware, Pull Requests cannot apply to wiki repositories.  Second, I think the permission to push on a github wiki is related to permission to push on the parent repository.  I don't know of a way to grant one without granting the other.

I think I have done the portion of wiki format conversion that can be accomplished effectively with scripts.  The remainder will have to be hand cleanup.

Draft conversion: https://github.com/jeffhhk/gambit_wiki
And script: https://gist.github.com/jeffhhk/57a924ea864210c5f358d5420f31c5d2

This was one of those tasks where the last mile was even messier than usual. wget can perform broken link checking, but only against html served over http. Github these days is rendering wiki with the help of javascript, so wget is not sufficient to get the page content. To mitigate, I attempted to do a second round of conversion using pandoc from .md to html, but this too failed because pandoc neglects to convert the .md extension in links to .html extensions.

As I was filing this issue, the branch was rebased to the HEAD of your master branch.

For Gambit, I have neither permission to push to the wiki nor permission to push to the main repository.  So I propose: If you approve of the changes, please manually merge the code to the official repository.  Here is one way:

```
    git clone git@github.com:gambit/gambit.wiki.git foo
    cd foo/
    git remote add originjeff https://github.com/jeffhhk/gambit_wiki
    git fetch originjeff
    git merge originjeff/master
    git push origin master
```

Regards,

Jeff

**Comment by feeley** [comment]
Thanks for the conversion of the old wiki! I have applied your changes. I have also updated the gambitscheme.org landing page to include a "Wiki" tab that opens the wiki on github.
