### ISSUE TITLE
Executable does NOTHING, when importing srfi-module (but code works in REPL)

### ISSUE THREAD

**Issue by klartext** [gambit/gambit#872]
There is some code that works in REPL and works as executable.
After adding a SRFI via import, the compiled code does nothing.
No warings in compilation, not even error message when running.
But in the REPL the code runs as expected.

```
; Read lines from textfile 'input.txt'
; as list and then print the lines.
; Without the import-statements, the code works fine.
;
; But when importing with one of the two import lines below,
; the executable is not working anymore.
; No error messages, but also nothing happens.
;
; Used gambit-c 4.9.4 (Arch-Package gambit-c 4.9.4-4)
; and compiled with:
; gambitc -exe <filename>

; When loading into the repl ("gsi"), the code works
; as expected - with and without using one of the import statements.


;(import (srfi 13))
;(import (gambit) (srfi 13))


(define (read-lines-from-port port lines)
  (let ((line (read-line port)))
    (if (not (eof-object? line))
        (read-lines-from-port port (cons line lines))
        (reverse lines))))


(define infile "input.txt")
(define inport (open-input-file infile))
;(define inport (current-input-port))

(define lines-from-input (read-lines-from-port inport '()))
;(define lines-from-input (read-lines-from-port (current-input-port) '()))

(println "------- Read lines ------------")
(display lines-from-input)

; Importing AFTER the above code instead before it also does disable
; the functionality of the file-reading code.
;(import (srfi 13))
;(import (gambit) (srfi 13))
```

**Comment by feeley** [comment]
This is a repeat of issue #800. The problem is due to how the Gambit linker works, which adds a minor hurdle when there are external libraries (scheduled to be streamlined in the not too distant future). Your specific issue can be solved by adding the `-nopreload` flag when compiling the program, i.e. `gambitc -exe -nopreload <filename.scm>`.

Note that your program can be greatly simplified by using the predefined `read-file-as-string-list`:

```
(display (read-file-string-list "input.txt")) ;; get file as a list of the lines
```

or

```
(define infile (open-input-file "input.txt"))
(display (read-all infile read-line)) ;; repeatedly call read-line to create a list of strings
```

or

```
(define infile (open-input-file "input.txt"))
(display (read-line infile #f)) ;; read file content as a single string
```

All of these alternatives avoid the need for an external library, so `-nopreload` is not needed.

**Comment by klartext** [comment]
Thank you for your quick detailed answer.

As this was code to show the issue, the function I wanted to use was not in the code.
I intended to use `string-tokenize`, which would need the library-import.

**Comment by klartext** [comment]
IMHO it would be better to have non-standard extensions like the predefined functions you mentioned, also residing in a library (maybe called gamit-extensions).
