### ISSUE TITLE
string-titlecase not available in gsi

### ISSUE THREAD

**Issue by klartext** [gambit/gambit#873]
```
(string-titlecase "abc def")     
*** ERROR IN (stdin)@8.2 -- Unbound variable: string-titlecase
```

Interestingly, the Tab-extension knows `string-titlecase`... but only after the error message was given.
Compiling to executable provides the function and the output looks correct.

Using Gambit v4.9.4

**Comment by gambiteer** [comment]
With the latest Github source I, too, get
```
heine:~> gsi
Gambit v4.9.5-84-g6b19d0c9

> (string-titlecase "abc def")     
*** ERROR IN (stdin)@1.2-1.18 -- Unbound variable: string-titlecase
1>                           
```
but tab completion does not know `string-titlecase`.  (I'm not sure what you mean by Tab-extension.)
After you import SRFI 13, `gsi` has `string-titlecase` available:
```
> (import (srfi 13))
> (string-titlecase "abc def")     
"Abc Def"
```
Also, the behavior is pretty much the same for the interpreter and the compiler; without the `(import (srfi 13))` one gets
```
heine:~> gsi title.scm
*** ERROR IN "title.scm"@1.11-1.27 -- Unbound variable: string-titlecase
 ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ title.scm ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
1┃(println (string-titlecase "abc def"))
heine:~> gsc title.scm
heine:~> gsi title
*** WARNING -- Variable "string-titlecase" used in module "title" is undefined
*** ERROR IN title# -- Operator is not a PROCEDURE
(#!unbound "abc def")
```
and with it one gets
```
heine:~> gsi title.scm
Abc Def
heine:~> gsc title.scm
heine:~> gsi title
*** WARNING -- Variable "srfi/13#string-titlecase" used in module "title" is undefined
Abc Def
```
Is this the behavior you're seeing?

**Comment by klartext** [comment]
> With the latest Github source I, too, get
> 
> ```
> heine:~> gsi
> Gambit v4.9.5-84-g6b19d0c9
> 
> > (string-titlecase "abc def")     
> *** ERROR IN (stdin)@1.2-1.18 -- Unbound variable: string-titlecase
> 1>                           
> ```
> 
> but tab completion does not know `string-titlecase`. (I'm not sure what you mean by Tab-extension.) 

Well, it was late, I meant tab-expansion.


> After you import SRFI 13, `gsi` has `string-titlecase` available:
> 
> ```
> > (import (srfi 13))
> > (string-titlecase "abc def")     
> "Abc Def"
> ```
> 
> Also, the behavior is pretty much the same for the interpreter and the compiler; without the `(import (srfi 13))` one gets

I was looking into R6RS-library description.
There I found `string-titlecase`.
Has that function been moved out with R7RS?


What I get calling gsi on an example file:

```
klartext:~$ cat example.scm
(display (string-titlecase "abc def"))
klartext:~$ gsi example.scm 
*** ERROR IN "example.scm"@1.11 -- Unbound variable: string-titlecase
```

Directly pasting the code into gsi:
```
klartext:~$ gsi
Gambit v4.9.4

> (display (string-titlecase "abc def"))
*** ERROR IN (stdin)@1.11 -- Unbound variable: string-titlecase
1> 
```


Compiling to exe and calling it:
```
klartext:~$ 
klartext:~$ gambitc -exe -nopreload example.scm
klartext:~$ ./example
*** ERROR IN example# -- Operator is not a PROCEDURE
(#!unbound "abc def")
klartext:~$ 
```

My test last night was done in a file, which already included the SRFI13.
So now separating the snippet, leaving the SRFI13-import out, the code also fails when compiling.

**Comment by gambiteer** [comment]
I guess I don't understand what you think should happen, what you think is wrong with what Gambit is doing.

**Comment by klartext** [comment]
I'm sorry, this ticket was rather based on a mistake done in sleepy mode.

**Comment by feeley** [comment]
@klartext Yes string-titlecase is not part of R7RS, but as @gambiteer points out you can get it by importing SRFI 13.

As for tab-completion you have to understand that it uses the symbol-table to determine the possible completions. In other words the proposed completions are the symbols in the symbol table that have the same prefix as what has been typed before pressing the tab key. So, in a fresh REPL, if you try to tab-complete  `(string-title` you will get no completions. If you continue typing with `(string-titlecase "abc def")` and execute that you will get an error. If you then try to again tab-complete `(string-title` you will now get `(string-titlecase` because the symbol `string-titlecase` has been added to the symbol table by the previous (erroneous) command.
