### ISSUE TITLE
'make doc' .info and .txt generation failure

### ISSUE THREAD

**Issue by random-bites** [gambit/gambit#874]
While installing Gambit 4.9.5 (using the UCRT64-MSYS2 environment) the `make doc` step failed to create the gambit info files and the `gambit.txt` file.

When I read the `gambit.txi` file into an Emacs buffer and ran its `makeinfo buffer` command on this file, it gave the following errors and exited.
```
makeinfo --fill-column=70 gambit.txi
gambit.txi:5547: unknown command `rm'
gambit.txi:5547: unknown command `rm'
gambit.txi:5601: unknown command `rm'
gambit.txi:5601: unknown command `rm'
gambit.txi:5601: unknown command `rm'
gambit.txi:5601: unknown command `rm'
```
I wasn't able to find the command `@rm` in the Texinfo documentation (Maybe it is a custom command? I don't know anything about Texinfo.). But, when I commented out lines 5547 and 5601 (and each of the `@end deffn` lines) I was able to compile the file `gambit.txi` to four info files and one text file using the commands I found the file `gambit/doc/makefile`.

NOTE: These are the only two lines with the `@rm` command in `gambit.txi`.

```
Line 5547:
@deffn procedure char-set-hash @var{char-set} @rm{[}@var{bound}@rm{]}
@end deffn
```
```
Line 5601:
@deffn procedure ucs-range->char-set @var{lower} @var{upper} @rm{[}@var{error?} @rm{[}@var{base-cs}@rm{]}@rm{]}
@end deffn
```
I'm using `makeinfo` version 7.1.

**Comment by random-bites** [comment]
After further investigation, it appears to me that the `@rm` is a typo and was supposed to be `@r`.

**Comment by feeley** [comment]
@random-bites Thanks for seeing this typo!
