### ISSUE TITLE
Running configure && make run configure twice

### ISSUE THREAD

**Issue by jcubic** [gambit/gambit#877]
It seems that running `make` (I did `make -j4`) runs configure again. Is it intentional?

**Comment by gambiteer** [comment]
It's part of a bootstrap process.

My understanding is that if you do
```
make clean\
&& rm -rf boot gsc-boot
```
and then
```
./configure <your-build-options>
make core
```
then the C sources from the latest stable release are pulled from git sources, configured with few or no build options,  and it makes the Gambit compiler from the stable C sources.

This is copied to `gsc-boot`, `configure` is called again with the real build options, and `gsc-boot` is used to compile existing `.scm` files to C before building the real libraries and binaries.

I'm going to close this PR; if this doesn't answer your question just reopen it.

**Comment by jcubic** [comment]
I cloned the repo and run `configure && make` as in INSALL.txt and `configure` was run twice. Make did run configure again. How is this fixed?

**Comment by gambiteer** [comment]
There is nothing to "fix".  In my previous answer I gave an explanation why `configure` is invoked twice.  I don't want to just repeat myself, but I don't know how to explain it differently.
