### ISSUE TITLE
Redefining `<` causes `syntax-rules` to segmentation fault

### ISSUE THREAD

**Issue by rich-1170** [gambit/gambit#888]
When `<` is redefined, `syntax-rules` produces an error or segfaults.

Correct:
```
Gambit v4.9.5-105-g98d16c82

> (syntax-rules () ((_) 'ok))
(syntax-rules () ((_) 'ok))
#<procedure #2>
```

Incorrect: redefining `<` to a different procedure causes an error in `syntax-rules`:
```
Gambit v4.9.5-105-g98d16c82

> (define (< x y) 'junk)
(define (< x y) 'junk)
> (syntax-rules () ((_) 'ok))
(syntax-rules () ((_) 'ok))
*** ERROR -- syntax error ((#(#(source1) syntax-rules (stdin) 65537 851969) "list expected"))
```

Incorrect: redefining `<` to a symbol causes `syntax-rules` to segmentation fault:
```
Gambit v4.9.5-105-g98d16c82

> (define < 'junk)
(define < 'junk)
> (syntax-rules () ((_) 'ok))
(syntax-rules () ((_) 'ok))
Segmentation fault
```

The manual entry for `define-syntax` (https://gambitscheme.org/latest/manual/#index-syntax_002drules) mentions that Gambit's macro functionality is implemented in the form of a loaded library: `~~lib/syntax-case`. If I had to guess, redefining any name used in `syntax-case` would break it. 

I suppose this is correct behavior for loaded libraries (https://gambitscheme.org/latest/manual/#Legacy-Modules), but this still seems like a bug. `syntax-rules` is supposed to be a built-in standard scheme procedure, so I would think its internal operation should be protected from the user redefining names.

**Comment by feeley** [comment]
Thanks for spotting this! Yes it is a bug for builtin features to depend on the state of global variables bound to standard procedures. There was a missing redirection of `eq?` -> `##eq?`, etc.
