### ISSUE TITLE
I don't think "2x2-matrix-multiply" is an identifier.

### ISSUE THREAD

**Issue by gambiteer** [gambit/gambit#909]
Chibi rejects "2x2-matrix-multiply" as an identifier, yet
```
> gsi
Gambit v4.9.5-132-g2fd33281

> (define 2x2-matrix-multiply #f)
> 2x2-matrix-multiply
#f
```
The syntax of identifiers in R5Rs and R7RS small both seem to reject "2x2-multiply" as an identifier.
I couldn't find in the Gambit sources where this is lexed.

**Comment by feeley** [comment]
In Gambit, a delimited sequence of characters (i.e. any character except a delimiter like `(`, `)`, `”`, `|`, space, …) is considered to be a symbol if it is not a valid number or keyword. It is allowed for an RnRS implementation to extend the syntax of symbols, and many Scheme implementations have such extensions. Chibi is being strict about the syntax of symbols.
