### ISSUE TITLE
Gambit v4.9.3 - 7.2.2 ##namespace and ##import forms -- the example doesn't work

### ISSUE THREAD

**Issue by jimmy3987** [gambit/gambit#915]
I have been trying to understand the ##namespace concept, and it didn't appear to work as described. 

So, in desperation, I cut-and-pasted the example referred to as "angle2". I created the 3 files and tried to run them, but I get this error: 
------------------------------------
> (load "app2.scm")
*** ERROR IN "app2.scm"@2.2 -- Unbound variable: ##demand-module
1> 
------------------------------------
Am I doing something incorrectly here, or is this a fault of some kind in Gambit v4.9.3? The command ##namespace itself is accepted, and following it, all variables are prefixed by the name of the namespace, but nothing else appears to work as described. 

My thanks for any help that you can give regarding this matter.

**Comment by feeley** [comment]
v4.9.3 is 5 years old. The form `##demand-module` was added to Gambit 4 years ago, so you need to upgrade to at least v4.9.4. The current release is v4.9.5.

**Comment by jimmy3987** [comment]
Thank-you for your help with issue #915.

Jim.
________________________________
