### ISSUE TITLE
Handling of invalid string escape sequences

### ISSUE THREAD

**Issue by maconcg** [gambit/gambit#931]
In working on writing some unit tests for R7RS string procedures, I discovered a bug that is triggered by evaluating certain string escape sequences in the REPL.  It may also occur in other contexts (and may not even be limited to the REPL) -- still looking.

It occurs on both macOS and OpenBSD, for both my built-from-git and built-from-release-tarball Gambits, in a conventional terminal emulator as well as with those `INSIDE_EMACS` scenarios I've been going on about.

Here is the simplest way to trigger it:
```
> "\x0"
*** ERROR IN (stdin)@1.1-1.5 -- Invalid hexadecimal escape
> "\x0"
"\n"
> "\x0"
*** ERROR IN (stdin)@2.5-3.2 -- Invalid infix syntax
> "\x0"
*** ERROR IN (stdin)@3.5-4.2 -- Invalid infix syntax
> ,q
,q
,q
```
You can also trigger this via `"\o0"`, `"\U1234567"`, and some other sequences.

One bit of potentially-relevant information is that the Gambit documentation mentions the sequences `\xhh`, `\ooo`, etc. (as opposed to the r7rs `\xhh;` with the semicolon).

I'll try to figure out a fix, and once I do I'll also submit any necessary doc fixes, but in the meantime I thought I'd create an issue to ask for pointers / let someone who might be faster than me beat me to the punch.

**Comment by feeley** [comment]
What you are doing is entering `"\x0` without a terminating `;` so the parser declares that there is an error, then it starts reading at the `"` followed by a newline and then another `"` which ends the string!

So I'm not sure this actually counts as a bug.

**Comment by maconcg** [comment]
Indeed, it's only invalid escape sequences that trigger this -- you have to do something wrong to get here, so it may not be worth looking too hard at.  I probably didn't highlight the two issues that made me want to open this:

1. It puts your REPL into a werid state where you can't kill it via the usual mechanisms (`,q` `(exit)`).
2. The error messages seem wrong (specifically "Invalid infix syntax").

The quickest fix would just be to mention the need to use a terminating `;` in the docs.  Do you think that'd be sufficient?

**Comment by feeley** [comment]
The `,q` commands are ignored because after the error you are reading characters that are accumulated in a string. Many Scheme implementations will behave this way if you start a string on the first line of the REPL (the characters will accumulate, even on following lines, until a `"` is encountered).

The "invalid infix syntax" error is because when the reader encounters the `\` it is outside of a string, so Gambit's SIX parser is triggered:

```
> (list "abc '\n+1")
("abc '\n+1")
> (list "abc" '\n+1)
("abc" (six.infix (six.x+y (six.identifier n) (six.literal 1))))
```

So while all of this behaviour is explainable, I see your point that it can be confusing. The solution may be to change the REPL's reader to flush the rest of the input line when a reader syntax error is encountered.

**Comment by maconcg** [comment]
I'm second-guessing myself because this seems like such a simple fix, but it seems to produce the (imo) more intuitive behavior.

```
diff --git a/lib/_repl.scm b/lib/_repl.scm
index 19f470ae..61b42687 100644
--- a/lib/_repl.scm
+++ b/lib/_repl.scm
@@ -4175,6 +4175,7 @@
               (if x (##cdr x) "Unknown datum parsing exception")
               port))
            (write-items (macro-datum-parsing-exception-parameters exc))
+           (##read-line (##repl-input-port))
            (##newline port))
 
           ((macro-deadlock-exception? exc)
```

Would this patch do it? If so, I'll submit it as a PR with doc changes.

**Comment by lassik** [comment]
> The solution may be to change the REPL's reader to flush the rest of the input line when a reader syntax error is encountered.

👍

**Comment by feeley** [comment]
That's really not where such a logic should go. The lines you mention are in the implementation of `display-exception` and that procedure (or variants) can be called in many different contexts, not just because of REPL input. For example `(with-input-from-string "(bad!" read)`.

Rather, it should be in

```
(define-prim (##repl-channel-ports-read-command channel level depth)

  (define prompt "> ")

  (let ((output-port (macro-repl-channel-output-port channel)))
    (##exit-with-exception-on-exception
     (lambda ()
       (if (##fx< 0 depth)
           (begin
             (##write-string "[" output-port)
             (##write depth output-port)
             (##write-string "]" output-port)))
       (if (##fx< 0 level)
           (##write level output-port))
       (##write-string prompt output-port)
       (##force-output output-port))))

  ((macro-repl-channel-ports-read-expr channel) channel))
```

**Comment by feeley** [comment]
But it is not the implementation that worries me. The question is rather what is the best behaviour for the REPL. You also have to consider that the REPL may be used in a pipe, to pipe input to the REPL as though a user was entering commands. What to do if one fails?

**Comment by maconcg** [comment]
This reminds me somewhat of when I was writing documentation for `##os-executable-path` and I had tried my best to pick a _non_-deterministic example that used `mktemp -d`.  This time I tried my best to _only_ affect the REPL.  Oof.

> You also have to consider that the REPL may be used in a pipe, to pipe input to the REPL as though a user was entering commands.

Just to make sure I'm not off track, could you show me an example of how to do this? My unsuccessful attempts to follow along look this:

```
$ echo '(pp "hello gambit")' | /usr/local/bin/gsi - | nl
     1	> "hello gambit"
     2	> 
     3	*** EOF again to exit
```

**Comment by maconcg** [comment]
Also, here is a before/after comparison that shows the narrow behavior I was targeting with that patch:

```
$ /usr/local/bin/gsi
Gambit v4.9.5

> "\When in the Course"
*** ERROR IN (stdin)@1.1 -- Invalid escaped character: #\W
> *** ERROR IN (stdin)@1.4 -- Unbound variable: hen
1> *** ERROR IN (stdin)@1.8 -- Unbound variable: in
2> *** ERROR IN (stdin)@1.11 -- Unbound variable: the
3> *** ERROR IN (stdin)@1.15 -- Unbound variable: Course
4> ,q
(exit)
"
"\n,q\n(exit)\n"
4> ,q
$
```

```
$ /usr/local/Gambit/bin/gsi
Gambit v4.9.5-199-g238953af

> "\When in the Course"
*** ERROR IN (stdin)@41.1-41.4 -- Invalid escaped character: #\W
> 42
42
> ,q

```

**Comment by feeley** [comment]
Why do you say unsuccessful? What you show is the expected behaviour. Here is another:

```
$ echo "(+ 1 2) (* 3 4) (make-string 10)" | gsi
Gambit v4.9.5-140-g37f022c0

> 3
> 12
> "\x0;\x0;\x0;\x0;\x0;\x0;\x0;\x0;\x0;\x0;"
> 
*** EOF again to exit
```

**Comment by maconcg** [comment]
I thought it was unsuccessful because I hadn't managed to actually drop into a REPL.  I thought the use case you were describing was to essentially "preload" some commands into the REPL.

**Comment by feeley** [comment]
If you want the program to use the controlling TTY as the REPL channel, then you have the `-:dc` option for that:

```
$ echo "(+ 1 2) (* 3 4) (make-string 10)" | gsi -:dc
Gambit v4.9.5-140-g37f022c0

> (read ##stdin-port)
(+ 1 2)
> (read ##stdin-port)
(* 3 4)
> (read ##stdin-port)
(make-string 10)
> (read ##stdin-port)
#!eof
> ,q
```
As you can see, the standard input is not the same thing as the console.

**Comment by maconcg** [comment]
Thank you for the pointer about `gsi -:dc`.  That also helped me fix a problem with the echo PR I've been working on.

Gonna think on this for a bit.

**Comment by feeley** [comment]
It wasn't too hard to fix and at the same time I changed the behaviour so that after a valid REPL command, the rest of the line is flushed if it is whitespace. This means the old behaviour:

```
> (read-char)
#\newline
```
which reads the newline at the end of the input line now gives the opportunity to enter a character on the next line:
```
> (read-char)
x
#\x
```
